### ISSUE TITLE
no svg export for webgl rendered graphs 

### ISSUE THREAD

**Issue by cldougl** [plotly/documentation#1007]
note that we do not offer svg export for webgl rendered graphs 
- [x] https://plot.ly/python/static-image-export/
- [x] https://plot.ly/javascript/static-image-export/
- [x] https://plot.ly/r/static-image-export/

**Comment by nicolaskruchten** [comment]
We should make it extra-clear which graphs are webgl (e.g. scatter3d doesn't have gl in the name) and point out that it's actually not the SVG that fails so much as the fact that anything rendered with WebGL will come out rasterized and not vectorized.

Should we add a note in the product as well?

**Comment by cldougl** [comment]
I'd suggest adding a note in the documentation and pricing page (https://github.com/plotly/plotly-next/issues/114) rather than the product (I feel like at that point it's a bit late)
