### ISSUE TITLE
add links to dash on all shiny pages

### ISSUE THREAD

**Issue by bcdunbar** [plotly/documentation#1008]
add a link to dash https://plot.ly/products/dash/ in the sidebar on https://plot.ly/r/shiny-gallery/ and all individual shiny examples.

something like "Know Python? Check out [Dash](https://plot.ly/products/dash/)" <- not set in stone ... open to anything better

**Comment by michaelbabyn** [comment]
closed by [#1017](https://github.com/plotly/documentation/pull/1017)
