### ISSUE TITLE
joy plot/ridge plot examples

### ISSUE THREAD

**Issue by chriddyp** [plotly/documentation#1018]
Someone in the community forum asked about Ridgeline and Joy Plot charts in Python: https://community.plot.ly/t/ridgeline-joy-plots-in-dash-automatic/12602/3

this might be a nice page of content. https://plot.ly/python/joy-plots. The plots are beautiful too :)

**Comment by chriddyp** [comment]
> Your second link is inactive. Could you please repost?

Sorry this was unclear. This link  https://plot.ly/python/joy-plots is just meant to be the URL of where these new examples should go. It doesn't exist yet.

**Comment by chriddyp** [comment]
Some nice conversation continues in https://community.plot.ly/t/ridgeline-joy-plots-in-dash-automatic/12602/8. In particular, here's a nice example: https://plot.ly/~empet/14632/plotly-joyplotridgelines/#/

**Comment by chriddyp** [comment]
A really nice example here: https://morphocode.com/location-time-urban-data-visualization/
![image](https://user-images.githubusercontent.com/1280389/50254772-646bcf00-03bd-11e9-964e-82ea2711cd53.png)

**Comment by Kully** [comment]
> A really nice example here: https://morphocode.com/location-time-urban-data-visualization/

looks awesome

**Comment by Mahdis-z** [comment]
https://plot.ly/python/violin/

**Comment by tpvasconcelos** [comment]
I wanted to have a little more flexibility into how ridgeline plots are displayed with Plotly (e.g., ensure the correct z-order is used, more flexibility into coloring options, multiple traces per rows, etc...) and ended up building a little fun side project just for this use-case. I'll plug it here in case it can be of help to anyone who runs across this issue: https://github.com/tpvasconcelos/ridgeplot
