### ISSUE TITLE
Alternative icon for "More" thumbnails

### ISSUE THREAD

**Issue by jackparmer** [plotly/documentation#1041]
I never liked how this is a chart icon:

![image](https://user-images.githubusercontent.com/1865834/44362745-e8558f00-a48f-11e8-832f-d93e7be29f25.png)

I think it should be a right arrow icon instead, something from noun-project:

https://thenounproject.com/search/?q=right-arrow

In a company "Text & Background" color: https://brand.plot.ly/

**Comment by Kully** [comment]
Image is updated now:

![mixed](https://user-images.githubusercontent.com/10369095/44365320-75501680-a497-11e8-89e8-a883f2256de0.jpg)
