### ISSUE TITLE
Rename "Custom controls with JavaScript" to "IPywidgets"

### ISSUE THREAD

**Issue by jackparmer** [plotly/documentation#1043]
We should rename this section to "IPywidgets" and streamroll this outdated content on the plot.ly/python homepage:

![image](https://user-images.githubusercontent.com/1865834/44371868-1c8c7800-a4af-11e8-9016-364367f228e7.png)

The 6 widget example notebooks should be replaced with one of @jonmmease 's notebooks from here:

https://github.com/jonmmease/plotly_ipywidget_notebooks/tree/master/notebooks

These 3 remaining codepen/postmessage examples should also be replaced with one of Jon's notebooks:

![image](https://user-images.githubusercontent.com/1865834/44371926-70975c80-a4af-11e8-979a-86da38c71351.png)

With Jon's widget notebooks, I would vote showing an line GIF of each widget in action, since the widgets won't display in GitHub pages. It should be easy to scroll through and understand what the notebook does before downloading it opening it in Binder.

We should also probably rewrite the content here:
https://moderndata.plot.ly/widgets-in-ipython-notebook-and-plotly/

**Comment by Kully** [comment]
@jackparmer most of Jon's notebooks do not replicate the same things that the already existing doc pages provide, eg. a widget slider.

Do you want these original docs replicated or just replaced by the notebooks?

**Comment by Kully** [comment]
Closing in favour of Jon's Issue: https://github.com/plotly/documentation/issues/991
