### ISSUE TITLE
Update moderndata widgets section

### ISSUE THREAD

**Issue by Kully** [plotly/documentation#1051]
We should rewrite content at
https://moderndata.plot.ly/widgets-in-ipython-notebook-and-plotly/
and use the new Plotly FigureWidgets.

cc @jackparmer

**Comment by jackparmer** [comment]
Indeed, I would just replace these 6 examples with Jon's notebooks:

![image](https://user-images.githubusercontent.com/1865834/44607016-050a0380-a7bd-11e8-9f4a-f1ef3722a2a2.png)

And delete the "More example IPython notebooks section." Easy peasy.

It's an old post, but still shows up in Google Search

**Comment by jackparmer** [comment]
I wouldn't edit the HTML - you can change the format of the post so that it's not this 2 column layout. 

Just delete what is there and rewrite it in the Wordpress editor (not in HTML) with a section and GIF for each of the new notebooks.

**Comment by Kully** [comment]
> Just delete what is there and rewrite it in the Wordpress editor (not in HTML) with a section and GIF for each of the new notebooks.

Okay, I wasn't using wordpress - that sounds like the solution! Thanks.

**Comment by Kully** [comment]
Okay the post is updated now. Only thing I couldn't do was get GIFs to display properly. I used pngs of the widgets displayed in the notebooks instead

**Comment by cldougl** [comment]
@Kully can this issue be closed or is something still needed to complete this task?

**Comment by Kully** [comment]
> can this issue be closed or is something still needed to complete this task?

only if Jack is okay with not having GIFs on the page. He wanted them there but I was not able to get them to work.

**Comment by Kully** [comment]
The GIF Issue:

First I uploaded a new gif to the moderndata site:
![screen shot 2018-09-05 at 12 08 29 pm](https://user-images.githubusercontent.com/10369095/45106477-c9e4ca00-b104-11e8-8207-54090388f3af.png)

upload this GIF

![figurewidget-create](https://user-images.githubusercontent.com/10369095/45106496-d36e3200-b104-11e8-8f05-30b0c343c713.gif)

insert the GIF into the layout

![screen shot 2018-09-05 at 12 08 40 pm](https://user-images.githubusercontent.com/10369095/45106525-e54fd500-b104-11e8-8a20-6052b3270f40.png)

then update the page

![screen shot 2018-09-05 at 12 08 49 pm](https://user-images.githubusercontent.com/10369095/45106537-e97bf280-b104-11e8-9c58-0d4adc4fdc7e.png)

and the GIF doesn't animate on the post

![screen shot 2018-09-05 at 12 09 52 pm](https://user-images.githubusercontent.com/10369095/45106559-f8fb3b80-b104-11e8-96c4-f172bb220457.png)

**(go to https://moderndata.plot.ly/widgets-in-ipython-notebook-and-plotly/ to see it live)**
