### ISSUE TITLE
Align footer with plot.ly

### ISSUE THREAD

**Issue by nicolaskruchten** [plotly/documentation#1055]
The footers on pages like help.plot.ly and plot.ly/javascript should match the footer on the homepage or be as close as possible.

**Comment by nicolaskruchten** [comment]
@jdamiba can you take care of this pet peeve of mine please, and generally try to keep the footers in sync across the three properties, wherever practical? :)

**Comment by jdamiba** [comment]
Closed by https://github.com/plotly/documentation/pull/1057 and https://github.com/plotly/plotly.github.io/pull/365
