### ISSUE TITLE
"Download THIS Notebook!" doesn't work in Firefox

### ISSUE THREAD

**Issue by jonmmease** [plotly/documentation#1060]
To reproduce:

 - Visit: https://plot.ly/python/line-and-scatter/ using Chrome
 - Click "Downdload **THIS** Notebook!" button, and you will navigate to the notebook from the notebook_demo account.
  - Visit the same link from Firefox (I'm on 61.0.2 (64-bit) on MacOS)
  - Click the same button and nothing happens. Firefox doesn't respond as if it's trying to load anything.

**Comment by nicolaskruchten** [comment]
We'll clear this up when we do https://github.com/plotly/documentation/issues/1501
