### ISSUE TITLE
python fundamentals section should display 4 tutorials + more

### ISSUE THREAD

**Issue by cldougl** [plotly/documentation#1074]
in order to make this page readable/easier to navigate we have implemented 4 tutorials for each section + the link to more options

![screen shot 2018-09-05 at 4 58 41 pm](https://user-images.githubusercontent.com/2789078/45120733-fca2b880-b12c-11e8-836e-280d2b1267fd.png)

we can remove from the index page: 
- orca management (this is a valuable doc explaining orca implementation but I think the static image export doc is more useful on a low-level user)
- privacy (this is also mentioned in the getting started tutorial and getting started intro on the top of each page)

**Comment by jonmmease** [comment]
I'm fine with "Orca Management" being bumped off the front page.  Where is the front-page status specified?

**Comment by bcdunbar** [comment]
done in https://github.com/plotly/documentation/commit/cc977cf308e94f694277da8f8fa095d48534f87d

@jonmmease in the publisher cell `page_type='example_index'`

**Comment by cldougl** [comment]
yeah it's just noted in the readme in the publisher cell (commented out): https://github.com/plotly/documentation/blob/source-design-merge/_posts/python/README.md#create-python-documentation
but feel free to add an additional note if you think it needs to be further clarified.
