### ISSUE TITLE
https://plot.ly/api/ edit suggestions (round 2)

### ISSUE THREAD

**Issue by cldougl** [plotly/documentation#1075]
follow up to https://github.com/plotly/streambed/issues/11343 (& https://github.com/plotly/documentation/pull/1057 )

- [ ] can we split these rows to be 3 | 2 rather than  4 | 1
- [x] Plotly Open Source Graphing Libraries -> Plotly Open Source Libraries for titles. The graphing libraries can keep this but we can remove graphing from the dash link: 
![screen shot 2018-09-05 at 5 09 55 pm](https://user-images.githubusercontent.com/2789078/45121279-a6cf1000-b12e-11e8-941e-eb1651eb4b45.png)

**Comment by nicolaskruchten** [comment]
I think we should keep "graphing" for JS no? We should also remove the redundant line above the boxes:

![image](https://user-images.githubusercontent.com/203523/45163490-7f278880-b1be-11e8-9f13-08617780f305.png)
