### ISSUE TITLE
Typo in orca install instructions

### ISSUE THREAD

**Issue by jonmmease** [plotly/documentation#1082]
See https://github.com/plotly/plotly.py/issues/1164

In https://plot.ly/python/static-image-export/

```
$ conda install -c plotly-orca psutil
```

Should be

```
$ conda install -c plotly plotly-orca psutil
```

I'd like to get this fixed ASAP.  Is anyone working on docs today that could update this line?  If not I'll open a PR tonight.

**Comment by cldougl** [comment]
@Kully do you want to prioritize making this syntax change today?

**Comment by Kully** [comment]
> @Kully do you want to prioritize making this syntax change today?

Sure!

**Comment by jonmmease** [comment]
Done in #1083
