### ISSUE TITLE
angularaxis/radialaxis confusion

### ISSUE THREAD

**Issue by alexcjohnson** [plotly/documentation#1095]
The reference still has `layout > angularaxis` and `layout > radialaxis`... these are confusing now that we have `layout > polar > angularaxis` and `layout > polar > radialaxis`. Can we either remove these entirely, or clearly mark all these attributes something like "for the deprecated legacy polar trace types, see `layout > polar` instead for use with the new polar trace types"

![screen shot 2018-09-18 at 5 28 42 pm](https://user-images.githubusercontent.com/2678795/45717741-d3d8e500-bb68-11e8-98e0-ab778c9302bc.png)

cc @etpinard

**Comment by etpinard** [comment]
Good call. I'll add a deprecation warning during https://github.com/plotly/plotly.js/pull/3023

**Comment by etpinard** [comment]
https://github.com/plotly/plotly.js/pull/3023 improves the situation, so I'll close this thing.

But please, anyone should feel free to reopen this ticket if deemed not sufficient.
