### ISSUE TITLE
Document the new plotly.js makeTemplate function and layout.template attr

### ISSUE THREAD

**Issue by nicolaskruchten** [plotly/documentation#1111]
This feature is pretty cool and needs some docs (or at least I couldn't find any!): https://github.com/plotly/plotly.js/blob/fc0a1f8313abc17d188481eaabd6dfc1a1fb0922/src/plot_api/template_api.js

**Comment by alexcjohnson** [comment]
#1111 did a great job with `makeTemplate`/`validateTemplate` but didn't address `layout.template` itself though, right?

**Comment by michaelbabyn** [comment]
@alexcjohnson , right, I'll make another PR showing some examples of creating a template from scratch and the special handling of container arrays.

**Comment by nicolaskruchten** [comment]
Do we really need to document the format? I figure people can just use
makeTemplate...?

**Comment by michaelbabyn** [comment]
@nicolaskruchten , I re-looked at https://plot.ly/javascript/reference/#layout-template after we talked and there are some attributes for handling `annotations` and `updatemenus` in a template that would be much clearer with some examples.

> Container arrays (eg `annotations`) have special handling: An object ending in `defaults` (eg `annotationdefaults`) is applied to each array item. But if an item has a `templateitemname` key we look in the template array for an item with matching `name` and apply that instead. If no matching `name` is found we mark the item invisible. Any named template item not referenced is appended to the end of the array, so you can use this for a watermark annotation or a logo image, for example. To omit one of these items on the plot, make an item with matching `templateitemname` and `visible: false`.

**Comment by nicolaskruchten** [comment]
Ok, makes sense
