### ISSUE TITLE
Document color_threshold argumnet to create_dendrogram

### ISSUE THREAD

**Issue by jonmmease** [plotly/documentation#1130]
In the not-yet-released plotly.py 3.4 there will be a new `color_threshold` argument to `create_dendrogram` to control the dendrogram cut height at which clusters are created.

See https://github.com/plotly/plotly.py/pull/1214 for an example.

I think we could just add this example to https://plot.ly/python/dendrogram/

**Comment by cldougl** [comment]
thanks @jonmmease could you ping this issue when 3.4 is released
