### ISSUE TITLE
Typo in plotly cheatsheet for python

### ISSUE THREAD

**Issue by antoinerg** [plotly/documentation#1136]
Link to the Python cheatsheet https://images.plot.ly/plotly-documentation/images/python_cheat_sheet.pdf

There is an error in point 4 in the cheatsheet where it says:
```
trace = "'x':[1,2],'y':[1,2]}
data = [trace]
data = {}
fig = go.Figure(data=data, layout=layout)
```
the third line overwrite data. It should be:
```
trace = "'x':[1,2],'y':[1,2]}
data = [trace]
layout= {}
fig = go.Figure(data=data, layout=layout)
```

Thanks [Sago](https://community.plot.ly/u/Sago) for spotting this 🔎

**Comment by jdamiba** [comment]
I edited the pdf as follows:
[python_cheat_sheet(fixed).pdf](https://github.com/plotly/documentation/files/2687962/python_cheat_sheet.fixed.pdf)

**Comment by jdamiba** [comment]
I uploaded the correct version to images.plot.ly.

**Comment by jdamiba** [comment]
The corrected version is now being served.
