### ISSUE TITLE
Parallel coordinates plot examples do not work

### ISSUE THREAD

**Issue by dnieuw** [plotly/documentation#1150]
The examples at [https://plot.ly/python/parallel-coordinates-plot/](url) do not work.
The interactive setting of thresholds does not highlight the lines.
It does not seem to be the browser I am using, I tested Firefox and Chrome.

**Comment by cldougl** [comment]
Hi @dnieuw -
Can you let us know if you're seeing an issue when trying to recreate the example or rather an issue on the doc site? The hosted examples on the site seem to be working as expected:
![parcoord](https://user-images.githubusercontent.com/2789078/47440385-0d11ff80-d77c-11e8-9a04-ed5c72e50416.gif)

**Comment by dnieuw** [comment]
Hi @cldougl ,

Both the hosted examples and the recreation using a jupyter notebook environment and local plotting of the graph do not work. I was already suspecting that the issue was my computer. Do you have any suggestions on what to look at to try to fix this?

The graph renders, and is interactive, it is just the highlighting that does not work.

**Comment by cldougl** [comment]
@dnieuw can you let us know what operating system you're running on and if possible share a screenshot of what you're seeing instead of the proper highlighting?

**Comment by dnieuw** [comment]
I am running Ubuntu linux 14.04 LTS and Google Chrome browser Version 70.0.3538.77 (Official Build) (64-bit).
My video card is a Dell Radeon HD 6350.

This is what I get:

![image](https://user-images.githubusercontent.com/11302970/47771513-dd1aad00-dce3-11e8-95d5-0b411a11f9ce.png)

So it is just the rendering of the colors that does not work.

**Comment by cldougl** [comment]
Hi @dnieuw - thus far we have not been able to reproduce this. Would you be able to see if you're still seeing the issue in our pure plotly.js implementation: https://codepen.io/plotly/pen/QpKOPr
If so, I would suggest transitioning this issue into the plotly.js repo: [https://github.com/plotly/plotly.js](https://github.com/plotly/plotly.js) as I don't think this is a problem directly related to the examples in the documentation.
