### ISSUE TITLE
"Uh oh" plots in subplots documentation on FireFox

### ISSUE THREAD

**Issue by jonmmease** [plotly/documentation#1155]
Several of the plots in the Python subplots documentation are not rendering for me on FireFox (Firefox 63.0 on MacOs): 

For example: https://plot.ly/python/subplots/#stacked-subplots
![screen shot 2018-10-26 at 7 03 59 pm](https://user-images.githubusercontent.com/15064365/47596126-2b315880-d952-11e8-81bf-08a54da43698.png)

Can anyone else reproduce?

**Comment by nicolaskruchten** [comment]
I cannot reproduce. If you have a fairly accurate timestamp we might be able to go back through the Cloud monitoring to figure out what's what. Seems like a transient Plotly Cloud issue, but those are the worst :(

**Comment by cldougl** [comment]
I cannot reproduce either -- all examples on that pg seem to be loading for me in chrome/firefox/safari/edge

**Comment by jonmmease** [comment]
I can no longer reproduce either. The time was Oct 26th around 7pm EST.  Feel free to investigate, but I'll close this for now.  Thanks for checking it out.
