### ISSUE TITLE
Hyperlink quotes in post descriptions break meta tags

### ISSUE THREAD

**Issue by StephenOrJames** [plotly/documentation#1177]
Post descriptions seem to be included directly in `meta` tags (for `og:description` and `twitter:description`). bf826c5 moved a hyperlink to the desctiption of the https://plot.ly/matplotlib/ - the double quotes are interfering with the `meta` tags' own quotes (screenshots below).

![image](https://user-images.githubusercontent.com/8732346/48696633-7258e500-ebb0-11e8-9503-cbf3bcf2a05d.png)
![image](https://user-images.githubusercontent.com/8732346/48697151-e47df980-ebb1-11e8-97ef-514b00088513.png)

**Comment by michaelbabyn** [comment]
closed by #1249
