### ISSUE TITLE
Preserve Edit in Chart Studio buttons

### ISSUE THREAD

**Issue by nicolaskruchten** [plotly/documentation#1197]
If/when we address https://github.com/plotly/plotly.js/issues/316, we should ensure that all CodePens and examples in our doc site still have the button to go to Chart Studio. This will likely involve going through every pen and pasting some JS code.

**Comment by michaelbabyn** [comment]
Updated code pens:
- [x] basic charts
- [ ] statistical
- [ ] scientific
- [ ] financial
- [ ] maps
- [ ] 3d
- [ ] multiple axis
- [ ] transforms
- [ ] custom ctls
- [ ] chart events
- [ ] animations
- [ ] style
- [ ] layout

**Comment by nicolaskruchten** [comment]
Oh wow I didn't realize we were doing this right away! I was hoping to have a conversation before we started about the benefits of adding a `config` entry to the `newPlot()` calls in the JS portion of the Pen vs sliding in a global call to `Plotly.setPlotConfig()` in the HTML portion of the Pen... ?
