### ISSUE TITLE
Document toImageButtonOptions

### ISSUE THREAD

**Issue by nicolaskruchten** [plotly/documentation#1198]
We should have some docs on this config option: https://github.com/plotly/plotly.js/blob/master/src/plot_api/plot_config.js#L153

Someone was asking about this in DCC: https://github.com/plotly/dash-core-components/issues/403 and in fact I added these options specifically for Dash, I just didn't finish the swing to document them, sorry.

**Comment by txhy2018** [comment]
have download as csv data?
