### ISSUE TITLE
Removal of sendToCloud button

### ISSUE THREAD

**Issue by nicolaskruchten** [plotly/documentation#1205]
We need to document how to turn it back on via `config`

**Comment by nicolaskruchten** [comment]
New in 1.43.0 https://github.com/plotly/plotly.js/pull/3307

**Comment by cldougl** [comment]
in addition to turning it back on in each plotly.js example (https://github.com/plotly/documentation/issues/1197) update the config doc: https://plot.ly/javascript/configuration-options/
