### ISSUE TITLE
Latex in 3D axes labels not working

### ISSUE THREAD

**Issue by alexandrebarb0sa** [plotly/documentation#1257]
Latex typesetting in 3D axes titles not working here in Plotly version 3.6.1, but it's fine in 2D plots.

**Comment by cldougl** [comment]
Hi there, thanks for reporting your issue. Unfortunately Latex in 3D charts is not currently a feature in plotly.js but you can follow the feature request issue: https://github.com/plotly/plotly.js/issues/608 for more information.
