### ISSUE TITLE
Latex Labels example is broken

### ISSUE THREAD

**Issue by Aypac** [plotly/documentation#1258]
There is an example of python syntax of labeling [here](https://plot.ly/python/LaTeX/). However, the latex is not rendered correctly:

![image](https://user-images.githubusercontent.com/10585956/52699295-b83a0500-2f75-11e9-9603-71b0bce14feb.png)

This relates to these file: https://github.com/plotly/documentation/tree/source-design-merge/_posts/python/style/latex

**Comment by priyatharsan** [comment]
the rendering issue is due to a bug in plotly.js: https://github.com/plotly/plotly.js/issues/559, https://github.com/plotly/plotly.js/issues/3290 and not the documentation.
