### ISSUE TITLE
Broken R table examples

### ISSUE THREAD

**Issue by tobinngo** [plotly/documentation#1272]
All of the R table examples featured are broken: https://plot.ly/r/table/

These errors were brought to my attention by users via Drift. Apparently, the code does work as intended in RStudio.

![image](https://user-images.githubusercontent.com/11036740/53760009-a91ce780-3e8f-11e9-9279-993cf98ec985.png)

![image](https://user-images.githubusercontent.com/11036740/53759879-53483f80-3e8f-11e9-812e-96c517e8ee3e.png)

**Comment by cldougl** [comment]
@tobinngo there's an error with the api: logged here https://github.com/plotly/documentation/issues/952

closing in favor of https://github.com/plotly/documentation/issues/952
