### ISSUE TITLE
Example link mistake in JavaScript docs

### ISSUE THREAD

**Issue by simonmysun** [plotly/documentation#1280]
Sorry that I failed to prepare the environment to debug. So I cannot submit a pull request.

## Problem description
In [this page](https://plot.ly/javascript/) there is a link to "2d Density Plots" but it is not linked in [this page](https://plot.ly/javascript/statistical-charts/) where it belongs.

Besides, the thumbnail image of "2D Histogram Contour" under [this page](https://plot.ly/javascript/statistical-charts/) is might be wrong.

**Comment by simonmysun** [comment]
I'm actually not sure the problem has been solved.

**Comment by michaelbabyn** [comment]
I just rebuilt the docs to include the change and it looks to be working now

**Comment by simonmysun** [comment]
Yes thanks. I have seen it working. I might need a better understanding of how Jekyll works. 

Besides, I think the content is not managed well: In [2d Density Plots in plotly.js](https://plot.ly/javascript/2d-density-plots/) there are examples named "2D Histogram Contour Plot with Histogram Subplots" and "2D Histogram Contour Plot with Slider Control". I think it makes people confused when they are not under [2D Histogram Contour in plotly.js](https://plot.ly/javascript/2d-histogram-contour/)

Only my own opinion. Not important at all.

**Comment by michaelbabyn** [comment]
I think you're right that it's confusing. Maybe we should consider changing the thumbnail for 2d histogram contour to something like this to make it more clear
![2d histogram contour](https://user-images.githubusercontent.com/41019918/54712406-90b0fc00-4b22-11e9-9db7-ea32e832c1d0.png)

**Comment by michaelbabyn** [comment]
Regarding Jekyll, we have two main branches in this repo. source-design-merge which is where we make edits and gh-pages which is where the main content on the site comes from ([more details](https://github.com/plotly/documentation#plotlys-github-pages-api-documentation-repository)). It wasn't until I updated the gh-pages repo that the changes were committed.

**Comment by simonmysun** [comment]
Right. I think you may also merge the two example page. 

Thank you for the explanation. I see what happened after your commit.
