### ISSUE TITLE
Missing ipython notebook

### ISSUE THREAD

**Issue by divyachandran-ds** [plotly/documentation#1288]
Convert python html docs to ipynb : 

- [ ] https://github.com/plotly/documentation/tree/source-design-merge/_posts/python/layout/labels
(https://plot.ly/python/figure-labels/)
- [ ] https://github.com/plotly/documentation/tree/source-design-merge/_posts/python/subplots/multiple-axes (https://plot.ly/python/fmultiple-axes/)

**Comment by michaelbabyn** [comment]
multiple-axis was done as part of #1282
