### ISSUE TITLE
plotly.offline.plot gives unexpected keyword exception for output_type='div'

### ISSUE THREAD

**Issue by manna018** [plotly/documentation#1290]
I am new in Plotly
When I use the code given below in Jupyter Notebook it works fine without any errors but when I use it in a flask app it throws an exception **plot() got an unexpected keyword argument 'output_type'**
I have no clue why is this happening . I get output in notebook but not in flask app I don't know why
```
data=go.Scattermapbox(lat=latlist,lon=longlist,mode='markers',marker=go.scattermapbox.Marker(size=9),text=placelist)      
layout = go.Layout(autosize=True,hovermode='closest',mapbox=go.layout.Mapbox(accesstoken=mapbox_access_token,bearing=0,center=go.layout.mapbox.Center(lat=28.5,lon=77.3),pitch=0,zoom=4))
fig = go.Figure(data=[data], layout=layout)
div=plot(fig,output_type='div')
return div
```

**Comment by manna018** [comment]
Just take look how I am importing it
```
from flask import Blueprint,render_template,request,flash,jsonify,json,make_response
import sqlite3 as sql
import pandas as pd
import geocoder 
import plotly.graph_objs as go
from plotly.offline import download_plotlyjs, init_notebook_mode, plot, iplot
```

**Comment by manna018** [comment]
When I use only data to plot map like 
`
div=plot(fig,output_type='div')
`
It works but nothing shows up

**Comment by manna018** [comment]
Seems like it misses the provided MapBox access token because it gives warning in javascript

**Comment by cldougl** [comment]
Hi @manna018  - thanks for checking out Plotly!
Please let us know here if you find an issue or bug in the documentation, otherwise we ask users to post use case questions in our community forum: https://community.plot.ly/
Finally, if you are working on a flask app you may be interested in checking out Dash: https://dash.plot.ly/

**Comment by manna018** [comment]
Issue solved 👍 
`div=plotly.offline.plot(fig,include_plotlyjs=False,output_type='div')`
