### ISSUE TITLE
Python Scatter Plot

### ISSUE THREAD

**Issue by tobinngo** [plotly/documentation#1304]
Would it be possible to change the color of the points of this scatter plot, so that they don't fall into common gender tropes? 

https://github.com/plotly/documentation/blob/source-design-merge/_posts/python/basic/dot/dot.ipynb

![image](https://user-images.githubusercontent.com/11036740/56311467-1755fa80-611c-11e9-8eab-cfe6fe85dafc.png)

**Comment by emmanuelle** [comment]
Thank you @tobinngo, would you like to open a pull request to improve this?
