### ISSUE TITLE
Falcon docs say to use sample credentials when they don't work 

### ISSUE THREAD

**Issue by matthewchan15** [plotly/documentation#1315]
Customers have been sending emails asking why the sample credentials in Falco do not work, when they're not supposed to work in the first place. This might explain why they think this.

https://help.plot.ly/database-connectors/personal-login/#step-7-setup-a-connection-to-your-databases

```If you don't have a database, or you want to test Falcon, you can make use of Plotly's read only sample datasets. Simply, toogle the Show / Hide Sample Credentials, which will reveal the required information for the appropriate databases, then copy, paste, and connect.```

**Comment by michaelbabyn** [comment]
moved to /plotly/plotly.github.io/issues/481
