### ISSUE TITLE
all dash examples should have a link to the code

### ISSUE THREAD

**Issue by cldougl** [plotly/documentation#1318]
The dash examples on the following pages do not have a link to the code. I would suggest putting a link to view the code in the dash example itself.

- [ ] https://plot.ly/python/basic-charts/
- [ ] https://plot.ly/python/statistical-charts/
- [ ] https://plot.ly/python/maps/
- [ ] https://plot.ly/python/3d-charts/

**Comment by michaelbabyn** [comment]
closed by #1327
