### ISSUE TITLE
Comparison with Vega and Vega-Lite still accurate?

### ISSUE THREAD

**Issue by domoritz** [plotly/documentation#1330]
In https://plot.ly/javascript/open-source-announcement/#distinction-from-vega-and-vegalite it says that "The vega and vega-lite schemas are more opinionated in prescribing how the chart data is grouped, sliced, or statistically processed before graphical display. This allows for complicated chart display with a concise JSON description, but leaves less control to the user. Neither approach is more “correct”—they’re just different."

I think the discussion only applies to Vega-Lite and not Vega. Vega is not very opinionated and gives developers great freedom to express bespoke visualizations. From the abstraction level, it is at the level of D3 and certainly more flexible than plotly. 

For the comparison with Vega-Lite, I think the key distinction is that Plotly is template based, while Vega-Lite is grammar based. Plotly enumerates chart types while Vega-Lite does not have a concept of chart types but instead, every chart is constructed by composing marks and encoding. Vega-Lite has developed a lot in recent years and I'm not sure I still agree that Vega-Lite offers less control to the user. It certainly isn't inherent in the approach so it feels out of place here in the comparison. 

Thoughts?

**Comment by nicolaskruchten** [comment]
That is indeed an old announcement (dated 2015!) and so likely out of date in many respects :)

Is it very important to you that this (now-historical) document be updated?

**Comment by domoritz** [comment]
I've just seen a paper citing this very page so I wanted to at least write down how I see the differences today. I agree it doesn't make sense to update a historical document but if you ever write a new comparison, feel free to take from my comments.

**Comment by nicolaskruchten** [comment]
Ok, thanks for sharing your thoughts! Published comparisons of tools never really age well :(

FWIW, from my perspective, Plotly.js doesn’t enumerate “chart types” per se but rather “trace types” which can be composed in various ways, so the “template” nomenclature doesn’t sit super well with me (even though the Vega/Vega-Life approach is certainly more open-ended/composable so I definitely understand what you’re trying to express!) Plotly trace types are almost as generic as “marks” although they’re coordinate-system-bound, so we don’t have just “point” or “bar” but rather scatter3d, scatterternary, scatterpolar, bar, barpolar etc. A different way of modelling things.

Congrats on the new release btw! The new Vega-life features are really nice :)

**Comment by domoritz** [comment]
Ahh, thanks for the clarification of trace types. I will make sure to talk about them instead of templates when when I talk about plotly. 

I have a dream that some day we can figure out what the expressivity of different approaches are (i.e. what space can it express) in a formal way.

**Comment by nicolaskruchten** [comment]
Cool! Admittedly our documentation is inconsistent about the use of "chart type" vs "trace type" but under the hood it's traces all the way down, and you can mix and match coordinate-compatible trace types on the same axes: scatter and line and waterfall and funnel and histogram if it makes you happy :)

Re expressivity: that sounds like an awesome dream, sign me up! Is there anyone working on a formal framework for this? Is there any comparable research outside of vis on what "expressivity" is? I'd love to help frame this up somehow, or even just sit on the sidelines and listen :)

**Comment by domoritz** [comment]
I'm not familiar with anything. @billhowe has expressed interest in this as well.
