### ISSUE TITLE
Chart Studio Theme, Template & Read-only sharing docs

### ISSUE THREAD

**Issue by nicolaskruchten** [plotly/documentation#1331]
We need a tutorial on help.plot.ly that outlines sharing workflows that include Themes, Templates and Read-Only sharing.

**Comment by cldougl** [comment]
closing in favor of https://github.com/plotly/plotly.github.io/issues/474 and https://github.com/plotly/plotly.github.io/issues/473 @Mahdis-z will follow up in those issues
