### ISSUE TITLE
Style-edit and proofread On-Prem customer-facing installation guide

### ISSUE THREAD

**Issue by vanastassiou** [plotly/documentation#1334]
As part of getting to know our product, I had a good look at the installation guide and noticed some inconsistencies that made it difficult for me to quickly understand what we were trying to get across. I corrected wording as well as I could to make the technical instructions clearer, but this document could benefit from a docs team member polishing it up.

The sorts of edits I have in mind (this is by no means an exhaustive list):
 - Reduce wordiness and redundancy
 - Add semantic section breaks where it makes sense, to result in a more usable table of contents
 - Where section breaks have been mistakenly used to describe a list of steps, convert to a numbered list
- Maintain consistent style for:
  - Section headings (phrasing and capitalization)
  - Code blocks
  - Product names
  - Indentation levels
- Any other changes that would increase clarity for a naive reader 

Here's the document I updated: https://docs.google.com/document/d/1HOa4YuEQO63qWDLR1iBdNKyNvUyKNai-574QNsbjufc/edit#

In case any edits I made are unclear, here's a backup of the doc I took before making changes: https://docs.google.com/document/d/1NdfQigYtfBUiYjnbGFLOdVBHSSgmkRAgRjoChi0Psfc/edit

**Comment by cldougl** [comment]
moved to https://github.com/plotly/streambed/issues/12991
