### ISSUE TITLE
Navbar changes

### ISSUE THREAD

**Issue by nicolaskruchten** [plotly/documentation#1355]
These changes should only take 20min but I've spent an hour trying to install gems and ruby etc locally :(

I'd like to make the following simple changes to the navbar to somewhat align it to the main plotly site navbar.

![image](https://user-images.githubusercontent.com/203523/59353271-974daa80-8cf0-11e9-96e9-312344d6138d.png)

**Comment by nicolaskruchten** [comment]
Here's the logo gif, it's white-on-transparent so it'll show weird here, sorry:

![graphing libraries logo-01](https://user-images.githubusercontent.com/203523/59353315-ad5b6b00-8cf0-11e9-8050-29a8bad9a9e3.png)

**Comment by nicolaskruchten** [comment]
These changes won't fully align everything to the main site but they'll help!

Also: the breadcrumb navbar 'affix' should be set much lower than 435 pixels... it should just affix to the top-level navbar always

**Comment by cldougl** [comment]
> These changes should only take 20min but I've spent an hour trying to install gems and ruby etc locally :(

@nicolaskruchten it would be good if you could make an issue w/ the problem that you had. That way we can modify the [contributing guide](https://github.com/plotly/documentation/blob/source-design-merge/Contributing.md#clone-the-repo-and-install-dependencies) as necessary 

> These changes won't fully align everything to the main site but they'll help!

For changes like this I think it would be good to get the marketing team's feedback/guidance on a plan to unify the style across the marketing and doc pages

**Comment by nicolaskruchten** [comment]
Yep, I spoke to Jane about these.

Re installing, just the usual runaround about rvm/brew/automake installation in High Sierra... doesn’t seem worth creating issues here about this level of stuff IMO
