### ISSUE TITLE
drop points on plotly in shiny 

### ISSUE THREAD

**Issue by student3841701** [plotly/documentation#1371]
hi~~~
-  I used scatter plot on plotly in shiny, but some points were dropped. 
- Also, if the character was "閱", the plot cannot display. But when the character is "閲". 
How can I fixed it?  Many Thanks!

output$plot <- renderPlotly ({
ssc() %>% 
plot_ly(x = ~mas, y = ~sds, symbol = ~factor(dd), size=6, type = 'scatter', symbols=c('circle','x'), 
color = ~factor(group), 
colors=c("#e01f54","#001852","#f5e8c8","#b8d2c7",
"#c6b38e","#a4d8c2","#f3d999","#d3758f","#dcc392",
"#2e4783","#82b6e9","#ff6347","#a092f1","#0a915d",
"#eaf889","#6699ff","#ff6666","#3cb371","#d5b158","#38b6b6") ,
hoverinfo = 'text',mode = 'markers',text = ~"閲卷委員編碼:", teacher, "平均數:", mas,"標準差:",sds),
hoverlabel = list(bgcolor = "#5d645a",bordercolor='white',font=list(family = "Microsoft JhengHei",size = 12,color = "white"))) %>%
config(displayModeBar = F) %>%
layout(xaxis =  list(showline = TRUE), yaxis =  list(showline = TRUE))})

![123456](https://user-images.githubusercontent.com/9252143/60072875-668a5e00-9751-11e9-90b7-ef58bfc8bbc3.png)

**Comment by cldougl** [comment]
Hi there,
We ask that users post usage questions in our community forum: [https://community.plot.ly/](https://community.plot.ly/) and reserve issues in this repository for documentation bug reports.
Thanks!
