### ISSUE TITLE
(3-D)Retrieving the range of axes of a zoomed-in 3-D Scatter plot (3-D)

### ISSUE THREAD

**Issue by AniWar** [plotly/documentation#1372]
How to get the dynamic range (x,y,z) when 3-D scatter plot is zoomed in ?
I’m trying to do a relayout , however I could not find any specific objects which could help me with required data.I also tried passing whole ‘t’ object instead of ‘t.camera’ , but no joy :(

I need to get the dynamic range in 3-D plot so that I can determine the data points when I zoom in.

**Comment by cldougl** [comment]
Hi there,
We ask that users post usage questions in our community forum: [https://community.plot.ly/](https://community.plot.ly/) and reserve issues in this repository for documentation bug reports.
Thanks!
