### ISSUE TITLE
missing data for cars-exploration.ipynb

### ISSUE THREAD

**Issue by sbowman-mitre** [plotly/documentation#1376]
The notebook cars-exploration.ipynb loads some data initially. I'm interested in re-using this notebook to explore the cross-linked interaction more fully. However, the data itself does not appear to be available in this git repo. Can it be made available?

**Comment by cldougl** [comment]
hey @sbowman-mitre - could you link to where you're seeing this notebook and we'll have a look?

**Comment by sbowman-mitre** [comment]
Right, sorry! Here it is: https://github.com/plotly/documentation/blob/source-design-merge/_posts/python/javascript-controls/figureWidgets/cars-exploration.ipynb

**Comment by michaelbabyn** [comment]
The data for those examples can be found in the [github repo](https://github.com/jonmmease/plotly_ipywidget_notebooks) linked at the bottom of the example. Maybe we should add some text at the top of the page that makes it more clear?

**Comment by cldougl** [comment]
> Maybe we should add some text at the top of the page that makes it more clear?

yep that would be good @michaelbabyn

**Comment by sbowman-mitre** [comment]
Okay, thanks. Yeah I definitely wouldn't have found it in a different git repo.
