### ISSUE TITLE
choropleth python examples not loading correctly

### ISSUE THREAD

**Issue by cldougl** [plotly/documentation#1378]
the first 2 examples on this page https://plot.ly/python/choropleth-maps/ are not getting drawn correctly.

**Comment by michaelbabyn** [comment]
Re-running the first example seemed to have fixed it and it looks like the second one is a plotly.js regression introduced in 1.48. See this [codepen with `layout.geo.showcoastlines: true` using plotly.js 1.47.0](https://codepen.io/michaelbabyn/pen/gNXzep) and the [same plot using version 1.48.0](https://codepen.io/michaelbabyn/pen/agVGQQ) of plotly.js.

**Comment by michaelbabyn** [comment]
closing in favor of plotly/plotly.js#3992
