### ISSUE TITLE
indicator trace type

### ISSUE THREAD

**Issue by nicolaskruchten** [plotly/documentation#1411]
@antoinerg please fill in some stuff here.

Five examples including: 

- [x] indicator_gauge
- [x] indicator_bullet
- [x] indicator_grid
- [x] indicator_datacard
- [x] indicator_scatter

**Comment by Mahdis-z** [comment]
https://github.com/plotly/plotly.js/pull/3978
https://github.com/plotly/plotly.js/pull/4007
https://github.com/plotly/plotly.js/pull/4014
https://github.com/plotly/plotly.js/pull/4029
https://github.com/plotly/plotly.js/pull/4037

**Comment by antoinerg** [comment]
Here's a little summary of what we discussed this morning.

Codepen using plotly.js v1.49.0 that animates the mocks currently on `master`: https://codepen.io/antoinerg/pen/bPQEPr?editors=0010

The purpose of `indicator` is to visualize a single value specified by the `value` attribute. Three distinct visual elements are available to represent that value: `number`, `delta` and `gauge`. Any combination of them can be specified via the `mode` attribute.

Top-level attributes:
- `value`: the value to visualize
- `mode`: what visual elements to draw
- `align`: how to align `number` and `delta` (left, center, right)
- `domain`: the extent of the figure

Then we can configure the 3 different visual elements via their respective container:
`number` is simply a representation of the number in text. It has attributes:
- `valueformat`: to format the number
- `prefix`: a string before the number
- `suffix`: a string after the number
- `font.(family|size)`: to control the font

`delta` simply displays the difference between the value with respect to a reference. It has attributes:
- `reference`: the number to compare the value with
- `relative`: whether that difference is absolute or relative
- `valueformat`: to format the delta
- `(increasing|decreasing).color`: color to be used for positive or decreasing delta
-  `(increasing|decreasing).symbol`: symbol displayed on the left of the delta
- `font.(family|size)`: to control the font
- `position`: position relative to `number` (either top, left, bottom, right)

Finally, we can have a simple title for the indicator via `title`:
- `text`: its string
- `align`: its alignment (left, center, right)
- `font`

**Comment by antoinerg** [comment]
Ok so now let me describe `gauge`. Let's look at one with `gauge.shape === 'angular'`:
![newplot - 2019-07-25T124635 153](https://user-images.githubusercontent.com/301546/61892684-5396b500-aeda-11e9-8d7b-b02b1be137f9.png)

It has a few elements: a bar to display the current value (in green), it has a `threshold` to indicate a target value (in red) as well as `steps` to identify ranges of interest (one in yellow and one in blue).

```js
Plotly.newPlot(gd,[{
    "value": 450,
    "title": {"text": "Speed"},
    "type": "indicator",
    "mode": "gauge+number",
    "delta": {"reference": 400},
    "gauge": {
      "axis": {
        "range": [0, 500],
        "tickwidth": 1,
        "tickcolor": "white"
      },
      "bgcolor": "rgba(255, 255, 255, 0.25)",
      "borderwidth": 2,
      "bordercolor": "rgba(255, 255, 255, 0.5)",
      "steps": [{
        "range": [0, 250],
        "color": "rgba(255, 255, 0, 0.5)"
      }, {
        "range": [250, 400],
        "color": "rgba(0, 0, 255, 0.75)"
      }],
      "threshold": {
        "line": {
          "color": "rgba(255, 0, 0, 1)",
          "width": 4
        },
        "thickness": 0.75,
        "value": 490
      }
    }
  }], {'width': 800, 'paper_bgcolor': 'black', font: {color: 'white'}})
```

**Comment by antoinerg** [comment]
Another interesting feature of that `indicator` trace is that it sits above the other traces (even the 3d ones). This way, it can easily be used as an overlay as demonstrated in following two mocks:

### `indicator_scatter`
![indicator_scatter](https://user-images.githubusercontent.com/301546/61893299-c0f71580-aedb-11e9-8f0a-212a5cbd2bb6.png)

### `gl3d_indicator_scatter3d`
![gl3d_indicator_scatter3d](https://user-images.githubusercontent.com/301546/61893327-d2d8b880-aedb-11e9-997e-4fa2e7bac503.png)

**Comment by nicolaskruchten** [comment]
* New JS page: https://plot.ly/javascript/indicator/
   * some explanatory text: the various modes (gauge, number, delta) and the two gauge types (angular and bullet)
       * complex **example**: subplots with each thing based on indicator_grid_template
   * examples of each:
      * link to the gauge page and the bullet page
      * **big number** example
      * **indicator_datacard**
      * **indicator_scatter** (not 3d!!)
* Existing JS Gauge page: https://plot.ly/javascript/gauge-charts/ needs upgrading
   * simple **example**: gauge+number, no steps, no threshold, no delta
   * complex **example**: gauge+number+delta, steps, threshold
* New JS page: https://plot.ly/javascript/bullet-charts/
   * simple **example**: single bullet, no number, no delta
   * complex **example**: multiple bullets, plus number, plus delta
