### ISSUE TITLE
1.49 Mapbox features

### ISSUE THREAD

**Issue by nicolaskruchten** [plotly/documentation#1412]
@etpinard fill in some links to mocks, codepens please

**Comment by etpinard** [comment]
### `choroplethmapbox`

- Simple mock: https://rreusser.github.io/plotly-mock-viewer/#mapbox_choropleth0
- Mock with `geojson` set as `{/* geojson object /*}`: https://rreusser.github.io/plotly-mock-viewer/#mapbox_choropleth-raw-geojson
- Mock with multiple `choroplethmapbox` traces: https://rreusser.github.io/plotly-mock-viewer/#mapbox_choropleth-multiple

### `densitymapbox`

- Simple mock: https://rreusser.github.io/plotly-mock-viewer/#mapbox_density0
- Multiple `densitymapbox` traces: https://rreusser.github.io/plotly-mock-viewer/#mapbox_density-mulitple
- `densitymapbox` with "real" data: https://rreusser.github.io/plotly-mock-viewer/#mapbox_earthquake-density (essentially a remake of https://docs.mapbox.com/mapbox-gl-js/example/heatmap-layer/)

### New `mapbox.style` values

- `open-street-map`: https://rreusser.github.io/plotly-mock-viewer/#mapbox_osm-style
- `staman-*` styles: https://rreusser.github.io/plotly-mock-viewer/#mapbox_stamen-style
- `carto-*` styles: https://rreusser.github.io/plotly-mock-viewer/#mapbox_carto-style

**Comment by nicolaskruchten** [comment]
New JS pages, say 2 examples each (simple and complicated): lines on a mapbox, filled areas on a mapbox, density on a mapbox, choropleth on a mapbox

New JS page: mapbox overview...
   * explanation of layers (style, data, layers), explanation of relationship to Mapbox.js vs Mapbox tile service
   * clear explanation of when a mapbox token is and is not required, and how to set it (either in the mapbox layout object or via configuration)
   * explanation of attribution
   * example of various styles (non-mapbox, mapbox)
   * links to the 5 data pages (scatter, line, area, choropleth, density)
   * examples of layers (environment Canada layer) based on https://codepen.io/nicolaskruchten/pen/BgbxQG?editors=0010

**Comment by Mahdis-z** [comment]
- density mapbox https://github.com/plotly/plotly.js/pull/3993
- coropleth mapbox: https://github.com/plotly/plotly.js/pull/3988
- new mapbox style values https://github.com/plotly/plotly.js/pull/4068 , https://github.com/plotly/plotly.js/pull/3987
- support for source type and for mapbox layout layer https://github.com/plotly/plotly.js/pull/4006
- added attributes https://github.com/plotly/plotly.js/pull/4058, https://github.com/plotly/plotly.js/pull/4069

**Comment by etpinard** [comment]
Here's the codepen listing all the layers for all the `layout.mapbox.style` values:

https://codepen.io/etpinard/pen/ydVMwM , open the console and wait ~30 seconds.

Let me know if you have any questions.

**Comment by chriddyp** [comment]
For choropleth examples, we'll need examples that include GeoJSON files rather than URLs for the folks in the community that don't have public internet access or are building apps that can't depend on 3rd party services/urls.

**Comment by etpinard** [comment]
> we'll need examples that include GeoJSON files rather than URLs for the folks in the community that don't have public internet access or are building apps that can't depend on 3rd party services/urls.

example: https://rreusser.github.io/plotly-mock-viewer/#mapbox_choropleth-raw-geojson
