### ISSUE TITLE
Plotly does not work with webshot

### ISSUE THREAD

**Issue by kmalone7** [plotly/documentation#1414]
There is an issue with plotly and using webshot to save images of the figures. I first posted this with webshot, but no progress has been made. Hoping that posting here will yield some results. To see the details of this issue see: https://github.com/wch/webshot/issues/73

**Comment by nicolaskruchten** [comment]
Hmmm I'm not sure that this is the right repository to report this issue, as it's not related to our documentation. I would recommend reporting it in the plotly.r repo over at https://github.com/ropensci/plotly

**Comment by kmalone7** [comment]
Ok, I will close it here an post there. Thanks for a quick response.
