### ISSUE TITLE
Wind Rose Example Not Working

### ISSUE THREAD

**Issue by GeoffCapper** [plotly/documentation#1460]
Hi,

The wind rose chart example for javascript is a bit faulty, seems to be using a combination of old and new layout and is missing a few bits. (https://plot.ly/javascript/wind-rose-charts/) Copypasting the example won't reproduce the chart in the pen, and the code in the pen itself is using the old "area" chart type.

I can get a fairly close representation of the chart as seen in the pen by making the following changes to the JS shown in the page, adding the "polar" node to contain the axis layout parameters, and adding the barmode parameter.

```javascript
var layout = {
  title: 'Wind Speed Distribution in Laurel, NE',
  font: {size: 16},
  legend: {font: {size: 16}},
  polar: {
    barmode: 'overlay',
    radialaxis: {
      tickmode: 'auto',
      nticks: 5,
      tickangle: 45,
      angle: 45,
      ticksuffix: '%',
    },
    angularaxis: {
      direction: "clockwise"
    }
  }
}
```
Cheers, & thanks for a great library!

**Comment by jdamiba** [comment]
This issue has been addressed.
