### ISSUE TITLE
Check on Algolia index

### ISSUE THREAD

**Issue by nicolaskruchten** [plotly/documentation#1461]
it seems like newer stuff like "indicator" and older stuff like "barmode" aren't showing up in searches on the reference pages. @michaelbabyn is this a straightforward thing to deal with or does it need some investigation?

**Comment by michaelbabyn** [comment]
I think it's just a matter of running `make update_ref_search` after the plot schema gets updated. So, pretty straightforward

I think the makefile needs to be changed not to install the newest version of algoliasearch though because it's failing for me at the moment.
