### ISSUE TITLE
broken link in js mapbox density heatmap doc

### ISSUE THREAD

**Issue by cldougl** [plotly/documentation#1495]
Mapbox Map Layers link is 404ing from https://plot.ly/javascript/mapbox-density-heatmaps/

<img width="897" alt="Screen Shot 2019-09-05 at 1 58 44 PM" src="https://user-images.githubusercontent.com/2789078/64367063-78a43a80-cfe5-11e9-98be-01a399bfb65a.png">

**Comment by cldougl** [comment]
Same with the vectors tile link on https://plot.ly/javascript/mapbox-county-choropleth/

<img width="1088" alt="Screen Shot 2019-09-05 at 2 02 13 PM" src="https://user-images.githubusercontent.com/2789078/64367436-f700dc80-cfe5-11e9-89c6-16600a2b36b3.png">

 Looks like the link is only existing for python atm
https://plot.ly/python/mapbox-layers/

**Comment by nicolaskruchten** [comment]
Thanks! Yeah there was a delay in merging the mapbox-layers in JS-land. should arrive soon.

**Comment by jdamiba** [comment]
This issue has been addressed.
