### ISSUE TITLE
crosslinking documentation pages

### ISSUE THREAD

**Issue by chriddyp** [plotly/documentation#1496]
- In the pie  (and barpolar?) chart page, provide a simple example and link to the sunburst docs ("you may be looking for sunburst charts"). This would help with questions like these: https://community.plot.ly/t/superimposing-2-pie-charts-on-top-of-each-other/28299/3
- In the histogram page, provide an example using stacked bars with `px.bar` & hover data ("if you want to display information about the individual items within each histogram bar, then create a stacked bar chart with hover information. note that this is not technically the histogram chart type, but it will have a similar effect")
- in parcats, link to parcoords & vice versa?

**Comment by chriddyp** [comment]
the first two i think are most important. i've run into the sunburst question several times now from community members and workshops. I've run into the second one personally many times over the years.

**Comment by emmanuelle** [comment]
See https://github.com/plotly/plotly.py-docs/pull/195
