### ISSUE TITLE
Broken 3d animations example

### ISSUE THREAD

**Issue by jackparmer** [plotly/documentation#1500]
https://plot.ly/python/v3/visualizing-mri-volume-slices/

The slider / play button doesn't seem to do anything anymore:
![image](https://user-images.githubusercontent.com/1865834/64646212-9b1ec500-d3e4-11e9-97fd-d7477739270a.png)

**Comment by nicolaskruchten** [comment]
Oh yes, let's definitely upgrade this notebook to be offline-only and actually work :)

**Comment by nicolaskruchten** [comment]
The new upgraded page is now at https://plot.ly/python/visualizing-mri-volume-slices/ (note the lack of `/v3` in the URL) so we'll need to wait for Google to reindex it, and the old `/v3` page now automatically has this in the header to help things along:

![image](https://user-images.githubusercontent.com/203523/64731448-3d0ae400-d4af-11e9-89f7-26f92fb2c396.png)
