### ISSUE TITLE
Ability to launch Plotly.py v4 notebooks on Binder

### ISSUE THREAD

**Issue by nicolaskruchten** [plotly/documentation#1501]
The CI for https://github.com/plotly/plotly.py-docs current builds HTML pages for this doc system, and along the way makes IPYNB files. If those files were stored somewhere, each doc page could have a Binder link to the corresponding notebook.

**Comment by nicolaskruchten** [comment]
cc @jonmmease I know you're waiting for this :)

**Comment by jdamiba** [comment]
This issue has been addressed.
