### ISSUE TITLE
broken example on python mapbox choropleth maps

### ISSUE THREAD

**Issue by cldougl** [plotly/documentation#1504]
https://plot.ly/python/mapbox-county-choropleth/#mapbox-light-base-map-free-token-needed

<img width="1246" alt="Screen Shot 2019-09-16 at 4 57 24 PM" src="https://user-images.githubusercontent.com/2789078/65002573-58a82d00-d8a9-11e9-94bc-20c096ee6fdf.png">

**Comment by nicolaskruchten** [comment]
fixed :)
