### ISSUE TITLE
doesn't run on plotly 4.0

### ISSUE THREAD

**Issue by notuntoward** [plotly/documentation#1508]
This is quite out of date.  It would be good to either hide it or update it so it runs on plotly 4.0

**Comment by nicolaskruchten** [comment]
Which page are you referring to?

**Comment by notuntoward** [comment]
Whoops, for some reason, I thought the PR would be attached to the page I was looking at.  I can't find that page now, so I'll just close this and reopen it if I rediscover the problem.
