### ISSUE TITLE
/numpy/* and /scikit-learn/* should redirect to /python/

### ISSUE THREAD

**Issue by nicolaskruchten** [plotly/documentation#1529]
Let's do this at the streambed Nginx level, and once done we can eliminate all of the files from this repo.

**Comment by jdamiba** [comment]
[x] - redirect URLs at streambed level - accomplished by https://github.com/plotly/streambed/issues/13570
[ ] - delete files from repo - will be accomplished once https://github.com/plotly/documentation/pull/1537 is merged
