### ISSUE TITLE
CI tests

### ISSUE THREAD

**Issue by nicolaskruchten** [plotly/documentation#1555]
We need a script that runs on branches and s-d-m that checks for various things in the frontmatter and errors out if some invariants aren't met:

* example_index vs order?
* typo'ed display_as or other enumerated fields
* duplicate permalinks?

A variant of this script should also run in the py-docs repo so that we can catch these errors early

**Comment by jdamiba** [comment]
Ideas for things CI can enforce:

- [ ] every post must have a unique name (title would be auto-generated from name)
- [ ] every post must have a unique description
- [ ] every post must have a unique permalink
- [ ] every permalink can only be referred to from one `redirect_from`
- [ ] consistent ordering within language 
- [ ] maximum of 4 `example-index` posts

**Comment by nicolaskruchten** [comment]
So some of these will need to be tempered a bit like "within a given `language`"... because we will reuse titles etc.

We might also want some checks like "posts with matching permalinks in different languages have the same display_as".

Also: "the permalink and language match" ?

Also: "the example-index posts are always first in the ordering"

**Comment by jdamiba** [comment]
This issue has been addressed.
