### ISSUE TITLE
Need to remove reliance on api_create when generating docs with RMarkdown

### ISSUE THREAD

**Issue by rpkyle** [plotly/documentation#1557]
Currently, generating R documentation in this repository requires a call to `api_create`, e.g.

```
library(plotly)

p <- plot_ly(data = iris, x = ~Sepal.Length, y = ~Petal.Length)

# Create a shareable link to your chart
# Set up API credentials: https://plot.ly/r/getting-started
chart_link = api_create(p, filename="scatter-basic")
chart_link
```

We should modify the documentation generation such that the `api_create` call is no longer necessary. This will likely require the following:
- [x] enumerating the minimal and sufficient set of package dependencies required for all examples
- [x] editing 112 `plot_ly`-related scripts, as well as 42 `ggplot2`-related scripts
- [x] debugging any RMarkdown issues which arise, so that the process is error-free
- [ ] opening a PR in this repository to use a Pandoc template with RMarkdown without `api_create`, by editing the necessary bits of `_posts/r` and `_posts/ggplot2`

The end goal is to migrate this procedure to CircleCI, such that the process is automated. @nicolaskruchten

**Comment by nicolaskruchten** [comment]
Exciting!

Yes for the example above, in an ideal world it would look like

```R
library(plotly)
plot_ly(data = iris, x = ~Sepal.Length, y = ~Petal.Length)
```
or


```R
library(plotly)
p <- plot_ly(data = iris, x = ~Sepal.Length, y = ~Petal.Length)
p
```

whichever is more idiomatic

**Comment by nicolaskruchten** [comment]
Please note that in general, each code block should be independently runnable, so there is likely going to be a lot of duplication like `library(plotly)` loaded up again and again... this is normal :)

**Comment by nicolaskruchten** [comment]
Hi @CanerIrfanoglu ! Any update on this issue? :)

**Comment by CanerIrfanoglu** [comment]
Hi @nicolaskruchten 🙋🏻‍♂️

I created the example `.Rmd` file below. Then ran `Rscript -e 'rmarkdown::render("test.Rmd")'` to create a `.md` file from it. I would appreciate getting your or @rpkyle's feedback/validation before applying the same method to the remaning examples to avoid possible multiple iterations on all the examples. Thanks :) 
```
---
title: Group By in R | Examples | Plotly
name: Group By
permalink: r/group-by/
description: How to use groupby transforms in R with Plotly.
layout: base
thumbnail: thumbnail/groupby.jpg
language: r
has_thumbnail: true
display_as: transforms
page_type: example_index
order: 2
output:
  html_document: 
    keep_md: yes
---

```{r, echo = FALSE, message=FALSE}
knitr::opts_chunk$set(
  message = FALSE,
  warning = FALSE,
  fig.width = 8.33, # ~800px
  fig.height = 6.25 # 600px
)
```


```{r}
library(plotly)
packageVersion('plotly')
```

#### Basic Example

```{r}
library(plotly)

p <- plot_ly(x=1:4, y=runif(4))
p

```

**Comment by nicolaskruchten** [comment]
So in principle this is right but I think we'd want to target HTML as an output format rather than Markdown. What file did you base this one on? It looks fairly different from https://plot.ly/r/group-by/

**Comment by CanerIrfanoglu** [comment]
I changed the content of the group-by example just for testing purposes. I am able to remove the `api_create` and generate the figures on individual examples. Running into a problem when trying to integrate them when serving the docs locally though. As soon as that is figured, I can start editing all the examples.

**Comment by CanerIrfanoglu** [comment]
I finished making requested changes towards removing the reliance of `api_create` at  https://github.com/plotly/documentation/pull/1581. Please let me know for any possible modifications required. Thanks :)

**Comment by jdamiba** [comment]
This issue has been addressed.
