### ISSUE TITLE
3D Line Opacity

### ISSUE THREAD

**Issue by aneda** [plotly/documentation#157]
Opacity for 3D line does not work.  i have tried it with Opacity bar and with 'rgba'.  Here is a link: https://plot.ly/5437/~neda/#

![image](https://cloud.githubusercontent.com/assets/5222384/8525577/aec5b7d6-23cf-11e5-924f-39777d2fcaa6.png)

![screen shot 2015-07-06 at 11 17 58 am](https://cloud.githubusercontent.com/assets/5222384/8525584/c4858934-23cf-11e5-985e-acfcfeaff9d9.png)

@etpinard @bpostlethwaite

**Comment by bpostlethwaite** [comment]
cc/ @mikolalysenko
