### ISSUE TITLE
order checks

### ISSUE THREAD

**Issue by nicolaskruchten** [plotly/documentation#1576]
For each language, for each display_as (maybe hardcode the 3 main languages and the 8 main display_as categories):
* no more than 4 "example_index"
* those 4 should have the lower order
* the order should be sequential integers from 1, no duplicates
* all of them should have thumbnails

Note: please provide a little script that can be run which corrects the order :)

**Comment by nicolaskruchten** [comment]
One thing we could consider is to get rid of the `example_index` thing altogether... basically just say that the 4 pages with the lowest order are the ones that get onto the main page and that's that.

If we did that, could we get rid of `page_type` altogether also? Other than `example_index` vs not, what else does that field do?

**Comment by jdamiba** [comment]
This issue has been addressed.
