### ISSUE TITLE
permalink/redirect checks

### ISSUE THREAD

**Issue by nicolaskruchten** [plotly/documentation#1577]
If you make a list of all the permalinks and redirect_froms (in one list!) there should be no duplicates

**Comment by jdamiba** [comment]
@nicolaskruchten Here is a list of posts that contain duplicate permalinks or redirect_froms. 

| Post        | Post           | 
| ------------- |:-------------:| 
| https://github.com/plotly/documentation/blob/source-design-merge/_posts/plotly_js/maps/choropleth-mapbox/2019-08-16-choropleth_plotly_js_index.html      | https://github.com/plotly/documentation/blob/source-design-merge/_posts/plotly_js/maps/mapbox-layers/2019-08-20-mapbox-layers_plotly_js_index.html      |   
| https://github.com/plotly/documentation/blob/source-design-merge/_posts/plotly_js/basic/bar/2015-04-09-bar_plotly_js_index.html      | https://github.com/plotly/documentation/blob/source-design-merge/_posts/plotly_js/financial/waterfall/2015-04-09-bar_plotly_js_index.html      |   
| https://github.com/plotly/documentation/blob/source-design-merge/_posts/plotly_js/style/colorscales/2015-04-09-colorscales_plotlyjs_index.html      | https://github.com/plotly/documentation/blob/source-design-merge/_posts/plotly_js/style/colorscales/2017-08-21-colorscales_new_plotlyjs_index.html      |   
| https://github.com/plotly/documentation/blob/source-design-merge/_posts/plotly_js/basic/treemap/2019-10-15-treemap_plotly_js_index.html      | https://github.com/plotly/documentation/blob/source-design-merge/_posts/plotly_js/statistical/treemaps/2015-11-30-treemaps_plotly_js_index.html      |   
| https://github.com/plotly/documentation/blob/source-design-merge/_posts/python-v3/3d/3d-surface/3d-surface_python_index-old.html      | https://github.com/plotly/documentation/blob/source-design-merge/_posts/python-v3/3d/3d-surface/2015-06-30-3d-surface.html      |   
| https://github.com/plotly/documentation/blob/source-design-merge/_posts/python-v3/basic/bubble/2015-06-30-bubble.html      | https://github.com/plotly/documentation/blob/source-design-merge/_posts/python-v3/redirects/2018-04-18-bubble-charts-tutorial.html      |   
| https://github.com/plotly/documentation/blob/source-design-merge/_posts/python-v3/basic/funnel/2019-06-25-funnel-chart.html      | https://github.com/plotly/documentation/blob/source-design-merge/_posts/python-v3/financial/funnel-chart/2015-06-30-funnel-chart.html      |   
| https://github.com/plotly/documentation/blob/source-design-merge/_posts/python-v3/fundamentals/user_guide_python/old_user_guide/redirect_from/2015-05-27-streaming-line-tutorial.html      | https://github.com/plotly/documentation/blob/source-design-merge/_posts/python-v3/streaming/2015-06-30-streaming-line-tutorial.html      |   
| https://github.com/plotly/documentation/blob/source-design-merge/_posts/python-v3/fundamentals/user_guide_python/old_user_guide/redirect_from/2015-05-27-bar-charts-tutorial.html      | https://github.com/plotly/documentation/blob/source-design-merge/_posts/python-v3/redirects/2018-09-27-bar-charts-tutorial.html      |   
| https://github.com/plotly/documentation/blob/source-design-merge/_posts/python-v3/redirects/2018-04-18-bubble-charts-tutorial.html      | https://github.com/plotly/documentation/blob/source-design-merge/_posts/python-v3/fundamentals/user_guide_python/old_user_guide/redirect_from/2015-05-27-bubble-charts-tutorial.html      |   
| https://github.com/plotly/documentation/blob/source-design-merge/_posts/python-v3/fundamentals/user_guide_python/old_user_guide/redirect_from/2015-05-27-heatmaps-contours-and-2dhistograms-tutorial.html      | https://github.com/plotly/documentation/blob/source-design-merge/_posts/python-v3/redirects/2018-04-18-heatmaps-and-2dhist.html      |   
| https://github.com/plotly/documentation/blob/source-design-merge/_posts/python/chart-studio/2019-07-03-proxy-configuration.html      | https://github.com/plotly/documentation/blob/source-design-merge/_posts/python/chart-studio/proxy-configuration.md      |   
| https://github.com/plotly/documentation/blob/source-design-merge/_posts/python/chart-studio/get-requests.md      | https://github.com/plotly/documentation/blob/source-design-merge/_posts/python/chart-studio/2019-07-03-get-requests.html      |   
| https://github.com/plotly/documentation/blob/source-design-merge/_posts/python/chart-studio/2019-07-03-ipython-notebook-tutorial.html      | https://github.com/plotly/documentation/blob/source-design-merge/_posts/python/chart-studio/ipython-notebook-tutorial.md      |   
| https://github.com/plotly/documentation/blob/source-design-merge/_posts/python/chart-studio/presentations-tool.md      | https://github.com/plotly/documentation/blob/source-design-merge/_posts/python/chart-studio/2019-07-03-presentations-tool.html      |  
| https://github.com/plotly/documentation/blob/source-design-merge/_posts/python/chart-studio/2019-07-03-privacy.html      | https://github.com/plotly/documentation/blob/source-design-merge/_posts/python/chart-studio/privacy.md      |  
| https://github.com/plotly/documentation/blob/source-design-merge/_posts/python/chart-studio/proxy-configuration.md     | https://github.com/plotly/documentation/blob/source-design-merge/_posts/python/chart-studio/2019-07-03-proxy-configuration.html     |  
| https://github.com/plotly/documentation/blob/source-design-merge/_posts/python/chart-studio/getting-started-with-chart-studio.md     | https://github.com/plotly/documentation/blob/source-design-merge/_posts/python/chart-studio/2019-07-03-getting-started-with-chart-studio.html      |  
| https://github.com/plotly/documentation/blob/source-design-merge/_posts/python/chart-studio/2019-07-03-embedding-charts.html     | https://github.com/plotly/documentation/blob/source-design-merge/_posts/python/chart-studio/embedding-charts.md      |  
| https://github.com/plotly/documentation/blob/source-design-merge/_posts/python/chart-studio/data-api.md     | https://github.com/plotly/documentation/blob/source-design-merge/_posts/python/chart-studio/2019-07-03-data-api.html      |  
| https://github.com/plotly/documentation/blob/source-design-merge/_posts/python/chart-studio/delete-plots.md     | https://github.com/plotly/documentation/blob/source-design-merge/_posts/python/chart-studio/2019-07-03-delete-plots.html     |  
| https://github.com/plotly/documentation/blob/source-design-merge/_posts/r/shiny/2015-07-30-shiny.md     | https://github.com/plotly/documentation/blob/source-design-merge/_posts/r/shiny/coupled-events/click-selection/2016-02-24-shiny-coupled-events.md      |  
| https://github.com/plotly/documentation/blob/source-design-merge/_posts/r/basic/2015-12-31-semicircle-gauge-chart.md     | https://github.com/plotly/documentation/blob/source-design-merge/_posts/r/financial/2019-09-26-gauge-charts.md     |  
| https://github.com/plotly/documentation/blob/source-design-merge/_posts/r/style/2015-07-30-font.md     | https://github.com/plotly/documentation/blob/source-design-merge/_posts/r/style/2017-01-20-font-styles.md      |

**Comment by nicolaskruchten** [comment]
Cool! What would really help actually is to know which one is the one being served in prod right now, somehow.

Note also that in the case of the `/python/chart-studio/` pairs, the relationship between the `.md` file and the `.html` file is the same as the `.Rmd`/`.md` relationship in `/r/`, meaning these can be ignored. In general for this check in this repo you do *not* need to look at frontmatter inside `jupyter`

**Comment by nicolaskruchten** [comment]
See also #1580

**Comment by nicolaskruchten** [comment]
Expanding upon #1580, anything in `excludes` should probably either be removed from the repo or ignored by the ci checks. I'm looking specifically at `_posts/user_guide_python/old_user_guide/redirect_from` ... doesn't seem like it's doing anything today? let's look at nuking it from both `source-design-merge` and whatever files it had generated in `gh-pages` ?

**Comment by nicolaskruchten** [comment]
You know, the easiest thing to do here is to just delete whichever file is *not* being used in prod :)
