### ISSUE TITLE
front-matter-ci shouldn't look under `jupyter`

### ISSUE THREAD

**Issue by nicolaskruchten** [plotly/documentation#1580]
We discussed this in Slack https://plotly.slack.com/archives/DC96RUGSV/p1572392795005800 but upon further reflection, I think we can safely skip the files under `python/chart-studio` which have their front-matter stored in `jupyter`. These files are ignored by Jekyll I believe.

Actually, we should *confirm* that `_posts/python/chart-studio/*md` are ignored by Jekyll by adding them to the `excludes` in `_config.yml` just like the `*Rmd` files :)

**Comment by jdamiba** [comment]
closed by https://github.com/plotly/documentation/commit/7a0680509f5f3d48ef80cbe96ce77b63dbca5391#diff-fc3edd654e550950075d7f68b9d88abe
