### ISSUE TITLE
inline Javascript examples (no more embedded CodePens)

### ISSUE THREAD

**Issue by nicolaskruchten** [plotly/documentation#1587]
JS examples should be rendering plots "in line" in the page so that they always match the displayed code, rather than embedding an external CodePen which easily gets out of date.

**Comment by jdamiba** [comment]
This will require refactoring lines 24-35 of `auto_examples.html` to inline a `script` tag rather than an `iframe` with codepen embed. 

This shouldn't be an issue as the `plotly.js` library is present in the browser environment.

**Comment by jdamiba** [comment]
This issue has been addressed.
