### ISSUE TITLE
Repo shuffling proposal

### ISSUE THREAD

**Issue by nicolaskruchten** [plotly/documentation#1596]
I have a few concerns about this repository:
1. the name is a bit too broad, in the presence of other doc repos like `dash-docs` and `plotly.py-docs` and `plotly.github.io`
2. the main branch is `source-design-merge` instead of `master`
3. it's really big due to its history

Here's something we could do:
1. create a new repo `graphing-library-docs` and copy all of `source-design-merge` into `master` there
2. have that repo CI still deploy to `documentation/gh-pages` (thereby requiring no nginx changes, and keeping the new repo slim)
3. clear out the contents of the main branch here, replacing it with a single readme that says "we have many docs, here are links to them, feel free to file an issue here or in any of those other repos!"

thoughts @Mahdis-z @jdamiba @emmanuelle @cldougl @chriddyp ?

**Comment by nicolaskruchten** [comment]
(note that this does not preclude the previously-discussed idea of moving the contents of `plotly.py-docs` into the `plotly.py` repo in the near term)

**Comment by Mahdis-z** [comment]
Yeah, its giant, and this way it would be more straight forward for the contributors. Maybe `api-docs`?

**Comment by jdamiba** [comment]
I think that this should be quite safe if we modify the CircleCI `config.yml` to deploy to the `gh-pages` branch of the `documentation` repo. 

My only question is if we will continue to append changes to the `gh-pages` branch in `documentation`? This seems like it would be a good opportunity to get rid of gremlins by having the `gh-pages` branch in `documentation` be the output of the build in the `graphing-library-docs` repo.

**Comment by emmanuelle** [comment]
sounds good to me

**Comment by cldougl** [comment]
no concerns come to mind from me

**Comment by nicolaskruchten** [comment]
@jdamiba can you propose a plan here as a bulleted list of what we'd need to do to accomplish this? Or create a Google Doc and link to it here or whatever? :)

**Comment by jdamiba** [comment]
The workplan for this is as follows:

- [ ] create `plotly/graphing-libraries-docs` repo
- [ ] merge all open PRs in `documentation:source-design-merge`
- [ ] clone contents of `documentation:source-design-merge` to `graphing-libraries-docs:master`
- [ ] update `graphing-libraries-docs:master/.circleci/config.yml` to deploy to `documentation:gh-pages` after successfully building the site
- [ ] clear out every branch on `plotly/documentation` except for `documentation:gh-pages`
- [ ] update Readme.md on `graphing-libraries-docs` and `documentation:gh-pages` to reflect new workflow

**Comment by jdamiba** [comment]
This issue has been resolved with the setup of https://github.com/plotly/graphing-library-docs.
