### ISSUE TITLE
Replace `iris` with `df`

### ISSUE THREAD

**Issue by chriddyp** [plotly/documentation#1627]
This comes up in all of the workshops that I do - folks don't understand what "iris" is but they do understand the universal "df" variable name.

It would be helpful if we rewrote examples like this:
```python
import plotly.express as px
iris = px.data.iris()
fig = px.scatter(iris, x="sepal_width", y="sepal_length")
fig.show()
```

to be
```python
import plotly.express as px
df = px.data.iris()
fig = px.scatter(df, x="sepal_width", y="sepal_length")
fig.show()
```

cc @emmanuelle @nicolaskruchten @Mahdis-z

**Comment by nicolaskruchten** [comment]
Done and deployed.
