### ISSUE TITLE
redirect /python/annotated_heatmap/ to /python/annotated-heatmap/

### ISSUE THREAD

**Issue by chriddyp** [plotly/documentation#1629]
Words separated by underscores are roughly treated line one word whereas words separated by hyphens are treated as two words

https://support.google.com/webmasters/answer/76329?hl=en

> Consider using punctuation in your URLs. The URL http://www.example.com/green-dress.html is much more useful to us than http://www.example.com/greendress.html. We recommend that you use hyphens (-) instead of underscores (_) in your URLs.

**Comment by nicolaskruchten** [comment]
Done in https://github.com/plotly/plotly.py/commit/8d4163d58a8e6d3571519efe84c91e312e9a6e23 and deployed.
