### ISSUE TITLE
Mapbox token

### ISSUE THREAD

**Issue by nicolaskruchten** [plotly/documentation#1647]
Let's please:

1. create a mapbox account under accounts@plot.ly and put the password in 1Password
2. Create a token from that account that's locked to the plot.ly domain name
3. Use that token for JS/Py/R docs
4. make it such that the token is not bubbled through to CodePen

**Comment by jdamiba** [comment]
for JS docs - https://github.com/plotly/documentation/pull/1648

Environment variable changed in CircleCI for python docs. 

R docs use different key altogether.
