### ISSUE TITLE
R getting started should migrate to r-docs repo

### ISSUE THREAD

**Issue by nicolaskruchten** [plotly/documentation#1651]
Somehow we missed this one! https://github.com/plotly/documentation/blob/source-design-merge/_posts/r/2015-07-30-getting-started.md

**Comment by nicolaskruchten** [comment]
I think we missed https://github.com/plotly/documentation/tree/source-design-merge/_posts/r/chart-events and https://github.com/plotly/documentation/tree/source-design-merge/_posts/r/streaming also

**Comment by jdamiba** [comment]
This issue has been addressed.
