### ISSUE TITLE
What about Dash?

### ISSUE THREAD

**Issue by nicolaskruchten** [plotly/documentation#1654]
We need to add, to every R and Python page other than the "Is Plotly Free?" pages, a section at the bottom that reads something like:

### What about Dash?

[Dash](https://dash.plot.ly/) is an open-source framework for building analytical applications, with no Javascript required, and it is tightly integrated with the Plotly graphing library. Everywhere in this page that you see `fig.show()`, you can display the same figure in a Dash application by passing it to the `figure` argument of the [`Graph` component](https://dash.plot.ly/dash-core-components/graph) from the built-in `dash_core_components` package like this:

```python
import plotly.graph_objects as go # or plotly.express as px
fig = go.Figure() # or the output of any Plotly Express function
# fig.add_trace( ... )
# fig.update_layout( ... ) 

import dash
import dash_core_components as dcc
import dash_html_components as html

app = dash.Dash()
app.layout = html.Div(
    dcc.Graph(figure=fig)
)

app.run_server(debug=True)
```

**Comment by nicolaskruchten** [comment]
@jdamiba let's try to knock this one out this week please.

**Comment by nicolaskruchten** [comment]
Open to ideas about the phrasing and the exact code being shown. maybe the code needs to be page-specific, so as to reuse one of the simpler cells, to make it an actual copy-pasteable example... that would be labour-intensive but worth it IMO.

**Comment by nicolaskruchten** [comment]
@chriddyp @emmanuelle @alexcjohnson  input is welcome on this first pass!

The idea here is that all doc pages get the same little block (for now) and then in some near future we can do per-page blocks that don't show an empty figure.

@jdamiba and I figured out that actually we can append a little bit of Markdown to the notebooks right before rendering them in the CI step, so that this block will get formatted just like any other doc, without having to be manually pasted everywhere. Here is the R PR for this https://github.com/plotly/plotly.r-docs/pull/41 and the Python bit can just go in here somewhere once we agree on the details: https://github.com/plotly/plotly.py/blob/master/doc/Makefile#L32

**Comment by chriddyp** [comment]
Nice! I might change the first line to be:
```
fig = go.Figure() # or the output of any Plotly Express function, like `fig = px.scatter(...)`
```

**Comment by chriddyp** [comment]
and also:
```
app.layout = html.Div([
    dcc.Graph(figure=fig)
])
```

**Comment by chriddyp** [comment]
Since most folks working in plotly are working in jupyter, maybe let's also do this until we fix this in the library level
```
app.run_server(debug=True, use_reloader=False)  # Turn off reloader if inside Jupyter
```
