### ISSUE TITLE
Dash R docs /search not working at all

### ISSUE THREAD

**Issue by nicolaskruchten** [plotly/documentation#1672]
Algolia is seeing zero queries at all.

cc @rpkyle  :)

**Comment by rpkyle** [comment]
@nicolaskruchten I think @cldougl and @KPhans configured this over the summer, but I can confirm that queries are not working at this time.

I wasn't involved with setting this up in July, but if neither of them have bandwidth now, I can help resolve this.

**Comment by nicolaskruchten** [comment]
I'll let @jdamiba reach out if he needs help, but let's let him take the lead on fixing it :)

**Comment by rpkyle** [comment]
This was fixed by @jdamiba in plotly/dash-docs#769. Closing since the fix is in!
