### ISSUE TITLE
Switch banner demo url

### ISSUE THREAD

**Issue by jingningzhang1** [plotly/documentation#1674]
![image](https://user-images.githubusercontent.com/50333592/74964454-742bdc80-53e1-11ea-9f04-7ba8eee7a889.png)

Hi @nicolaskruchten would you be able to switch the demo dash url from https://go.plot.ly/demo_live to https://plot.ly/get-demo/

**Comment by jingningzhang1** [comment]
cc @VeraZab

**Comment by nicolaskruchten** [comment]
@jdamiba can you look after this one today please?

**Comment by jingningzhang1** [comment]
thank you @jdamiba and @nicolaskruchten !
