### ISSUE TITLE
change links from .ly to .com

### ISSUE THREAD

**Issue by nicolaskruchten** [plotly/documentation#1677]
This will likely require PRs in graphing-library-docs, py-docs and r-docs

**Comment by jdamiba** [comment]
addressed by https://github.com/plotly/graphing-library-docs/pull/43, https://github.com/plotly/plotly.py/pull/2312, and https://github.com/plotly/plotly.r-docs/pull/45

**Comment by nicolaskruchten** [comment]
Looks good! Likely introduces a bit of breakage but we can fix those as they come up :)
