### ISSUE TITLE
Javascript reference documentation is borked with Firefox

### ISSUE THREAD

**Issue by Luthaf** [plotly/documentation#1687]
I hope I am opening this on the right repository.

As soon as I start scrolling down with Firefox on https://plotly.com/javascript/reference/, the text starts to get mangled and unreadable:
<img width="989" src="https://user-images.githubusercontent.com/6141587/88546998-6b3cd800-d01d-11ea-9403-100bf2043a6e.png">

The page seems to be working fine on Safari & Chrome.

**meta**: Firefox 78.0.2 (64-bit) on macOS Mojave 10.14.6 (18G5033)

**Comment by nicolaskruchten** [comment]
Thanks for letting us know! I'm breaking this page up into smaller pieces and then I'll see if this still happens :)

**Comment by nicolaskruchten** [comment]
OK, do you still see this on smaller pages like https://plotly.com/python/reference/layout/xaxis/ ?

**Comment by Luthaf** [comment]
No, it seems to be working fine now! And separate pages for separate traces types is much better than the previous reference, thanks for doing this!
