### ISSUE TITLE
Python user guide - broken links

### ISSUE THREAD

**Issue by mariahhamel** [plotly/documentation#169]
Not sure how a user got here (our site seems to lead to plot.ly, rather than help.plot.ly for API documentation).

http://help.plot.ly/documentation/python/streaming-double-pendulum-tutorial/

links to 404s:

https://plot.ly/python/streaming-tutorial
https://plot.ly/python/streaming-line-tutorial
https://plot.ly/python/streaming-double-pendulum-tutorial
https://plot.ly/python/streaming-bubbles-tutorial

**Comment by chriddyp** [comment]
@mariahhamel - I'm not getting 404s on those pages anymore

**Comment by chriddyp** [comment]
I made a fix yesterday or the day before that fixes doc urls that don't have trailing slashes, maybe that fixed what you were seeing? it should be impossible to get directed to any help.plot.ly/documentation/* pages now

**Comment by mariahhamel** [comment]
@chriddyp I made a mistake--the linked URLs are 

http://help.plot.ly/python/streaming-tutorial

Etc.
