### ISSUE TITLE
How to update plot automatically when data is updated

### ISSUE THREAD

**Issue by mkcor** [plotly/documentation#170]
This question comes up on a regular basis, and understandably so.  We're talking about the Web App.

I tend to reply with the following:
1) Create your initial data set. Save the data.
2) Use the saved data to create a plot. Save the plot. Close the plot.
3) Add new data to your saved data set. Save again.
4) Reopen your graph. You will notice that the graph has been
automatically updated with the new data.

But this may become obsolete. @cldougl has pointed users to the 'INSERT INTO' option.

In any case, we should have a tutorial for this, maybe on http://help.plot.ly/?
What do you think?
/cc @mariahhamel @jackparmer @NicoleGrondin @MatthewHiscock

**Comment by jackparmer** [comment]
Yeah, I agree, I see this one all the time. See @cdougl 's response to
jonathanng
this weekend for example. @MatthewHiscock
<https://github.com/MatthewHiscock> or  @mariahhamel
<https://github.com/mariahhamel> want to take stab at this so we can just
send a link instead of writing this every time?

**Comment by MatthewHiscock** [comment]
Yup, I'm game for that. I'll whip something up and bounce it off the others.

**Comment by chriddyp** [comment]
A few things to make sure to cover in the tutorial:
- You don't need to save the data before you make the plot anymore. Saving a graph will automatically create and save a grid
- Use insert into only if you want to add a new trace to a graph, perhaps from a different dataset. You can open multiple datasets and the graph from organize by selecting multiple files and clicking `open` in the modebar
- Show how to find the dataset associated with your graph: if you uploaded, it will have the name of the uploaded file. If you entered data manually, the grid will have the same name as the plot with " Grid" appended to the filename
- You still have to explicitly save the grid to see changes updated, and you still have to open and close the plot to see the changes

**Comment by mkcor** [comment]
https://github.com/plotly/plotly.github.io/commit/b913852928339a699312d51c8454888177c7721d closes this issue (PR was https://github.com/plotly/plotly.github.io/pull/59).
