### ISSUE TITLE
Update Headerbar to reflext new headerbar on streambed

### ISSUE THREAD

**Issue by alexander-daniel** [plotly/documentation#172]
@NicoleGrondin @troiska 

Change "Workspace" to "Organize"

Bring in sweet new dropdowns.

### Old
<img width="1392" alt="screen shot 2015-07-29 at 11 14 14 am" src="https://cloud.githubusercontent.com/assets/5408720/8961405/fd5598e2-35e2-11e5-8d35-9128ee7fc4aa.png">

### New
<img width="1392" alt="screen shot 2015-07-29 at 11 14 21 am" src="https://cloud.githubusercontent.com/assets/5408720/8961413/0d05ecce-35e3-11e5-8ac0-fe7ce2f951fe.png">

**Comment by NicoleGrondin** [comment]
Now Fixed.

**Comment by chriddyp** [comment]
@NicoleGrondin - you can close these issues when they're fixed!
