### ISSUE TITLE
mega white space below banner

### ISSUE THREAD

**Issue by chriddyp** [plotly/documentation#178]
since the banner was added to the docs, there's a wicked 200px white space below the breadcrumbs above the container:

![image](https://cloud.githubusercontent.com/assets/1280389/9343091/e1878828-45cd-11e5-8080-0cceb915db06.png)

could one of you @NicoleGrondin or @jackparmer take a look and slim it down?

**Comment by NicoleGrondin** [comment]
Fixed.
