### ISSUE TITLE
Make a Color Scale page, remove Color Scale examples in Heatmap pages

### ISSUE THREAD

**Issue by etpinard** [plotly/documentation#18]
Heatmap doc pages take quite a bit of time to load e.g. for [python](https://plot.ly/python/heatmaps/) and even worse for [matlab](https://plot.ly/matlab/heatmaps/).

This makes me reluctant to add more Heatmap examples to the docs e.g. this [one](https://app.asana.com/0/11724913287040/13388529493270).

I suggest we make new page, one for each API, dedicated to color scale (custom, pre-defined, used in conjunction with `'zauto'`, `'zmin'` and `'zmax'`, etc.).

Plotly color scales can be used not only in Heatmap, but also in Contour, Histogram2d, Histogram2dContour and Scatter (and hopefully Bar and Histogram soon). So why hide this info in the Heatmap doc page?

The color scale doc page could be placed under Layout as a quick fix that does not require reorganization (although this is far from ideal as `'colorscale'` is a trace key). 

Perhaps we could make a new section on colors, combing the color scale page with a page on color formating (as mentioned in this Asana [task](https://app.asana.com/0/11724913287040/12570800170148)).

**Comment by peter-orchard** [comment]
I was trying to find valid values for the Heatmap colorscale parameter. Searched for a long time before finding this page. It's far from obvious that I was supposed to look up the Layout class.
