### ISSUE TITLE
improve python streaming docs

### ISSUE THREAD

**Issue by chriddyp** [plotly/documentation#183]
-  copy / paste stream example brings in >>>
- First streaming plot example is broken up / hard to copy-paste
- Quick start is only one x,y point which was confusing to some folks
- Streaming token doesn’t autofill on “Hello world” streaming example, need comment with link on where to get your streaming token
- Explanation on why here are 2 streaming tokens in /settings... folks didn't know which one to use

**Comment by cldougl** [comment]
fyi @yankev
