### ISSUE TITLE
"type" is missing in reference docs pages

### ISSUE THREAD

**Issue by jackparmer** [plotly/documentation#186]
For example type="category" for x/y axes

![image](https://cloud.githubusercontent.com/assets/1865834/9945557/f52c2294-5d5b-11e5-8987-15c4496825e0.png)

**Comment by chriddyp** [comment]
fixed in https://github.com/plotly/documentation/commit/bc863caf779cfa899e0fdd51ce7abcdef028fd52

**Comment by chriddyp** [comment]
deployed: https://plot.ly/python/reference/#layout-xaxis-type

**Comment by etpinard** [comment]
@chriddyp `error_?` have a `type` too

![image](https://cloud.githubusercontent.com/assets/6675409/9947163/14aeb578-5d66-11e5-81f7-8f2f7481053d.png)

**Comment by chriddyp** [comment]
fixed in https://github.com/plotly/documentation/commit/4720c901725f1cec1efa61a6c23683ff6030ab21

**Comment by chriddyp** [comment]
deployed: https://plot.ly/python/reference/#scatter-error_y-type
