### ISSUE TITLE
layout.xaxis.type options are not documented

### ISSUE THREAD

**Issue by jackparmer** [plotly/documentation#187]
Only log is really documented:

https://plot.ly/javascript/log-plot/

~~There should be examples with all the options: linear, log, date, and category here:~~

A good example would be for a plot that mixes numeric and non-numeric values on the x-axis then uses type = "category". So, x values would be something like [A12, B12, 1, C12, 2, 3]

https://plot.ly/javascript/axes/

![image](https://cloud.githubusercontent.com/assets/1865834/9945666/9528202c-5d5c-11e5-93da-1dac62eceacf.png)

Would be a good example for Python docs too.

**Comment by NicoleGrondin** [comment]
Categorial and date axis type examples created:
https://plot.ly/javascript/axes/#using-dates-on-the-x-axis
https://plot.ly/javascript/axes/#categorical-axes
