### ISSUE TITLE
Plotly.js example with showlink: false

### ISSUE THREAD

**Issue by jackparmer** [plotly/documentation#188]
Syntax is:

Plotly.plot(divid, data, layout, {showLink: false})

We need an example for this in the javascript docs.

**Comment by chriddyp** [comment]
+ the rest of the "config" variables

On Thu, Sep 17, 2015 at 8:14 PM, Jack Parmer <notifications@github.com>
wrote:

> Syntax is:
>
> Plotly.plot(divid, data, layout, {showLink: false})
>
> We need an example for this in the javascript docs.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/plotly/documentation/issues/188>.
>



-- 
Chris Parmer
Plotly, Chief Product Officer
514 571 5897
https://plot.ly/team

**Comment by cldougl** [comment]
plotly.js config options doc here: https://plot.ly/javascript/configuration-options/
