### ISSUE TITLE
how to remove "Edit chart" link in plotly.js

### ISSUE THREAD

**Issue by chriddyp** [plotly/documentation#189]
@NicoleGrondin We should add this here: https://plot.ly/javascript/#layout-options
@etpinard what's the official way to do this now?

**Comment by etpinard** [comment]
Using the fourth `Plotly.plot` argument, e.g `Plotly.plot(divid, data, layout, {showLink: false})`

More info about the config options [here](https://github.com/plotly/streambed/blob/master/shelly/plotlyjs/static/plotlyjs/src/graph_obj.js#L237-L270).

**Comment by chriddyp** [comment]
ah, great thx @etpinard ! does it make sense to have these guys in graph reference?

**Comment by chriddyp** [comment]
we should add this argument to https://plot.ly/javascript/plotlyjs-function-reference/, too, and list all of the available options in another page like javascript/config

**Comment by NicoleGrondin** [comment]
@chriddyp I started adding some config examples at : https://plot.ly/javascript/configuration-options/
Is that the style etc you were looking for?

**Comment by chriddyp** [comment]
looks great @NicoleGrondin ! 
- could we make the codepen container a little bit bigger so that that there isn't any scroll? 
![image](https://cloud.githubusercontent.com/assets/1280389/10093124/17be7148-631c-11e5-81be-5adb5738ce89.png)

**Comment by chriddyp** [comment]
I also just added a reference to this page in the function reference: https://github.com/plotly/documentation/commit/a7119c6c38cdf2de78c7f61214fe7c13c7d069a2

**Comment by cloaked123** [comment]
Hello - this doesn't seem to work for python? I tried: 
py.plot(fig, showLink=False,fileopt='overwrite', filename='RPi')

However, it still shows the Edit link.

**Comment by douglasg14b** [comment]
This no longer seems to work for JavaScript.

**Comment by cldougl** [comment]
seems to be working as expected: https://plot.ly/javascript/configuration-options/#hide-edit-chart-link

**Comment by douglasg14b** [comment]
@cldougl The codepen appears to either be using an old version or a different build of plotly.

**Comment by cldougl** [comment]
@douglasg14b with the latest version it still appears to be working (updated: https://plot.ly/javascript/configuration-options/#hide-edit-chart-link) 
do you have an example of where it's not working?

**Comment by douglasg14b** [comment]
@cldougl The codepen for that doe snot work, there still exists a button to "Edit Chart in Cloud": https://codepen.io/plotly/pen/epdjem


![image](https://cloud.githubusercontent.com/assets/1400380/23723407/ea860428-03fd-11e7-9aa5-e86d7b57132e.png)

**Comment by douglasg14b** [comment]
@cldougl Upon further research I have found this, that works: `{modeBarButtonsToRemove: ['sendDataToCloud']}`

**Comment by cldougl** [comment]
The edit chart link refers to the link on the bottom right corner (which is hidden by default: )
Editing the modebar is a different configuration option. See: https://github.com/plotly/plotly.js/blob/master/src/plot_api/plot_config.js#L58https://github.com/plotly/plotly.js/blob/master/src/plot_api/plot_config.js#L69-L87
