### ISSUE TITLE
Fix stream domain spec for getting started with On-Prem special instructions

### ISSUE THREAD

**Issue by BRONSOLO** [plotly/documentation#191]
Special Instructions for Plotly On-Premise users does not provide the correct stream domain in the call to saveplotlyconfig: https://plot.ly/matlab/getting-started/

It is currently: `plotly.your-company.com`
It should be: `stream-plotly.your-company.com`

**Comment by BRONSOLO** [comment]
@chriddyp

**Comment by chriddyp** [comment]
@BRONSOLO - that section is here: https://github.com/plotly/documentation/blob/source/_posts/matlab/getting-started/2015-05-25-getting-started_matlab_index.html#L49-L51 - feel free to just edit in the github browser on the `source` branch, and then i can deploy (or you can!)

**Comment by BRONSOLO** [comment]
@chriddyp sweet just made the change! thanks.
