### ISSUE TITLE
NameError: name 'df_sum_arrivals' is not defined

### ISSUE THREAD

**Issue by chriddyp** [plotly/documentation#193]
@jackparmer - https://github.com/plotly/documentation/blob/source/_posts/pandas/scatter-plot-on-maps/2015-06-29-us-airports-map.html#L42, and here: https://github.com/plotly/documentation/blob/source/_posts/python/scatter-plot-on-maps/2015-06-29-us-airports-map.html#L42

**Comment by tarzzz** [comment]
Closed via #309
