### ISSUE TITLE
Change hover text in stacked area chart example

### ISSUE THREAD

**Issue by jackparmer** [plotly/documentation#198]
Another small Python edit that keeps coming up over and over:

https://plot.ly/python/filled-area-plots/#stacked-area-chart

Put the 'real' data in `text` & and set hoverinfo: 'x+text'

People ask this all the time but here's the latest:

![image](https://cloud.githubusercontent.com/assets/1865834/10618876/61e91f88-7740-11e5-9ef2-cd0edaa171d7.png)

**Comment by etpinard** [comment]
@jackparmer 

We mean making a new Figure Factory for stacked area charts?

Putting a condition around `hoverinfo`  in the native `Scatter` graph object sounds like a syncing nightmare.

**Comment by cldougl** [comment]
I thought just making an example so hover shows individual % not cumulative?

**Comment by etpinard** [comment]
Oops my bad. I didn't read to issue title correctly

**Comment by jackparmer** [comment]
Right, just show how to hack around this without FigureFactory for now.

**Comment by cldougl** [comment]
https://plot.ly/python/filled-area-plots/#stacked-area-chart-with-original-values

**Comment by ViolaRudenko** [comment]
Do you guys know how to format 'text' to dollar amount format in R? Even though my 'real' data is already formatted correctly, once I do hoverinfo='x+text' in add_trace function, it loses the formatting. Hoverformat = "$,f" in the layout function didn't help.

**Comment by chriddyp** [comment]
hey @ViolaRudenko - could you open this issue in the R library repository (https://github.com/ropensci/plotly/issues/new) with a reproducable example? Thanks!

**Comment by ViolaRudenko** [comment]
Thanks, Chris! I just opened a new issue here - https://github.com/plotly/documentation/issues/271
