### ISSUE TITLE
trace-type specific layout attributes don't show in the reference pages

### ISSUE THREAD

**Issue by etpinard** [plotly/documentation#202]
@chriddyp 

e.g. `bargap` which is  under `traces.bar.layoutAttributes` in the plot schema.

**Comment by jackparmer** [comment]
Same for Box Gap and Group Gap for box plots.

**Comment by bpostlethwaite** [comment]
This just got me too. It will fail for `violin` plots now as well.

**Comment by le-absent** [comment]
I know this is a few months after the original post, but I'm encountering issues with these attributes as well as "hidden labels".

**Comment by etpinard** [comment]
@le-absent it would be best to ask your questions on -> https://community.plot.ly/ 

Thank you.

**Comment by nicolaskruchten** [comment]
Is this a deliberate decision or something that no one has had the time to tackle or... ?

**Comment by etpinard** [comment]
> Is this a deliberate decision or something that no one has had the time to tackle or... ?

Most devs have deliberately no time for this.

**Comment by etpinard** [comment]
... moreover, the UI isn't trivial. Should trace layout attributes be under the corresponding trace section or under layout?

**Comment by nicolaskruchten** [comment]
@etpinard challenge accepted: #927

**Comment by GeoffCapper** [comment]
No idea whether you prefer a comment on a closed item or a new item referencing this, apologies if I've got it wrong! The documentation for barmode seems to have gone missing from the JS reference for polar.

Using the in-page search throws up references to the parameter but not the actual parameter reference, and there is no mention of it in the left hand menu.

Using the browser find function will find it (https://plot.ly/javascript/reference/#layout-barmode), but it seems to lack the context as to what node it should appear under.

It's physically situated under "Update Menus" and "Sliders" (which are swapped in the document compared to the left hand menu) with a lot of other layout parameters.

**Comment by nicolaskruchten** [comment]
Heh, yeah the ordering on that page is a bit of a dog's breakfast at the moment and we're working on it. The trace-specific layout attributes are especially problematic, as you've called out.

**Comment by nicolaskruchten** [comment]
@GeoffCapper thanks for the heads-up re search and `barmode`... this part of it has been fixed. It shows up thrice in the search results because it's linked to three separate traces, but we'll sort that out soon :)
