### ISSUE TITLE
[plotly.js] add docs about non-browserify workflows in getting-started page

### ISSUE THREAD

**Issue by etpinard** [plotly/documentation#230]
@mdtusz @chriddyp @jackparmer @bpostlethwaite @cldougl 

Quite a bit of folks have been complaining about plotly.js 's npm-browserify-centric view of the world:

https://github.com/plotly/plotly.js/issues/13
https://github.com/plotly/plotly.js/issues/22

I would be nice to make the plotly.js getting started page ([page](https://plot.ly/javascript/getting-started/) | [source](https://github.com/plotly/documentation/blob/source/_posts/plotly_js/getting-started/2015-07-21-plotlyjs-getting-started.html)) show how plotly.js works with workflows.

Moreover, we should write a section about how to plotly.js users can build their own bundle e.g. a bundle with d3 removed using [`browserify -x`](https://github.com/substack/node-browserify#multiple-bundles).

**Comment by bpostlethwaite** [comment]
Agreed, @mdtusz sounds like a good issue for you to tackle. It will intro you to our existing documentation and build tooling. Want to work with @etpinard and @cldougl on this?

**Comment by chriddyp** [comment]
Here is the source: https://github.com/plotly/documentation/blob/source/_posts/plotly_js/getting-started/2015-07-21-plotlyjs-getting-started.html

**Comment by etpinard** [comment]
@mdtusz We should document this https://github.com/plotly/plotly.js/issues/39 in the getting started

When using the un-minified `dist/plotly.js`, you must include `charset="utf-8"` in the script tag.

**Comment by mdtusz** [comment]
Will do. We can also add a `webpack` field in the package.json so that users don't have to `require('plotly.js/dist/plotly.min.js')` and can just `require('plotly.js')`.

**Comment by etpinard** [comment]
@mdtusz +1 for the webpack field.

**Comment by mdtusz** [comment]
Should all work now for webpack users. It's not a beautiful unicorn fix, but it works and will let them get plotting.

**Comment by bpostlethwaite** [comment]
@mdtusz, this one in the bag then?

**Comment by bpostlethwaite** [comment]
ah saw the note about holding till the next release! disregard :)
