### ISSUE TITLE
Exporting PNG files from Plotly in R

### ISSUE THREAD

**Issue by adrianericcook** [plotly/documentation#235]
We need an R version on how to export a Plotly chart as a image from R using code. (i.e.Not using the export button on the chart).
http://stackoverflow.com/questions/33959635/exporting-png-files-from-plotly-in-r

We have a document like this in Python: https://plot.ly/python/static-image-export/

**Comment by cpsievert** [comment]
Just to be clear, `plotly_IMAGE()` does the same thing as `py.image.save_as` in https://plot.ly/python/static-image-export/

**Comment by JohnnyRieper** [comment]
A local solution of plotly_IMAGE would be most welcome

**Comment by royr2** [comment]
@adrianericcook we have a page[here](https://plot.ly/r/static-image-export/) that highlights the use of `plotly_IMAGE()`.
