### ISSUE TITLE
[plotly.js] document Plotly.extendTraces

### ISSUE THREAD

**Issue by etpinard** [plotly/documentation#250]
as requested here:

http://stackoverflow.com/questions/34345026/visualising-data-with-javascript-graphs-dynamically/34345451#34345451

**Comment by dandv** [comment]
C'mon guys, it's been almost a year now and we still can't find `extendTraces` and `prependTraces` at https://plot.ly/javascript/reference/.

**Comment by sjoerdmaessen** [comment]
Yes please

**Comment by BobbyAdamson** [comment]
Really want to use plotly to graph facebook reaction data in real-time, we need something for extend traces please

**Comment by cldougl** [comment]
see the js function reference page (https://plot.ly/javascript/plotlyjs-function-reference/#plotlyextendtraces) for more information and an example of `Plotly.extendTraces`
