### ISSUE TITLE
Mention tag CDN link on plotly.js getting-started

### ISSUE THREAD

**Issue by etpinard** [plotly/documentation#254]
Presenting https://cdn.plot.ly/plotly-latest.min.js first is good, but we should also present the tag cdn links e.g https://cdn.plot.ly/plotly-1.2.0.min.js somewhere on https://plot.ly/javascript/getting-started/

**Comment by tarzzz** [comment]
@jp @etpinard should be a quick fix..

**Comment by tarzzz** [comment]
This is fixed!
