### ISSUE TITLE
Follow up to issue #189: How to remove Edit Chart Link.

### ISSUE THREAD

**Issue by ghost** [plotly/documentation#267]
Hello - this is a follow up to issue #189
The solution to set showLink to False doesn't seem to work for python? 

I tried: 
py.plot(fig, showLink=False,fileopt='overwrite', filename='RPi')

However, it still shows the Edit link.

**Comment by Hotschke** [comment]
+1

**Comment by ogothe** [comment]
`fig = go.Figure(data=data, layout=layout)
py.iplot(fig,show_link=False)`

did not work in my jupyter notebook

**Comment by yankev** [comment]
What version of Plotly do you have installed?

**Comment by ogothe** [comment]
1.9.7

**Comment by mrcanalytics** [comment]
I'm having the same issue. Has anything been updated to allow the removal of "edit chart" link on python generated plots?

**Comment by sb5518** [comment]
Hi! Just wanted to know if there was any update regarding this issue. Thanks!

**Comment by cjosephson** [comment]
I would appreciate any updates as well

**Comment by cldougl** [comment]
For Plotly's APIs you can remove the edit chart link when using the offline mode.

For python, an example would be:
```
from plotly.offline import init_notebook_mode, iplot
from plotly.graph_objs import Scatter

init_notebook_mode()
iplot([Scatter(x=[1, 2, 3], y=[3, 1, 6])], show_link=False)
```

Config options set via our API libraries are overridden on graphs hosted on plot.ly (i.e. when working online). You can remove the edit chart link from an online plot by adding that attribute to the url: https://plot.ly/~chelsea_lyn/12789.embed?show_link=false
See more info on embedding options here: http://help.plot.ly/embed-graphs-in-websites/#customizing-the-iframe

**Comment by cldougl** [comment]
https://plot.ly/python/configuration-options/
