### ISSUE TITLE
Switch to Jekyll Syntax Highlighting

### ISSUE THREAD

**Issue by mxstbr** [plotly/documentation#279]
There's no need for a big JavaScript file (`highlight.pack.js`) to be loaded in [`_includes/footer.html`](https://github.com/plotly/documentation/blob/source/_includes/footer.html#L77-L79) for syntax highlighting. Has a negative performance impact and if JS is disabled there is no highlighting.

AFAIK, (and that works for `plotly/academy`), Jekyll (or maybe redcarpet, the Markdown parser, I'm not sure where it happens) automatically adds Syntax highlighting to fenced codeblocks with [Pygments](http://pygments.org/).

Í don't know which theme you're using to syntax highlight, but even if it isn't available for Pygments you can convert it from a `.tmTheme` file if you have that using [this python script](https://github.com/davinche/pygments-from-tmtheme).

----

> Note: Fenced codeblocks are code blocks delimited with 3 `~`s or 3 backticks.

**Comment by etpinard** [comment]
@chriddyp @cldougl :arrow_up:

**Comment by mxstbr** [comment]
You actually load highlight.js twice, once in the [`_includes/head.html`](https://github.com/plotly/documentation/blob/source/_includes/head.html#L14-L15) from a CDN, and once locally in the aforementioned footer.

**Comment by cldougl** [comment]
changed w/ doc redesign
