### ISSUE TITLE
move python database docs to main page

### ISSUE THREAD

**Issue by cldougl** [plotly/documentation#288]
Create a DATA IMPORT section at https://plot.ly/python/ for the [connecting to databases](https://plot.ly/ipython-notebooks/gallery/#connecting-to-databases) docs and add an 'import/plot from CSV' tutorial

** and make sure to either leave or redirect from all of the connecting to db tutorials [here](https://plot.ly/ipython-notebooks/gallery/#connecting-to-databases)

**Comment by tarzzz** [comment]
grabbing this one.. @jackparmer @cldougl

**Comment by cldougl** [comment]
Excellent!!! Thanks @tarzzz

**Comment by tarzzz** [comment]
This can be closed now, as the CSV Import tutorial is also in place.
