### ISSUE TITLE
Plotly.js reference not displayed fully.

### ISSUE THREAD

**Issue by mdtusz** [plotly/documentation#292]
@cldougl @tarzzz 

Reference section doesn't have all the documentation being displayed - none of the documentation past the initial bit that explains the general structure of data and layout.

![screen shot 2016-01-28 at 11 31 43 am](https://cloud.githubusercontent.com/assets/6494463/12650957/d399cb08-c5b2-11e5-8e5e-322787ee4217.png)

**Comment by etpinard** [comment]
I think @chriddyp deployed a fix earlier this am

**Comment by cldougl** [comment]
all of our ref pages are broken - taking a look now

**Comment by chriddyp** [comment]
broke last night when the plot.ly/plot-schema.json was taken down - fixing
now

On Thu, Jan 28, 2016 at 11:41 AM, Chelsea <notifications@github.com> wrote:

> all of our ref pages are broken - taking a look now
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/plotly/documentation/issues/292#issuecomment-176275702>
> .
>



-- 
Chris Parmer
Plotly, Chief Product Officer
514 571 5897
https://plot.ly/team

**Comment by cldougl** [comment]
:+1: thanks @chriddyp

**Comment by chriddyp** [comment]
looks like the schema.json structure changed too. just added a fix here: https://github.com/plotly/documentation/commit/c8c24d435f88a4d5cb8c2b98efc53d8e6a0e1b41. deploying now.

**Comment by chriddyp** [comment]
![image](https://cloud.githubusercontent.com/assets/1280389/12652463/ecc2a69e-c5b8-11e5-8460-a84656ffd707.png)
although the order of the traces has changed in this new schema
