### ISSUE TITLE
Themes Doc

### ISSUE THREAD

**Issue by cldougl** [plotly/documentation#300]
- Add doc about workspace themes

**Comment by cldougl** [comment]
hey @tarzzz even if you could just start this and get a few screenshots in that would be really helpful

let's put it: http://help.plot.ly/themes/

**Comment by tarzzz** [comment]
Added, Closing!

**Comment by cldougl** [comment]
- [ ] add thumbnail image
- [ ] add example: creating/saving/applying a custom theme that explains what properties are applied in themes
