### ISSUE TITLE
make thumbnails for excel tutorials a uniformed size

### ISSUE THREAD

**Issue by cldougl** [plotly/documentation#302]
http://help.plot.ly/tutorials/#excel

**Comment by tarzzz** [comment]
This is complicated than I thought. The http://help.plot.ly/tutorials/#excel and http://help.plot.ly/excel/ thumbnails are sourced from same place. Fixing for one will break the other..

  - http://help.plot.ly/tutorials/#excel : requires images of approx: 160x160 dimensions
  - http://help.plot.ly/excel/ : requires 400x300 (approx.) dimension/aspect ratio.

**Comment by cldougl** [comment]
@tarzzz we're redoing the excel tutorial page so I'm going to close this cause the issue should be solved with the new page (so you're off the hook :) )
