### ISSUE TITLE
make continuous error bar docs

### ISSUE THREAD

**Issue by cldougl** [plotly/documentation#315]
- [x] switch image for python line doc
- [x] for python at https://plot.ly/python/continuous-error-bars/
under scientific charts (next to Error Bars) including the following 2 exmaples https://plot.ly/python/line-charts/#Filled-Lines and https://plot.ly/pandas/error-bars/#asymmetric-error-bars-with-a-constant-offset **use error-cont.jpg for the image (it's already uploaded on AWS)
- [x] for js at https://plot.ly/javascript/continuous-error-bars/ **use error-cont.jpg for the image (it's already uploaded on AWS)

**Comment by tarzzz** [comment]
This is handled in #316

**Comment by tarzzz** [comment]
Closing!..
