### ISSUE TITLE
improve colorscale doc

### ISSUE THREAD

**Issue by cldougl** [plotly/documentation#326]
https://plot.ly/python/heatmap-and-contour-colorscales/
- [x] redirect to https://plot.ly/python/colorscales/
- [x] add an example of scatter w/ a colorscale
- [x] add some examples to demonstrate some of [these attributes](https://plot.ly/python/reference/#heatmap-colorbar) - *specifically `tickvals` and `ticktext`

create 
- [x] https://plot.ly/javascript/colorscales/
- [x] https://plot.ly/r/colorscales/

should be under style category

**Comment by bcdunbar** [comment]
may have to wait for https://github.com/ropensci/plotly/issues/1021 to add R colorscale docs
