### ISSUE TITLE
Add docs for layout.barmode & layout.bargap

### ISSUE THREAD

**Issue by cpsievert** [plotly/documentation#328]
Can't find them on https://plot.ly/r/reference/, but we definitely use them in the ggplot2 converter

**Comment by cldougl** [comment]
yeah we don't have `barmode` & `bargap` on any of the ref pages yet (cause they didn't really fit with the way the reference is organized) but we should add them in and make that reference more complete.

**Comment by cldougl** [comment]
duplicate of https://github.com/plotly/documentation/issues/202
