### ISSUE TITLE
add example where axis is reversed AND min/max is defined

### ISSUE THREAD

**Issue by cldougl** [plotly/documentation#338]
from an intercom Q
- [x] for python: https://plot.ly/python/axes/
- [ ] for js: https://plot.ly/javascript/axes/

**Comment by tarzzz** [comment]
Added,

Python: https://plot.ly/python/axes/#reversed-axes-with-range-(-min/max-)-specified
JS: https://plot.ly/javascript/axes/#reversed-axes-with-range-(-min/max-)-specified


Closing!

**Comment by alexcjohnson** [comment]
This didn't actually work correctly - or, if it did previously, it doesn't now, not 100% sure. You've specified `autorange: 'reversed', range: [0, 10]` but the range has been discarded, and we just get a padded reversed autorange.

You can just do `range: [10, 0]` and omit `autorange` entirely. https://codepen.io/alexcjohnson/pen/WaWJLj

brought up in https://github.com/plotly/plotly.js/issues/3176
