### ISSUE TITLE
Issues/suggestions in new Design [2016]

### ISSUE THREAD

**Issue by tarzzz** [plotly/documentation#352]
Here it goes:

  - [x] getting 404 on server side .. 
![image](https://cloud.githubusercontent.com/assets/1546532/13820479/87c02cc2-ebc3-11e5-8aea-f9212f2de4bf.png) First one is probably a typo.

  - [x] Chart examples w/o thumbnails ( i.e. Layout Options, File Settings etc. ) are not showing up on language index pages.

**Comment by yankev** [comment]
- The 404 page isn't working: http://52.90.54.46:4000/r/referencedsf
- The formatting of `python` in the title and `plot objects` is off 
![image](https://cloud.githubusercontent.com/assets/12302455/13820616/8e3dbb68-eb74-11e5-8733-2401f75dafe0.png)

**Comment by aulneau** [comment]
Fixed the reference issues.

@yankev I'm not sure if the sign in/sign up links will work -- I'm not sure how you've been dealing with them in the past (modal, redirect, etc)

A lot of the code boxes are pretty touchy, I'll go back in and play with it.

**Comment by yankev** [comment]
Just some more formatting, in particular for the python user guides: for example:
http://localhost:4000/python/bar-charts-tutorial/

**Comment by aulneau** [comment]
- [ ] Add return to top button
