### ISSUE TITLE
Typo in docs: https://plot.ly/javascript/plotlyjs-function-reference/#plotly-relayout

### ISSUE THREAD

**Issue by hamogu** [plotly/documentation#369]
The first three lines in the example in section https://plot.ly/javascript/plotlyjs-function-reference/#plotly-relayout
read: 

```
var update = {
    title: 'some new title',
    xaxis.range: [0, 5]
```

That fails with `SyntaxError: missing : after property id`. Instead it must be `"xaxis.range" : [0,5]`. The Pen is correct, but the code shown on the page should be corrected.

**Comment by DeluxZ** [comment]
There is another type in the same doc. 

```javascript
// update an entire nested object with relayout
var update = {
    tile: 'some new title',
    xaxis: {range: [0, 5]}
};
Plotly.relayout(graphDiv, update)
```

**Comment by cldougl** [comment]
attribute typos have been addressed on https://plot.ly/javascript/plotlyjs-function-reference/
