### ISSUE TITLE
import data (and remove giant data blocks)

### ISSUE THREAD

**Issue by cldougl** [plotly/documentation#376]
for the following tutorials the data should be imported rather than pasted as a giant codeblock. 
You can create a csv and host here: https://github.com/plotly/datasets
then import the data rather than entering the data as a block

- [x] https://plot.ly/python/bubble-charts/#categorical-bubble-charts
- [x] https://plot.ly/python/graphing-multiple-chart-types/#a-contour-and-scatter-plot-of-the-method-of-steepest-descent
- [x] https://plot.ly/python/line-and-scatter/#data-labels-on-hover
- [x] https://plot.ly/python/box-plots/#fully-styled-box-plots
- [x] https://plot.ly/python/polar-chart/#polar-line-chart
- [x] https://plot.ly/python/polar-chart/#polar-scatter-chart

- [x] https://plot.ly/javascript/continuous-error-bars/#asymmetric-error-bars-with-a-constant-offset
- [x] https://plot.ly/javascript/polar-chart/ *both* examples on this page
- [x] https://plot.ly/javascript/box-plots/#fully-styled-box-plot
- [x] https://plot.ly/javascript/heatmap-and-contour-colorscales/ every example on this page *but* all the examples are using the same dataset :) 
- [x] https://plot.ly/javascript/3d-scatter-plots/
- [x] https://plot.ly/javascript/3d-line-plots/
- [x] https://plot.ly/python/heatmap-and-contour-colorscales/#custom-heatmap-colorscale
- [x] https://plot.ly/javascript/ribbon-plots/
- [x] https://plot.ly/javascript/3d-surface-plots/#topographical-3d-surface-plot

**Comment by yankev** [comment]
https://plot.ly/python/graphing-multiple-chart-types/ pushed the change for this guy (not yet deployed)
