### ISSUE TITLE
Documentation for multiple plots in a single knitr chunk

### ISSUE THREAD

**Issue by cpsievert** [plotly/documentation#377]
Here is the "official" way to do it -- https://github.com/ropensci/plotly/issues/273#issuecomment-195611009

I've seen questions about this in multiple places, including https://github.com/ropensci/plotly/issues/570

**Comment by cldougl** [comment]
add example mentioned above to https://plot.ly/r/knitr/

**Comment by cpsievert** [comment]
FWIW this is covered in the plotly book -- https://cpsievert.github.io/plotly_book/arranging-htmlwidgets.html
