### ISSUE TITLE
Header links don't snap into the right position for Example Index Pages

### ISSUE THREAD

**Issue by yankev** [plotly/documentation#380]
If you click on section in the navigation menu, it will snap to the right position on the page.
![image](https://cloud.githubusercontent.com/assets/12302455/15082063/cee72d56-1393-11e6-9e66-52b1c5387794.png)

However if you run the url in the address bar, it will not align properly.
e.g)
https://plot.ly/r/#maps
![image](https://cloud.githubusercontent.com/assets/12302455/15082045/bbca1d82-1393-11e6-914f-88b221236a2a.png)

**Comment by yankev** [comment]
@aulneau thinks it could be ad related.

**Comment by nicolaskruchten** [comment]
This works for me.
