### ISSUE TITLE
diamonds shiny example

### ISSUE THREAD

**Issue by cpsievert** [plotly/documentation#385]
From @MySchizoBuddy in #583

> The shiny-plotly example about [diamonds facet plots](https://plot.ly/r/shinyapp-explore-diamonds/) has an input slider named height of plot which doesn't do anything. The server.R code doesn't use it anywhere. Either remove that slider or show us how to change the plot height using the slider

Also pageWithSidebar() is deprecated you have to use fluidPage instead

**Comment by royr2** [comment]
Have updated example and app...
