### ISSUE TITLE
Fix broken R examples

### ISSUE THREAD

**Issue by cpsievert** [plotly/documentation#387]
Some of our r pages are using old, backward-incompatible code -- here are some things to watch out for:

* Trace properties are no longer inherited when adding traces to an existing plot. So, for example, the second example on <https://plot.ly/r/bar-charts/> should be:

```r
p2 <- add_trace(
  p,
  x = c("giraffes", "orangutans", "monkeys"),
  y = c(12, 18, 29),
  name = "LA Zoo",
  type = "bar"
)
```

instead of 

```r
p2 <- add_trace(
  p,
  x = c("giraffes", "orangutans", "monkeys"),
  y = c(12, 18, 29),
  name = "LA Zoo",
  filename="r-docs/simple-bars"
)
```

* Also, note that `filename` is no longer an argument in `plot_ly()` or `add_trace()`. It is only relevant for `plotly_POST()`

**Comment by timelyportfolio** [comment]
I plan to get to a lot of these soon.

**Comment by yankev** [comment]
Ye, I'll edit some of these as well.

**Comment by royr2** [comment]
Let me know and I can help as well

**Comment by yankev** [comment]
- [ ] https://plot.ly/r/bar-charts/

**Comment by MySchizoBuddy** [comment]
it would be beneficial if the code is using the single file format of app.R rather than the ui.R/server.R model

**Comment by yankev** [comment]
Pushed changes for the `Basic Charts` section.

**Comment by yankev** [comment]
I think this can be closed. It's possible that I might've missed something, but in that case a new issue can be made and looked at on a case by case manner.

**Comment by cldougl** [comment]
@yankev +1 for closing (this massive issue) but can you open an issue for the shiny example w/ missing depends
