### ISSUE TITLE
Add info about new `Plotly` methods to reference page

### ISSUE THREAD

**Issue by etpinard** [plotly/documentation#395]
In the past few weeks, three new `Plotly` methods were added to plotly.js. We should add info about them on [/javascript/plotlyjs-function-reference/](https://plot.ly/javascript/plotlyjs-function-reference/).

These new methods are:

- [x] `Plotly.purge` in [`v1.7.0`](https://github.com/plotly/plotly.js/releases/tag/v1.7.0) which clears the graph div to its pre-Plotly.plot state
- [x] `Plotly.toImage` in [`v1.11.0`](https://github.com/plotly/plotly.js/releases/tag/v1.11.0) which turns an existing plotly graph into an image string
- [x] `Plotly.downloadImage` in [`v1.11.0`](https://github.com/plotly/plotly.js/releases/tag/v1.11.0) which turns programatically download an existing plotly graph.

**Comment by timelyportfolio** [comment]
Here is a [codepen example](http://codepen.io/timelyportfolio/pen/MyzGWY) of `toImage` that could be adapted for documentation.

**Comment by yankev** [comment]
Just added these. Let me know if there are any changes I should make.

**Comment by cldougl** [comment]
@yankev I would remove the svg example from https://plot.ly/javascript/plotlyjs-function-reference/#generating-image-strings-with-plotlytoimage I think having the png and pdf (pro example) is enough -- the svg just results in a large text block so it's not a super great visual

**Comment by yankev** [comment]
@cldougl, k removed. Closing #395
