### ISSUE TITLE
make ticktext // tickvals example w/ applicable data

### ISSUE THREAD

**Issue by cldougl** [plotly/documentation#429]
Replace: https://plot.ly/python/axes/#enumerated-ticks-with-tickvals-and-ticktext and https://plot.ly/javascript/axes/#enumerated-ticks-with-tickvals-and-ticktext

here's an example: http://nbviewer.jupyter.org/github/gvallverdu/cookbook/blob/master/plotly_bandDiagram.ipynb

**Comment by Kully** [comment]
Resolved with version 1.12.9

**Comment by Kully** [comment]
@cldougl I'm confused by what you want me to do. Do you want me to replace the enumerated-ticks-with-tickvals-and-ticktext example in each with the `Bands of Silicon` Diagram in the last link you sent?

**Comment by cldougl** [comment]
@Kully yes exactly. We want a real use case example!

**Comment by Kully** [comment]
> @Kully yes exactly. We want a real use case example!

Do you know if he has posted the files he is refering to online somewhere? I just see the personal directories `./Bandes/vasprun.xml` so I'm kinda stumped. Should I just find other real data?
