### ISSUE TITLE
Reference documentation about Area charts is wrong

### ISSUE THREAD

**Issue by charlespwd** [plotly/documentation#432]
On the https://plot.ly/javascript/reference/#area page, the description:

> A area trace is an object with the key "type" equal to "area" (i.e. {"type": "area"}) and any of the keys listed below.

is wrong. As trying to do this gives me the following warning.

```
2plots.js:102 unrecognized trace type area
```

Also, the trace.type=='scatter' fill option is undocumented.

**Comment by cldougl** [comment]
Hey there, thanks for reporting the area issue.
As for the fill- is this what you're looking for?
https://plot.ly/javascript/reference/#scatter-fill
If not, could you let me know which option you're trying to find?

**Comment by cldougl** [comment]
Hey @charlespwd 

Regarding the fill- is this what you're looking for? https://plot.ly/javascript/reference/#scatter-fill
If not, could you let me know which option you're trying to find?

Additionally, type: area is referring to our polar charts. Here's an example of a use-case: https://plot.ly/javascript/wind-rose-charts/#wind-rose-chart

**Comment by charlespwd** [comment]
That's what I was looking for.

About area... shouldn't it be named `polar` instead of `area`? Look at https://plot.ly/javascript/filled-area-plots/ which uses `{ type: 'scatter', fill: 'tozeroy' }`

**Comment by cldougl** [comment]
Yep - but sometimes they're referred to as polar area charts. They got stuck with the `type: area`. Eventually we'll be reworking a _lot_ of the code related to polar charts and the type will likely change from area, (but not in the near future).

Feel free to let us know if you run into any other issues in the docs!!
