### ISSUE TITLE
'Fork on Github' button doesn't work

### ISSUE THREAD

**Issue by ellecj** [plotly/documentation#492]
The 'Fork on Github' button at the top of the tutorial pages don't work. I used to do this a lot with the Plotly 1 tutorials and open them in the new workspace, but now it doesn't seem to do anything when you click. No error message.

![fork-and-edit](https://cloud.githubusercontent.com/assets/8120592/17148876/d0bc38fa-5336-11e6-9dd7-2e64c6eaa15b.gif)

I know there have been a few fork and edit issues that are now closed, like [this](https://github.com/plotly/streambed/issues/6625) one and [this](https://github.com/plotly/streambed/issues/6774), but could it be related? 

cc: @cldougl

**Comment by cldougl** [comment]
Fixed in https://github.com/plotly/plotly.github.io
