### ISSUE TITLE
Update IRkernel installation instruction for using Jupyter notebook in R

### ISSUE THREAD

**Issue by pravj** [plotly/documentation#498]
For the tutorial [Plotly charts in Jupyter notebooks using R](https://plot.ly/r/using-r-in-jupyter-notebooks/#install-irkernel), the instructions to install IRkernel are outdated.

According to the IRkernel repository's [README file](https://github.com/IRkernel/IRkernel#installation), it should be as follows:

```R
install.packages(c('repr', 'IRdisplay', 'pbdZMQ', 'devtools'))
devtools::install_github('IRkernel/IRkernel')
IRkernel::installspec()
```

The current instructions fail because of a package `rzmq`, which is [no more being used in the IRkernel](https://github.com/IRkernel/IRkernel/commit/fb4cefabc67e068c18036c12a17644fb9899a98b).

cc @cldougl @dikshagabha

**Comment by cldougl** [comment]
good catch @pravj - want me to show you how to update the R docs?

**Comment by pravj** [comment]
@cldougl, you have already explained it to me, probably I was among the very first users of the guide you have created. :smile: 

But, I can see that we don't actually have any `Rmd` file for this particular tutorial. There is just a [HTML](https://github.com/plotly/documentation/blob/source-design-merge/_posts/r/jupyter/2016-02-20-jupyter-notebook-r.html) file.

Do I need to edit this plain HTML?

**Comment by cldougl** [comment]
@pravj Yep - if it's just an HTML you will edit that. Feel free to let me know if you need help with that!
