### ISSUE TITLE
Looks like our docs pages don't get along with IE11

### ISSUE THREAD

**Issue by etpinard** [plotly/documentation#502]
See http://community.plot.ly/t/plotly-chart-image-export-issue/1792/4

**Comment by cldougl** [comment]
@aulneau

**Comment by aulneau** [comment]
@cldougl on it. Thanks for the alert!

**Comment by cldougl** [comment]
@aulneau these still look pretty broken - do you have any ideas on how to fix the docs for ie 11?

**Comment by cldougl** [comment]
@aulneau any update with this?

**Comment by cldougl** [comment]
@aulneau did you get a chance to take a look at this?

**Comment by bcdunbar** [comment]
fixed in https://github.com/plotly/documentation/commit/e7b539c7dff7dbc60b6d1b954077916f9ac7d7e8
