### ISSUE TITLE
Add python 3d axes doc

### ISSUE THREAD

**Issue by cldougl** [plotly/documentation#509]
Add 3d layout options (emphasizing scene option) 

same as https://plot.ly/javascript/3d-axes/ but for python 🐍

**Comment by dikshagabha** [comment]
@cldougl 
 Please Review
 https://plot.ly/python/3d-axes/

**Comment by cldougl** [comment]
@dikshagabha nice!
I would capitalize the title: Range of axes -> Range of Axes
other than that, looks great!!

**Comment by dikshagabha** [comment]
:+1:
