### ISSUE TITLE
`Making all Plots Private` Tutorial is Broken in Python 3

### ISSUE THREAD

**Issue by Kully** [plotly/documentation#522]
[This tutorial](https://plot.ly/python/privacy/#making-all-of-your-plotly-plots-private) does not appear to be working in Python 3. A user tried the script in Python 3 and ended up with an error:

```
TypeError: the JSON object must be str, not 'bytes'
```

cc @cldougl

**Comment by cldougl** [comment]
closing in favor of https://github.com/plotly/documentation/issues/948
