### ISSUE TITLE
What do *src options do?

### ISSUE THREAD

**Issue by dandv** [plotly/documentation#544]
https://plot.ly/javascript/reference/#scatter-xsrc is empty, as well as ysrc, ticktextsrc, tickvalssrc, symbolsrc etc.

Related: #484

**Comment by zbjornson** [comment]
(+1) These are in the python docs, and I assume have the same effect in JS.

https://plot.ly/python/reference/#mesh3d-colorbar-tickvalssrc
https://plot.ly/python/reference/#scatterternary-marker-colorbar-ticktextsrc
https://plot.ly/python/reference/#pointcloud-xsrc

**Comment by cldougl** [comment]
src options removed from reference pages
