### ISSUE TITLE
How do I create a *scatter* plot?

### ISSUE THREAD

**Issue by dandv** [plotly/documentation#545]
Not with lines between the points; just points, like a proper [scatter plot](https://plot.ly/javascript/reference/#scatter).

The default `type: scatter` traces lines, which I find counter-intuitive. I couldn't find how to disable the line at https://plot.ly/javascript/reference/#scatter.

**Comment by cldougl** [comment]
https://plot.ly/javascript/line-and-scatter/ and https://plot.ly/javascript/reference/#scatter-mode should help you out. In the future, we're happy to answer questions like this in our [community forum](http://community.plot.ly/).

**Comment by dandv** [comment]
Thanks.

PS: great to see the forum is using [a forum software I've contributed quite a it to](https://meta.discourse.org/users/dandv/summary).
