### ISSUE TITLE
Update pages to new layout

### ISSUE THREAD

**Issue by bcdunbar** [plotly/documentation#568]
Python tutorials that need layout updated:
- [x] apache-spark
- [x] redshift
- [x] sqlite
- [x] salesforce
- [x] MySQL

**Comment by bcdunbar** [comment]
@cldougl layout is user-guide https://github.com/plotly/documentation/blob/source-design-merge/_posts/tutorials/2015-06-30-apachespark.html Do the html and ipynb files need to be moved to **_posts/python**. Same for the other examples (redshift etc.).

**Comment by cldougl** [comment]
@bcdunbar this was a weird issue, they actually weren't getting updated properly because the permalinks were missing the trailing slash.
