### ISSUE TITLE
Update text & annotations doc

### ISSUE THREAD

**Issue by Kully** [plotly/documentation#569]
- [x] Reorder examples: text mode / styling text / hover / annotations
- [x] update text mode example
- [x] styling text (re-do example with simpler data.)
- [x] hovermode examples
- [x] Add example about coloring annotations: The [font color](https://plot.ly/r/reference/#layout-annotations-font) attribute should be included

**Comment by cldougl** [comment]
all done: https://plot.ly/r/text-and-annotations/
