### ISSUE TITLE
plotlyjs event page

### ISSUE THREAD

**Issue by cldougl** [plotly/documentation#571]
https://plot.ly/javascript/plotlyjs-events/ page with list and examples for all plotlyjs events:
- [x] `plotly_hover` (more examples: https://plot.ly/javascript/hover-events/)
- [x] `plotly_unhover` 
- [x] `plotly_click` (more examples https://plot.ly/javascript/click-events/)
- [x] `plotly_clickannotations`
- [x] `plotly_doubleclick`
- [x] `plotly_relayout` (more examples: https://plot.ly/javascript/zoom-events/)
- [x] `plotly_restyle`
- [x] `plotly_redraw`
- [x] `plotly_beforeplot`
- [x] `plotly_afterplot`
- [x] `plotly_autosize`
- [x] `plotly_framework`
- [x] `plotly_selected` (more examples: https://plot.ly/javascript/lasso-selection/)
- [x] `plotly_deselect`
- [x] `plotly_selecting`

style similar to https://plot.ly/javascript/plotlyjs-function-reference/ and include link in sidebar on https://plot.ly/javascript/

**Comment by bcdunbar** [comment]
event descriptions:

**plotly_hover** - occurs when mouse is over a select point, returning the following points:
**plotly_unhover** - will be emitted on mouse out, removing hover effects
**plotly_beforehover** - will be emitted on mouse out, removing hover effects
**plotly_click** - occurs when mouse is clicked, like plotly_hover it will return the following points:
	     - There is a slight difference between 2D, 3D (z), and geo (lat, lon, location) plots
**plotly_doubleclick** - restores the plot. That is, when a user preforms pan/zoom a plotly_doubleclick can be called to reset plot values.
**plotly_clickannotations** - an extension of plotly_click, clickannotations attaches annotated text to daat points.
**plotly_restyle** - is an efficient means of chaning parameters in the data array.
**plotly_relayout** - is an efficient means of updating just the layout in a graphDiv.
**plotly_redraw** - will force a full recalculation and redraw of the plot.
**plotly_autosize** - automatically sets the plot layout size.
**plotly_selecting** - occurs when the user preforms a click-and-drag lasso or zoom.
**plotly_selected** - can be used to return information about data points inside a selection box (box or lasso)
**plotly_deselect** - can be used to to return to previous data by emitting a doubleclick.

Not entirely sure about these ones or what they're returning:

**plotly_framework** - ?
**plotly_beforeplot** - ?
**plotly_afterplot** - ?
**plotly_transitioned** - ?
**plotly_transitioning** - ?
**plotly_update** - ?
**plotly_animating & plotly_animated** - These combine to queue succesive animations (transitions and frames).
**plotly_animatingframe** - ?

**Comment by cldougl** [comment]
https://plot.ly/javascript/plotlyjs-events/
