### ISSUE TITLE
Sitemaps are outdated

### ISSUE THREAD

**Issue by chriddyp** [plotly/documentation#575]
The sitemaps for this repo look outdated for some reason: http://help.plot.ly/documentation/sitemap.xml

See http://help.plot.ly/sitemap for an example sitemap. I think it is as easy as adding `jekyll-sitemap` to the gems like in here: https://github.com/plotly/plotly.github.io/blob/master/Gemfile#L10

Very important for these to be updated!

cc @cldougl

**Comment by cldougl** [comment]
added _site/sitemap.xml : https://github.com/plotly/documentation/commit/5c34f0021679dab860162a9ab42bd26f002f770c
