### ISSUE TITLE
Treemap example's labels seem buggy

### ISSUE THREAD

**Issue by ryan-williams** [plotly/documentation#599]
from the [nested treemaps example](https://plot.ly/matlab/treemap/#nested-treemaps):

![](https://cl.ly/11461J171l2Z/Screen%20Recording%202016-11-19%20at%2010.10%20AM.gif)

labels jumping around well above and below what my cursor is actually over

**Comment by cldougl** [comment]
Hi @ryan-williams 
You can try applying the [`hovermode` attribute](https://plot.ly/matlab/reference/#layout-hovermode) to your code to better control how/when the hovertext is displayed.
For this chart, I would recommend setting hovermode to closest. You can also do this by selecting the 'Show closest data..' button in our modebar: 
![screen shot 2016-11-21 at 11 40 19 am](https://cloud.githubusercontent.com/assets/2789078/20491642/050bca2a-afe0-11e6-8d1e-3602d9b7c7fd.png)

Please note that Treemaps are not a native plotly.js chart type at the moment, so we don't have predetermined hovermode specific to this chart type/use case.

**Comment by ryan-williams** [comment]
Thanks for the info, though I wonder if you misunderstood that this "broken" example is from [plot.ly's docs](https://plot.ly/matlab/treemap/#nested-treemaps); it's not my code.

**Comment by cldougl** [comment]
Nope I didn't misunderstand. I was trying to provide you with information to apply to your code.

**Comment by cldougl** [comment]
`hovermode` updated on example

**Comment by ryan-williams** [comment]
looks good, thanks!
