### ISSUE TITLE
Issues with plot | Line Charts in Matplotlib doc page

### ISSUE THREAD

**Issue by etpinard** [plotly/documentation#60]
https://plot.ly/matplotlib/plot/

@chriddyp @theengineear 
- The url is ridiculous
- Looks like something is up with converting `.set_dashes`.

![image](https://cloud.githubusercontent.com/assets/6675409/6153967/3b9cb412-b1f6-11e4-950a-498c068c6622.png)

LHS figure: mpl version, RHS figure: the figure on https://plot.ly/matplotlib/plot/

**Comment by theengineear** [comment]
I don't think set dashes has *ever* worked.

Why is the url ridiculous? matplotlib's main plotting function is 'plot'. It's a lot of 'plot' in the url, but i'm not sure it's unwarranted.
