### ISSUE TITLE
Add subplot example with annotations

### ISSUE THREAD

**Issue by Kully** [plotly/documentation#602]
- [x] https://plot.ly/python/text-and-annotations/ - @Kully 
- [x] https://plot.ly/r/text-and-annotations/ @bcdunbar 
- [x] https://plot.ly/javascript/text-and-annotations/ @bcdunbar

**Comment by bcdunbar** [comment]
R subplot with annotations is completed.

**Comment by Kully** [comment]
@cldougl Since it's not done, should I replace all the individual html files with a notebook, if it's gonna happen eventually?

**Comment by cldougl** [comment]
yes-that has been logged here https://github.com/plotly/documentation/issues/674

**Comment by Kully** [comment]
> yes-that has been logged here #674

I'm retracting my :+1 (😄 ) because isn't that issue related to the subplots doc and not the text-and-annotation one?

I just want to be clear: should I make a notebook for the text-annotations doc page in the same PR? Is there another PR opened for that too?

**Comment by cldougl** [comment]
you're right- they both should be notebooks

**Comment by Kully** [comment]
okay, so I'll deal with the notebook in the same PR that deals with _this current_ issue
