### ISSUE TITLE
`title` for Numpy docs should just be `Numpy Reference` instead of `Numpy Graphing Library | Plotly`

### ISSUE THREAD

**Issue by chriddyp** [plotly/documentation#604]
![image](https://cloud.githubusercontent.com/assets/1280389/20610722/8e694f26-b26b-11e6-9ec9-b65143f97823.png)
 
cc @cldougl @Kully

**Comment by chriddyp** [comment]
And we should create a more descriptive description like:
```
Numpy reference, examples, and documentation. Numpy is Python's core library for scientific computing and vector computations.
```

**Comment by chriddyp** [comment]
Same thing here:
![image](https://cloud.githubusercontent.com/assets/1280389/20610732/db9cab9e-b26b-11e6-96d1-ec8435c3332f.png)

**Comment by chriddyp** [comment]
And the `title`s for the individual pages should be
`Numpy Max` instead of `Max | plotly`
![image](https://cloud.githubusercontent.com/assets/1280389/20610747/0ac1041a-b26c-11e6-900b-cf1b9a6acbe6.png)

**Comment by chriddyp** [comment]
Can we also call `help(numpy.max)` (or w/e function we're documenting) as the last cell of every page? I think it's pretty helpful to show users how they can view the docs without even leaving the command line.

**Comment by Kully** [comment]
> Can we also call help(numpy.max) (or w/e function that is being documented on that page) as the last cell of every page? I think it's pretty helpful to show users how they can view the docs without even leaving the command line.

Good idea!

**Comment by Kully** [comment]
- []
