### ISSUE TITLE
plotly.js: losing context in api when scrolling

### ISSUE THREAD

**Issue by mg1075** [plotly/documentation#616]
When going through the api, 
it is easy to lose context when looking at child properties of an api item.

https://plot.ly/javascript/reference/

Compare this with, e.g., the highcharts api, where a fixed side menu
lets you know what section of the api you are looking at.

http://api.highcharts.com/highcharts/chart 

With the plotly site, once you hit a parent api item, and then scroll
down through the children of the api item, you are not able to tell 
anymore what parent item of the api you are examining.

**Comment by cldougl** [comment]
see https://github.com/plotly/documentation/issues/455
