### ISSUE TITLE
the great migration

### ISSUE THREAD

**Issue by chriddyp** [plotly/documentation#62]
from @jackparmer , https://github.com/chriddyp/chriddyp.github.io/issues/12#issue-74188946

We're moving https://plot.ly/api/ and its subpages to GitHub pages! No more waiting for streambed test to pass after fixing an API docs, instant API example addition and updating!

Here's a list of things for to get this started:

- [x] @chriddyp , add @NicoleGrondin to this repo!

@NicoleGrondin, some similar css/styling work to help.plot.ly:

- [x] Make http://chriddyp.github.io/python and its subpages look like https://plot.ly/python/ in style. Don't add any new pages that don't exist yet (like the "Reference", "User guide", etc).

- [x] Same with the other languages linked here: http://chriddyp.github.io

- [x] Make http://chriddyp.github.io look like https://plot.ly/api/, with a few tweaks (below!)

- [x] Little reorganization of banner image and adding language icons:
![image](https://cloud.githubusercontent.com/assets/1865834/7528965/06e7bd38-f4ff-11e4-9e33-034e13871b94.png)

- [x] Second half:
![image](https://cloud.githubusercontent.com/assets/1865834/7528973/259f25ae-f4ff-11e4-9067-54b3478116d6.png)

- [x] Add logos to the figure converter blurbs - folks usually pass right by them:

![image](https://cloud.githubusercontent.com/assets/1865834/7528979/455e8a88-f4ff-11e4-8364-c1b3f1128828.png)

![image](https://cloud.githubusercontent.com/assets/1865834/7528982/509a7eb6-f4ff-11e4-9bcc-b0435abc5858.png)

http://i.imgur.com/ZJWcTD9.png
http://www.scipy.org/_static/images/matplotlib_med.png

- [x] Make a top bar nav for subpages like: http://chriddyp.github.io/python/time-series/
That points to Python, MATLAB, and R equivalent pages. 
Rethinkdb has a cool one we can model after:
http://rethinkdb.com/docs/secondary-indexes/python/
![image](https://cloud.githubusercontent.com/assets/1865834/7529075/c262d268-f500-11e4-9fb7-b2f557fdafd9.png)

cc @aneda , @mariahhamel

**Comment by jackparmer** [comment]
![image](https://cloud.githubusercontent.com/assets/1865834/7540297/483c0e20-f57b-11e4-8041-801c083fc3e6.png)

**Comment by theengineear** [comment]
yay!!!

**Comment by chriddyp** [comment]
@NicoleGrondin - FYI some things to know to get started, ping me if you have any questions!

- The new documentation structure is on the branch `gh-pages`: https://github.com/plotly/documentation/tree/gh-pages. The `master` branch contains the old documentation, and we'll eventually delete the contents of the branch. Since this repo isn't named `plotly.github.io`, it serves the pages from the `gh-pages` branch.

- Since this repo isn't named `plotly.github.io`, github pages adds the url term `documentation`. Since our `plotly.github.io` has the CNAME `help.plot.ly`, that means that these pages are under `help.plot.ly/documentation`. We'll do some things later to get these into the existing `plot.ly/python`

- Since I moved these from `chriddyp.github.io`, the links are unaware of the `/documention` URL prefix. To make the links aware of this, add a `baseurl` parameter to `_config.yml`, e.g.: https://github.com/chriddyp/external-source-plotter/blob/gh-pages/_config.yml. Then, inside the HTML pages, template it in that `site.baseurl`, e.g. https://github.com/chriddyp/external-source-plotter/blob/gh-pages/index.html#L9.

- There are hundreds of examples in this branch, and as such it takes jekyll a while (30-60 seconds) to compile the new pages when changes are made. I recommend developing on a separate branch locally with most of the examples removed, just so you can iterate quickly when you make changes. Let me know if you need any help with this! Here's instructions for running locally: http://jekyllrb.com/docs/quickstart/

A few notes on structure:
- Each folder represents a page and contains the set of examples. For example, this folder https://github.com/plotly/documentation/tree/gh-pages/_posts/python/axes contains all of the examples on this page: https://plot.ly/python/axes/
- Inside each folder is an `...index.html` file, e.g. https://github.com/plotly/documentation/blob/gh-pages/_posts/python/axes/2015-04-09-axes_python_index.html. This file contains some templating magic to grab all of the other examples in the folder, and automatically template them into a two column layout. It knows which set of examples to grab from the `front-matter` parameter `suite`: https://github.com/plotly/documentation/blob/gh-pages/_posts/python/axes/2015-04-09-axes-labels.html#L5.
- These `...index.html` files allow us to easily template it in the standard two-column examples (code of the left, graph on the right) and/or insert any other non-standard HTML that we want for that page, e.g. like this example: https://plot.ly/python/file-options/
- Each language splash page, e.g. `/python` has it's own templated `language-index.html`, e.g. https://github.com/plotly/documentation/blob/gh-pages/_posts/2015-04-05-python-index.html. These are also super templated in order to grab the thumbnails and page links automatically as we add new examples
- The `_sass` folder contains a bunch of stuff from `materialize.scss` that I used just to get started - let's :boom: that and re-use some of the stuff you created with the help docs

**Comment by jackparmer** [comment]
Here's what I see to wrap up the new API pages on GitHub pages. They're looking super great @NicoleGrondin !

This is going live on Tuesday! https://plot.ly/api/ , https://plot.ly/python/ will be served from GitHub pages, no longer Plotly's streambed repo!

cc @scjody @chriddyp 

- [ ] Typo here. Also change left margin, font weight, and font size to more closely match nav. bar here:
https://plot.ly/javascript-graphing-library/
![image](https://cloud.githubusercontent.com/assets/1865834/7785655/8ff277d4-0167-11e5-92f1-efea5a1b44a0.png)

![image](https://cloud.githubusercontent.com/assets/1865834/7785657/990f86f4-0167-11e5-9e19-0cb161028b5b.png)

- [ ] Need to set background color to whitesmoke like plot.ly/python/* pages. Need to bring a JS code syntax highlighter that has support for R, Python, MATLAB, Julia, etc:
![image](https://cloud.githubusercontent.com/assets/1865834/7785658/bc239a04-0167-11e5-9954-0d7ac0e47873.png)

- [ ] Getting Started and IPython notebook pages don't seem to exist yet, getting 404's on them. Same for MATLAB.
![image](https://cloud.githubusercontent.com/assets/1865834/7785661/dc791630-0167-11e5-8bc3-3d599b486ddd.png)

- [ ] Its really important that the R, Python, and MATLAB logos are above the folk on a 13" screen. Let's do what the enterprise pages do and bring the full bleed splash photo all the way up through the toolbar and reduce the splash image height:

![image](https://cloud.githubusercontent.com/assets/1865834/7785662/262182fe-0168-11e5-82ed-487984d36c12.png)

- [ ] The Python / R / MATLAB logos should link to the getting started pages for the python, R, and MATLAB clients and have the same hover effect as the links at the bottom of:
http://help.plot.ly/
The text on hover should just be "Plotly Python API", "Plotly MATLAB API", etc....

**Comment by chriddyp** [comment]
- [ ] Need to add `BASE_URL` to the `_config.yml` url and set it equal to `https://plot.ly` and do a massive find-and-replace to replace all `{{BASE_URL}}` with `{{site.BASE_URL}}` (e.g. here: https://github.com/plotly/documentation/blob/gh-pages/_posts/matlab/3d-surface/2015-04-09-elevations-3d-surface.html#L8-L9)

**Comment by chriddyp** [comment]
- [ ] update plotly.js urls from `/plotly_js/` to `/javascript-graphing-library/`

**Comment by chriddyp** [comment]
Looking so good!

Non-blocking issues:
- [ ] Add a "Next, view examples" link or button at the bottom of each `getting-started` page (e.g. https://plot.ly/python/getting-started) that links them to the main doc page (e.g. https://plot.ly/python)

**Comment by mariahhamel** [comment]
My screen doesn't show the logos:

![screen shot 2015-05-27 at 1 09 40 pm](https://cloud.githubusercontent.com/assets/5942601/7842538/b7e471b8-0471-11e5-9369-a27b0cdcbbbc.png)

I do have headers and footers, but would guess this is somewhat standard for users.

**Comment by mariahhamel** [comment]
syntax highlighting isn't quite right in MATLAB. 

Image from github pages:

![screen shot 2015-05-27 at 1 34 50 pm](https://cloud.githubusercontent.com/assets/5942601/7843078/53a0b06e-0475-11e5-80e9-15b55cde4475.png)

Image from old docs: 

![screen shot 2015-05-27 at 1 35 00 pm](https://cloud.githubusercontent.com/assets/5942601/7843083/5da7f1c6-0475-11e5-9a84-1e2950128b8b.png)

Syntax highlighting for Python also isn't quite right (for example nothing is highlighted in: import plotly.plotly as py)

R syntax highlighting is also different from old docs.

**Comment by NicoleGrondin** [comment]
@chriddyp fyi part of your comment disappeared when I clicked on it
apologies for annoying-ness

**Comment by chriddyp** [comment]
haha no worries. i think the issues were blocking:

- [ ] /python/reference - need to either migrate that or figure out how to serve it from nginx - I can take that
- [ ] /matlab/user-guide/, /r/user-guide/, /python/user-guide/ (and all of it's chapters) - similar story: need to see if we can migrate it (with the body.html files in here: https://github.com/plotly/MATLAB-User-Guide/tree/master/converted (matlab streaming and matlab user guide), https://github.com/plotly/R-User-Guide/blob/master/published/includes/user-guide/body.html (R user-guide), throughout here: https://github.com/plotly/python-user-guide/tree/master/published/includes
