### ISSUE TITLE
python animation doc improvements

### ISSUE THREAD

**Issue by cldougl** [plotly/documentation#640]
https://plot.ly/python/intro-to-animations/
- [x] upgrade command should be in `code text`: 
<img width="461" alt="screen shot 2017-01-09 at 4 48 25 pm" src="https://cloud.githubusercontent.com/assets/2789078/21784947/9a3e8fca-d68b-11e6-9b71-70ffc7d714f1.png">

- [x] there are offline and online examples on this page: 
<img width="789" alt="screen shot 2017-01-09 at 4 48 46 pm" src="https://cloud.githubusercontent.com/assets/2789078/21784965/ae4385e8-d68b-11e6-8cbf-50d7d4cde4cd.png">

- [x] you can see more examples should be a bit more descriptive .. 'You can see more examples of using Plotly's REST API ..'
<img width="322" alt="screen shot 2017-01-09 at 4 51 49 pm" src="https://cloud.githubusercontent.com/assets/2789078/21785059/0342e1d8-d68c-11e6-97b2-4b0bdcfcbf0d.png">

- [x] add reference section pointing to helpful links (https://plot.ly/python/reference/#layout-sliders / https://plot.ly/python/reference/#layout-updatemenus etc)

- [x] add notebook link

**Comment by Kully** [comment]
@cldougl For the 2nd checkbox, do you just want me to add offline/online examples when they don't exist in a doc?

**Comment by cldougl** [comment]
@Kully that point is referring to the image beneath it where in the Version Check it says: Please note that all of these examples are using Python Offline -- that's not true, there are online and offline examples on that page so that line can be removed or edited.

**Comment by Kully** [comment]
Got it thanks!

**Comment by Kully** [comment]
> Python Offline

Should it be `Python Offline` or `Plotly Offline`?

**Comment by cldougl** [comment]
@Kully it should be removed. Is it mentioned somewhere else?

**Comment by Kully** [comment]
> Is it mentioned somewhere else?

No it wasn't.

**Comment by Kully** [comment]
Solved via PR: https://github.com/plotly/documentation/pull/651
