### ISSUE TITLE
MATLAB: How to add hover text to a plotly fig made with fig2plotly()

### ISSUE THREAD

**Issue by jackparmer** [plotly/documentation#65]
MATLAB calls their native version of this feature "data cursor" - we should try to cozy up to them for this in Google search:
http://se.mathworks.com/help/matlab/creating_plots/data-cursor-displaying-data-values-interactively.html

**Comment by tarzzz** [comment]
Added here:
https://plot.ly/matlab/text-and-annotations/#matlab-enable-data-cursor
