### ISSUE TITLE
pandas.io.data module has moved - change docs with this import

### ISSUE THREAD

**Issue by Kully** [plotly/documentation#657]
We need to replace `import pandas.io.data as web` with  `import pandas_datareader.data as web` in import sections when used. Importing the former gives the following warning/error message:

```
ImportError: The pandas.io.data module is moved to a separate package (pandas-datareader). After installing the pandas-datareader package (https://github.com/pandas-dev/pandas-datareader), you can change the import ``from pandas.io import data, wb`` to ``from pandas_datareader import data, wb``.
```

An example is found in this [Table Example](https://plot.ly/python/table/#include-and-index-column) which I should be getting replaced by another PR.

**Comment by cldougl** [comment]
closing in favour of https://github.com/plotly/documentation/issues/661
