### ISSUE TITLE
Rewrite `import FigureFactory` imports for 2.0.0. changes

### ISSUE THREAD

**Issue by Kully** [plotly/documentation#661]
The specific task is to change
`from plotly.tools import FigureFactory as FF`
to
`import plotly.figure_factory as ff`
in the docs

**Comment by Kully** [comment]
NB: Also want to replace `import pandas.io.data as web` for `import pandas_datareader.data as web` on the doc pages that also have the FigureFactory call.

**Comment by cldougl** [comment]
done.
