### ISSUE TITLE
update layout for pandas mult axis and subplot docs

### ISSUE THREAD

**Issue by cldougl** [plotly/documentation#691]
![screen shot 2017-02-15 at 2 48 56 pm](https://cloud.githubusercontent.com/assets/2789078/22992503/dea0669c-f38d-11e6-8d0f-71421095ffeb.png)
 - Update section to `multiple_axes`
 - fix title for mult. axes and subplots

**Comment by bcdunbar** [comment]
@cldougl these are fixed but https://plot.ly/pandas/multiple-axes and https://plot.ly/pandas/subplots are using the older layout.

**Comment by cldougl** [comment]
@bcdunbar great - I'll update those now
