### ISSUE TITLE
Document 3D showspikes, spikeside and contours.?.highlight

### ISSUE THREAD

**Issue by etpinard** [plotly/documentation#702]
See https://github.com/plotly/plotly.js/issues/1406 for more info.

The booleans `scene.?axis.showspikes`, `scene.?axis.spikesides` and `contours.?.highlight` (contour traces only) all impact the behavior on hover for 3D graphs in _slightly_ different ways - which can easily be confusing.

**Comment by cldougl** [comment]
- [ ] python
- [ ] r
- [ ] javascript

**Comment by michaelbabyn** [comment]
@cldougl , I'm thinking of putting this tutorial in `/language/layout/3d-hover-options`. Does that make sense to you?

**Comment by cldougl** [comment]
@michaelbabyn that's perfect -- I'd suggest making the the url something like : https://plot.ly/python/3d-hover/

**Comment by michaelbabyn** [comment]
closed by #1128
