### ISSUE TITLE
parcoord pandas docs

### ISSUE THREAD

**Issue by cldougl** [plotly/documentation#707]
add to statistical section
- [x] plot.ly/javascript/parallel-coordinates-plot
- [x] plot.ly/python/parallel-coordinates-plot
- [x] plot.ly/r/parallel-coordinates-plot
- [x] plot.ly/pandas/parallel-coordinates-plot

some info on parcoords: https://en.wikipedia.org/wiki/Parallel_coordinates
a js example: http://codepen.io/monfera/pen/dNBwOv (needs to be simplified slightly)

**Comment by jackparmer** [comment]
Let's use these links instead:

python/parallel-coordinates-plot
r/parallel-coordinates-plot
javascript/parallel-coordinates-plot

They're more descriptive so we'll be more likely to rank in Google search.

Someone should eventually do a MATLAB one as well:

matlab/parallel-coordinates-plot

**Comment by monfera** [comment]
Perhaps the [doc body](https://plot.ly/javascript/reference/#parcoords) too could use a mention of `parallel coordinates` written out like this in full, as some users may search on the page for `parcoords` while some others, `parallel coordinates`.

**Comment by cldougl** [comment]
added https://plot.ly/pandas/parallel-coordinates-plot/ cc @chriddyp

**Comment by chriddyp** [comment]
thanks @cldougl !

**Comment by monfera** [comment]
Looks great!!!
