### ISSUE TITLE
Add native scrollable dropdown to Python

### ISSUE THREAD

**Issue by Kully** [plotly/documentation#708]
Re: https://github.com/plotly/plotly.js/releases/tag/v1.23.0

I suppose this involves adding something like `scrollable` to the [type param](https://github.com/plotly/documentation/issues/708) in `updatemenus`

**Comment by bcdunbar** [comment]
there is an example at the bottom of this notebook https://plot.ly/~jackp/17248/sliders-in-python/

**Comment by Kully** [comment]
Closing because `scrolling` is already added to long dropdowns

**Comment by cldougl** [comment]
scrolling is automatically applied when applicable. It's not an option/attribute: 
https://plot.ly/python/dropdowns/#scrollable-dropdown
