### ISSUE TITLE
r statistical chart type docs

### ISSUE THREAD

**Issue by cldougl** [plotly/documentation#713]
- [ ] 2D density (similar to: https://plot.ly/python/density-plots/#2d-histogram-contour-plot-with-histogram-subplots)
- [ ] treeplot (w/ igraph) (similar to: https://plot.ly/python/tree-plots/)
- [ ] cont error bars (similar to: https://plot.ly/python/continuous-error-bars/)

**Comment by priyatharsan** [comment]
closing this issue and moving the issue tasks to https://github.com/plotly/documentation/issues/968
