### ISSUE TITLE
Some 'Back' links from pages under the plotly.js doc root don't lead back

### ISSUE THREAD

**Issue by monfera** [plotly/documentation#727]
Pages whose Back buttons go somewhere unexpected, rather than the expected https://plot.ly/javascript :

- [x] https://plot.ly/javascript/plotlyjs-function-reference/
- [x] https://plot.ly/javascript/reference/

... maybe there are others, and perhaps the issue is present in some other docs (Python, R etc.), I haven't exhaustively tested

![image](https://cloud.githubusercontent.com/assets/1548516/24201310/f76adef8-0f0f-11e7-9061-d9b61f070d4f.png)

**Comment by cldougl** [comment]
- [x] same issue with https://plot.ly/--APIs--/reference/
