### ISSUE TITLE
4.7 new R package features

### ISSUE THREAD

**Issue by cpsievert** [plotly/documentation#741]
I'm planning on a new CRAN release in the next couple weeks. See here for all the new features -- https://github.com/ropensci/plotly/blob/master/NEWS.md

It'd be nice to have some fresh examples, especially for animation (see `help(animation)`), new ggplot2 geoms (see `help(geom_col)`, for example), using the `raster2uri()` function for images (see `help(raster2uri)`), and [anchoring multiple traces on a single legend entry](https://github.com/ropensci/plotly/commit/28a1215c22438ca9f9aa0de2f5725fab060b6f3b)

**Comment by cpsievert** [comment]
By the way, none of the linking/highlighting examples will work on https://plot.ly/. We still have to work out how to support that.

**Comment by bcdunbar** [comment]
- [ ] geom_quantile
- [ ] geom_col
- [ ] geom_spoke
- [ ] geom_rug
- [ ] geom_dotplot
- [ ] geom_crossbar
- [ ] raster2uri
- [ ] animation examples
- [ ] crosstalk examples (offline)

**Comment by bcdunbar** [comment]
**Tools for working with plotly's REST API (v2)**

- [ ] api_create() *remove plotly_POST from docs and replace with api_create*
- [ ] api_download_plot()
- [ ] api_download_grid()
- [ ] api()

**Comment by cpsievert** [comment]
FWIW, `plotly_POST()` should still work, so it's not *super* pressing to replace it in the docs (but we should eventually replace it)

**Comment by bcdunbar** [comment]
added to https://github.com/plotly/documentation/issues/968
