### ISSUE TITLE
aspect ratio docs and backlinks

### ISSUE THREAD

**Issue by chriddyp** [plotly/documentation#747]
From https://github.com/plotly/plotly.js/pull/1522

docs for:
- [x] r
- [x] python
- [x] javascript

After we have docs, we can close and comment on:
- [x] https://github.com/plotly/plotly.py/issues/70
- [x] https://community.plot.ly/t/aspect-ratio-plotly/3215
- [x] https://github.com/plotly/plotly.py/issues/285

cc @cldougl

**Comment by cldougl** [comment]
waiting for https://github.com/plotly/streambed/pull/9387
