### ISSUE TITLE
Copy to clipboard doesn't do anything

### ISSUE THREAD

**Issue by chriddyp** [plotly/documentation#751]
![copy-to-clipboard](https://cloud.githubusercontent.com/assets/1280389/25185770/3ec175cc-24ec-11e7-8c64-1b3aebe013f2.gif)

**Comment by cldougl** [comment]
@chriddyp what browser/version are you using because this works fine for me?

**Comment by chriddyp** [comment]
Chrome! although now it seems to be working? Perhaps flash was getting blocked or something. Sorry for the false alarm!
