### ISSUE TITLE
carpet plot documentation

### ISSUE THREAD

**Issue by cldougl** [plotly/documentation#754]
- [x] javascript 
  - [x] carpet (plot.ly/javascript/carpet-plots)
  - [x] scattercarpet (plot.ly/javascript/carpet-scatter)
  - [x] contourcarpet (plot.ly/javascript/carpet-contour)
- [x] python 
  - [x] carpet (plot.ly/python/carpet-plots)
  - [x] scattercarpet (plot.ly/python/carpet-scatter)
  - [x] contour carpet (plot.ly/python/carpet-contour)
- [x] r 
   - [x] carpet (plot.ly/r/carpet-plots)
   - [x] scattercarpet (plot.ly/r/carpet-scatter)
   - [x] contour carpet (plot.ly/r/carpet-contour)

**Comment by bcdunbar** [comment]
waiting on this  https://github.com/ropensci/plotly/issues/1021 for `scattercarpet` in R.
