### ISSUE TITLE
Change Layout Style of Figure Label Page

### ISSUE THREAD

**Issue by bcdunbar** [plotly/documentation#756]
need to change this https://plot.ly/r/figure-labels/ as it is the old style and has the incorrect $$ at the bottom.

**Comment by bcdunbar** [comment]
@cldougl were you updating styles the other day? I believe this is the only R doc with old style.

**Comment by cldougl** [comment]
yep the permalink was missing the trailing slash:
<img width="467" alt="screen shot 2017-06-19 at 10 02 54 am" src="https://user-images.githubusercontent.com/2789078/27289133-e0cb1412-54d6-11e7-92c5-491a17a96980.png">


all fixed now- thanks for pointing this out!!
