### ISSUE TITLE
matlab doc updates

### ISSUE THREAD

**Issue by cldougl** [plotly/documentation#772]
- [x] https://plot.ly/matlab/user-guide/
- [x] https://plot.ly/matlab/dropdowns/

**Comment by bcdunbar** [comment]
^ only found the 1.

Also, noticed that these are inactive / don't have links https://plot.ly/matlab/#streaming 

<img width="772" alt="2017-06-15 1" src="https://user-images.githubusercontent.com/8393928/27197225-7078bc62-51db-11e7-9a20-09e71c9694e1.png">

**Comment by cldougl** [comment]
thanks for checking those @bcdunbar
