### ISSUE TITLE
Codepens are clipped confusingly

### ISSUE THREAD

**Issue by alexcjohnson** [plotly/documentation#781]
Noticed this on a few of the examples in https://plot.ly/javascript/hover-events/ - some important elements are scrolled off of the codepen viewport, but the box it's in has whitespace at the bottom as if the codepen should have had a bigger viewport. For example the "Go" button is nowhere to be found initially:
![hidden go button](https://user-images.githubusercontent.com/2678795/27965843-12b750de-630b-11e7-8fe4-6b6c82a9cb44.gif)

cc @cldougl

**Comment by cldougl** [comment]
@alexcjohnson I've edited the embed size of those examples so they should be good now. Feel free to take a look to double check that you're not still seeing that issue

**Comment by alexcjohnson** [comment]
Looks great, thanks!
