### ISSUE TITLE
update https://plot.ly/matplotlib/time-series/

### ISSUE THREAD

**Issue by cldougl** [plotly/documentation#785]
- [x] make notebook
- [x] second example chart embed is incorrect

**Comment by bcdunbar** [comment]
I just updated the plots in the html files as no other matplotlib docs use ipynb, or did we want to start making notebooks for matplotlib docs?

**Comment by cldougl** [comment]
@bcdunbar yeah I wanted to start making these use ipynbs and add the intro cell

**Comment by bcdunbar** [comment]
no problems I'll make a notebook for this one now then and make another issue for converting matplotlib to ipynbs.

**Comment by bcdunbar** [comment]
issue for other matplotlib conversions https://github.com/plotly/documentation/issues/802
