### ISSUE TITLE
add Plotly.update example

### ISSUE THREAD

**Issue by cldougl** [plotly/documentation#794]
add example for `Plotly.update( )` to https://plot.ly/javascript/plotlyjs-function-reference/#plotlyupdate with a trace argument:  https://codepen.io/plotly/pen/PKGrem

**Comment by alexcjohnson** [comment]
Yes please! Also a couple of things I notice about this:
- we should not generally use nested objects in `Plotly.update` or `restyle` or `relayout` examples. So `var data_update = {marker: {color: 'red'}}` should be changed to `var data_update = {'marker.color': 'red'}` - I know this is explained, but the nested form will very often give people confusing results, and attribute strings are a plotly.js-specific thing people need to learn, so I'd say every example for `update`/`restyle`/`relayout` that's not explicitly talking about this issue should use the attribute string form.
  - when explaining this difference, we could be even clearer about the overwriting that will happen, with an example of deleting a previously-specified attribute (`{marker: {color: 'red'}}` deleting `marker.symbol` for example)
- with the traces argument, we should show that it can be either a number or an array, just as we do in the `restyle` docs.

**Comment by michaelbabyn** [comment]
closed by [1026](https://github.com/plotly/documentation/pull/1026/)
