### ISSUE TITLE
Aggregation transform docs

### ISSUE THREAD

**Issue by jackparmer** [plotly/documentation#804]
For R, Python and JavaScript: 

1. A simple example with a dropdown for each type of aggregation

2. A time series example with 2 dropdowns: One that chooses an interval (day, week, etc) and one that chooses a transform (sum, average, etc)

3. A global choropleth map example

Any other examples for the docs come to mind @rreusser @alexcjohnson ?

**Comment by bcdunbar** [comment]
JS:
- [x] simple dropdown
- [ ] time series
- [x] world choropleth
- [x] with table subplot

R:
- [x] simple dropdown
- [ ] time series
- [x] world choropleth 
- [x] with table subplot

Py:
- [ ] simple dropdown
- [ ] time series
- [ ] world choropleth 
- [ ] with table subplot

**Comment by jackparmer** [comment]
@bcdunbar Thanks for working on this. For the time series, binning is only supported in histograms at the moment. Here is an example:

https://plot.ly/dashboard/jackp:18052/present

It would be great to have this example as the times series example, with a dropdown for different binning intervals (1 day, 1 week, 1 month, 6 months, etc).

**Comment by bcdunbar** [comment]
@jackparmer brilliant! I was just thinking about what to do for time series.

**Comment by jackparmer** [comment]
@bcdunbar No problem. This feature is a bit confusing, but you can play around with the bin size settings in the workspace:

![image](https://user-images.githubusercontent.com/1865834/31840765-c8adf2b6-b5b4-11e7-8269-30a637eb58a5.png)

It would also be useful to have a 2nd time series example with a **second** dropdown that changes `histfunc`. The default is`COUNT`, but you can also bin by `SUM` or `AVG` of another column. The police shootings dataset doesn't have another meaningful numeric column to sum or average over, but this might work well with the gapminder dataset.
