### ISSUE TITLE
GitHub corner links should link to documentation page on GitHub

### ISSUE THREAD

**Issue by jackparmer** [plotly/documentation#805]
Currently, the GitHub link goes to the project repository root. It might make more sense at this point to link to the doc page on GitHub instead.

More community members might contribute to the ever-expanding docs if it were easier to go from the doc page to its source on GitHub.

**Comment by Kully** [comment]
@jackparmer I assume you are talking about this:
![screen shot 2017-09-12 at 2 50 27 pm](https://user-images.githubusercontent.com/10369095/30343002-c90ae6aa-97c9-11e7-80a6-96e4b75bc645.png)

I'm trying to understand the goal here. Is it to encourage folks to contribute to docs over the actual source code of charts, etc _or_ is an observation that more people want to edit the documentation and not the chart code?

**Comment by jackparmer** [comment]
yeah, it's to encourage more community members to make updates to the docs themselves

**Comment by michaelbabyn** [comment]
@Kully  I've got a fix for this, do you mind if I take it?

**Comment by Kully** [comment]
@michaelbabyn go for it!
