### ISSUE TITLE
remove src attributes from reference pages

### ISSUE THREAD

**Issue by cldougl** [plotly/documentation#810]
remove src attributes from reference page

**Comment by etpinard** [comment]
To do so, I think should we should move the [parts](https://github.com/plotly/plotly.js/blob/00856ad4be7701c02efd7230707b59d1f5a8169e/src/plot_api/plot_schema.js#L355-L364) in plotly.js `PlotSchema` that adds those `*src` attribute to [`streambed`](https://github.com/plotly/streambed/blob/master/shelly/plotlyjs/static/plotlyjs/build.js

**Comment by etpinard** [comment]
That is, those `*src` attributes shouldn't be included in https://github.com/plotly/documentation/blob/source/_data/plotschema.json
