### ISSUE TITLE
Adding Sliders Animation Doc Page is 404ing Plots

### ISSUE THREAD

**Issue by Kully** [plotly/documentation#823]
Link to Doc Page: https://plot.ly/python/gapminder-example/

**Comment by cldougl** [comment]
@Kully this looks good now - reran the docs w/ the PythonPlotBot account

**Comment by Kully** [comment]
> @Kully this looks good now - reran the docs w/ the PythonPlotBot account

👍  👍  👍  👍  👍  👍  👍
