### ISSUE TITLE
display a gif that shows how you can interactive with a parallel coordinates plot

### ISSUE THREAD

**Issue by chriddyp** [plotly/documentation#824]
the interaction controls for a parallel coordinates are unlike the rest of our plots. and there are a lot of cool ways that you can interact with them!

could we add a GIF that shows how to interact with these plots after the first example on every parallel coordinates doc page? 
along with a subtitle like:
> Parallel coordinates are richly interactive by default. Drag the lines along the axes to filter regions and drag the axis names across the plot to rearrange variables.

cc @cldougl @Kully

**Comment by cldougl** [comment]
- [ ] https://plot.ly/python/parallel-coordinates-plot/
- [ ] https://plot.ly/pandas/parallel-coordinates-plot/
- [ ] https://plot.ly/r/parallel-coordinates-plot/
- [ ] https://plot.ly/javascript/parallel-coordinates-plot/
