### ISSUE TITLE
`editType` and `impliedEdits` not filtered from reference pages

### ISSUE THREAD

**Issue by rreusser** [plotly/documentation#832]
See:
- https://plot.ly/javascript/reference/#scatter-line-editType
- https://plot.ly/javascript/reference/#histogram-xbins-impliedEdits

This is likely a result of new things showing up in the schema from https://github.com/plotly/plotly.js/pull/1999. cc @alexcjohnson for a double-check on whether anything else may have snuck through.

**Comment by cldougl** [comment]
yep saw those today, planning to remove those with 
https://github.com/plotly/documentation/issues/810

**Comment by rreusser** [comment]
I think that's it. Just wanted to make sure. 👍

**Comment by alexcjohnson** [comment]
Yes, pretty sure it's only those two. Good catch both of you!
