### ISSUE TITLE
Add table docs 

### ISSUE THREAD

**Issue by bcdunbar** [plotly/documentation#833]
- [x] JS
- [x] Py https://plot.ly/python/table/
- [x] R

Py: https://plot.ly/~jackp/18023
R : https://moderndata.plot.ly/creating-interactive-svg-tables-in-r/

**Comment by cldougl** [comment]
started python here: https://plot.ly/python/table/ 
need more examples,
specifically: 
- [ ] changing size of rows/columns 
- [ ] table and chart subplot (more examples: https://github.com/plotly/documentation/issues/849)
- [ ] alternating row colors
- [ ] row colors based on variable

**Comment by bcdunbar** [comment]
I actually made a similar python one, I'll just bring across some examples and add these other ones.

JS is done but I'll add row colors based on variables. I've also made a Table Subplot doc https://github.com/plotly/documentation/issues/849 in JS 

R is done but only offline for now.

**Comment by bcdunbar** [comment]
R docs are offline so it is temp here https://rpubs.com/bcd/tables
