### ISSUE TITLE
HTML tables in docs need CSS styling

### ISSUE THREAD

**Issue by jackparmer** [plotly/documentation#851]
Our HTML table CSS styling needs to be fixed ASAP, it looks totally broken:

![image](https://user-images.githubusercontent.com/1865834/32296441-a4934c4c-bf22-11e7-8802-c260c663fa20.png)

https://plot.ly/python/aggregations/

I'd use the same styling we do in Jupyter notebooks:

![image](https://user-images.githubusercontent.com/1865834/32297261-ffde63c8-bf24-11e7-9060-c4b698d6c9bb.png)

https://plot.ly/~jackp/17966/import-plotlyplotly-as-py-import-plotly/

**Comment by cldougl** [comment]
https://github.com/plotly/documentation/commit/0786e286525fda9e4f397e103cfaaf05a88dd7d2 temporarily defaulting to html defaults to improve broken spacing look:

![screen shot 2017-11-02 at 12 55 51 pm](https://user-images.githubusercontent.com/2789078/32339132-2ecd8d82-bfcd-11e7-83fc-116412f58d0e.png)

will add styled table class in subsequent commit

**Comment by bcdunbar** [comment]
added new table in  https://github.com/plotly/documentation/commit/784ead0fe2f54ded34a9dbe361cf1702d375e2a1 and fixed rendered_html styles https://github.com/plotly/documentation/commit/694e25da53d45bcf9294ad8952e7568297b55d90
