### ISSUE TITLE
Python filter transform graph is blank

### ISSUE THREAD

**Issue by jackparmer** [plotly/documentation#852]
![image](https://user-images.githubusercontent.com/1865834/32303771-0e116118-bf41-11e7-98e9-c9cccb3c76da.png)

**Comment by jackparmer** [comment]
Same with "Multiple Transforms" doc

**Comment by cldougl** [comment]
Taking a look --
Looks like the new version of plotly.js isn't getting injected correctly when we deploy offline charts.

![screen shot 2017-11-02 at 10 22 34 am](https://user-images.githubusercontent.com/2789078/32330871-cd47792a-bfb7-11e7-8645-50cd2afb9aa5.png)

**Comment by bcdunbar** [comment]
oddly it worked for aggregation doc but not this rest.

**Comment by cldougl** [comment]
issue related to: http://requirejs.org/docs/errors.html#mismatch
Resolved now.
