### ISSUE TITLE
Python GroupBy graph is blank

### ISSUE THREAD

**Issue by jackparmer** [plotly/documentation#853]
![image](https://user-images.githubusercontent.com/1865834/32303792-39b743c8-bf41-11e7-8ec4-0371ac66b761.png)

**Comment by cldougl** [comment]
fixed in https://github.com/plotly/documentation/commit/ef64e4e9271af52283ba26bea64715e07c1194b8

**Comment by cldougl** [comment]
reopening as the solution broke search
also noting this is only affecting chrome (ff & safari are working as expected)
