### ISSUE TITLE
Examples in sidebar disabled when in 'More [Chart Type]'

### ISSUE THREAD

**Issue by bcdunbar** [plotly/documentation#854]
open https://plot.ly/python/subplot-charts/ and select any of the examples from the sidebar. Quick start still functions as expected.

**Comment by cldougl** [comment]
oh I see - the sidebar is being built like it's the index page (i.e. plot.ly/python)
we could a. remove those "Examples"
or b. replace them with the links on that page.

I think in this case we should remove them as replacing them with the links on that page would be pretty repetitive

**Comment by michaelbabyn** [comment]
closed by [#1025](https://github.com/plotly/documentation/pull/1025)
