### ISSUE TITLE
update breadcrumbs to include the more charts link 

### ISSUE THREAD

**Issue by cldougl** [plotly/documentation#855]
For Example:

![screen shot 2017-11-03 at 12 17 23 pm](https://user-images.githubusercontent.com/2789078/32384351-09a3392a-c091-11e7-8cbe-314e22c076b5.png)

API Libraries -> Python -> Basic Charts -> Scatter Plots

**Comment by cldougl** [comment]
@michaelbabyn do you want to take a crack at this one? You can let @bcdunbar and I know if you have any questions!

**Comment by michaelbabyn** [comment]
closed by [#997](https://github.com/plotly/documentation/pull/997)
