### ISSUE TITLE
histogram 2d contour doc

### ISSUE THREAD

**Issue by cldougl** [plotly/documentation#860]
Examples for: 
- [x] https://plot.ly/python/reference/#histogram2dcontour
- [x] https://plot.ly/javascript/reference/#histogram2dcontour
- [x] https://plot.ly/r/reference/#histogram2dcontour

**Comment by bcdunbar** [comment]
added in https://github.com/plotly/documentation/commit/c981d1a7340087ea0c0d9e9b7abdc14eb68441ab
