### ISSUE TITLE
update https://plot.ly/python/file-options/

### ISSUE THREAD

**Issue by cldougl** [plotly/documentation#862]
should include a description and be a ipynb (for search*)

**Comment by bcdunbar** [comment]
@cldougl for description do you mean a description tag (like, "How to update your graphs in Python with the fileopt parameter.") or an introduction section?

**Comment by bcdunbar** [comment]
updated in https://github.com/plotly/documentation/commit/49b0ae3bdfac04871d4bbc6b91e1ea6211bc563d

@cldougl Leaving issue open for now - what description did you want to add?

**Comment by cldougl** [comment]
@bcdunbar yep exactly like you said: https://github.com/plotly/documentation/issues/862#issuecomment-364609562

"How to update your graphs in Python with the fileopt parameter."
