### ISSUE TITLE
Python layout.images docs

### ISSUE THREAD

**Issue by jackparmer** [plotly/documentation#865]
Here are some ideas to make the image examples more useful, interesting, or inspiring: https://plot.ly/python/images/

1. For background image, maybe something like this instead of the python logo:
https://matplotlib.org/users/image_tutorial.html

![image](https://user-images.githubusercontent.com/1865834/33859585-9a62a192-dea2-11e7-9131-db4d017b73e0.png)

2. For the multiple images example, maybe chemical structures with spectroscopy data?

![image](https://user-images.githubusercontent.com/1865834/33859743-5844d3b0-dea3-11e7-898d-ecf1b4b13a17.png)

3. Heard of a few folks using image backgrounds with Datashader for plots with too much data to be interactive:

https://moderndata.plot.ly/visualize-100-million-points-with-datashader-and-plotly/

4. Might be fun to do something with facial recognition overlays and hover text:

![image](https://user-images.githubusercontent.com/1865834/33860333-5152528c-dea6-11e7-82d3-7237f6f97521.png)

**Comment by michaelbabyn** [comment]
closed by [1032](https://github.com/plotly/documentation/pull/1032)
