### ISSUE TITLE
Broken Python demo dataset link on 3D mesh page

### ISSUE THREAD

**Issue by zwm0426** [plotly/documentation#867]
Here is a broken dataset.txt link for Python demo in the page:
https://plot.ly/python/3d-mesh/#reference

It directs me to a page which is 404 not found now:
https://github.com/plotly/documentation/tree/source-design-merge/_posts/python/3d-mesh/dataset.txt

Actually, the correct page is (added "3d/"):
https://raw.githubusercontent.com/plotly/documentation/source-design-merge/_posts/python/3d/3d-mesh/dataset.txt

Please update the link, thank you.

**Comment by cldougl** [comment]
Thanks for reporting @zwm0426
