### ISSUE TITLE
Detecting when Plotly has finished

### ISSUE THREAD

**Issue by BruceSherwood** [plotly/documentation#874]
I needed a way to know when a Plotly call was completed but found nothing about this in the documentation. I finally found the information in a link to the Plotly js forum in 2015, “I want to show loading symbol while loading the graph”. This ought to be in the documentation.

**Comment by cldougl** [comment]
Hi there-
Thanks for your suggestion! `plotly_afterplot` is documented on our even handler page here: https://plot.ly/javascript/plotlyjs-events/#additional-events

Did you have a specific example in mind that would be helpful in addition to the afterplot handler?

**Comment by BruceSherwood** [comment]
I missed finding this in the documentation, which I now see was just my fault. However, the forum comment also mentions a particularly convenient form that I don't see in the documentation you've pointed me to, which is this: Plotly.plot(graphDiv, data, layout, config).then(postPlotHandler);

**Comment by cldougl** [comment]
Great, I've updated the afterplot section to include both options: https://plot.ly/javascript/plotlyjs-events/#afterplot-event
Typically we focus on documenting Plotly syntax (i.e. the afterplot handler opposed to non-Plotly specific javascript functions) but you can always make documentation requests here if you find something that you think will be helpful for other users!
