### ISSUE TITLE
florida county choropleth doc page is broken

### ISSUE THREAD

**Issue by Kully** [plotly/documentation#881]
URL: https://plot.ly/python/mapbox-county-choropleth/

First issue arrises with this line:
`florida_data = ast.literal_eval(florida_data)`

**Comment by cldougl** [comment]
@Kully was a cell removed from this notebook?

![screen shot 2018-03-08 at 1 55 39 pm](https://user-images.githubusercontent.com/2789078/37170304-7c66162c-22d8-11e8-86ae-c97d67e0483b.png)

**Comment by Kully** [comment]
> was a cell removed from this notebook?

I don't remember if I accidentally deleted one, but I do not think so.
