### ISSUE TITLE
Plot dosen't update when the browser isn't open

### ISSUE THREAD

**Issue by saulgold** [plotly/documentation#885]
I am sending data to a plotly plot through the Python API, but the online plot only updates when I have it open in the plotly dashboard. When I close the dashboard the plot resets until I open it again.

Is this a feature? I would like to plotly chart to be continually plotting in the background.

**Comment by cldougl** [comment]
Hi there,
This is Plotly's documentation api so issues here are reserved for issues in the documentation. If you have questions you can post in our community forum: https://community.plot.ly/
