### ISSUE TITLE
Plotly.react

### ISSUE THREAD

**Issue by alexcjohnson** [plotly/documentation#886]
`Plotly.react` should be described in https://plot.ly/javascript/plotlyjs-function-reference/

Key points:
- signature matches `Plotly.newPlot`
- describe [datarevision](https://github.com/plotly/plotly.js/blob/113b3618732f28d1a2158771544bf4e60e00c084/src/plots/layout_attributes.js#L186)
- same end results as `newPlot` with the speed of `restyle`/`relayout`

**Comment by nicolaskruchten** [comment]
https://plot.ly/javascript/plotlyjs-function-reference/#plotlyreact (grammar fixes to be deployed soon!)
