### ISSUE TITLE
attribute hash links are scrolled off-screen

### ISSUE THREAD

**Issue by alexcjohnson** [plotly/documentation#892]
For example, I wanted to point someone to the reference to parcoords.dimensions.tickformat at https://plot.ly/javascript/reference/#parcoords-dimensions-tickformat, but it's not visible when you visit that link - the top item you see is the "visible" attribute, which is next after tickformat. I guess it's scrolled under the floating header...
![screen shot 2018-03-11 at 7 40 35 pm](https://user-images.githubusercontent.com/2678795/37259995-5527c310-2564-11e8-83dc-0c1cde5b2910.png)

**Comment by nicolaskruchten** [comment]
Yeah this happens from the sidebar links and the search results too and
throws me off all the time :)

**Comment by nicolaskruchten** [comment]
Here are a couple of options for resolving this: https://stackoverflow.com/questions/10732690/offsetting-an-html-anchor-to-adjust-for-fixed-header

I'm happy to give it a try if that's the best way forward :)

**Comment by cldougl** [comment]
@nicolaskruchten we have a style read me here: https://github.com/plotly/documentation/blob/source-design-merge/style_README.md if you want to implement the offset

**Comment by alexcjohnson** [comment]
Beautiful, thanks @nicolaskruchten!
