### ISSUE TITLE
`carpet-plot` links at the bottom of the page don't go to the right places

### ISSUE THREAD

**Issue by chriddyp** [plotly/documentation#894]
![image](https://user-images.githubusercontent.com/1280389/37316595-6073476c-2636-11e8-907a-2188fe79e479.png)

- `Carpet Scatter Plots` goes to the R page instead of the python page
- `Carpet Contour Plots` goes to a page that doesn't exist

**Comment by bcdunbar** [comment]
fixed in https://github.com/plotly/documentation/commit/0691510baf97f7d84f41a0d592d1430489dadb99

**Comment by chriddyp** [comment]
thanks @bcdunbar !
