### ISSUE TITLE
use api_create instead of plotly_POST on R getting started page

### ISSUE THREAD

**Issue by cldougl** [plotly/documentation#900]
`plotly_POST` -> `api_create()`

![screen shot 2018-03-15 at 3 38 24 pm](https://user-images.githubusercontent.com/2789078/37487161-1c5c0efa-2867-11e8-8cc2-1dee9d49c6c9.png)

**Comment by bcdunbar** [comment]
this will be swept up with a bunch of `find ... sed`s in https://github.com/plotly/documentation/issues/898

**Comment by bcdunbar** [comment]
fixed in https://github.com/plotly/documentation/commit/2c3f6ab28be3e62bfbe0b9543de5a95901917a2d

FWIW, I used `find -type f -exec sed -i 's:plotly_POST:api_create:g' {} \;`
