### ISSUE TITLE
Is there a code formatting guide for plotly js sample?

### ISSUE THREAD

**Issue by Andries-Smit** [plotly/documentation#907]
There are various styles and mixed style of code in the samples. Is the formatting guide?
- indent 2 space, 4 spaces or tabs
- use of newline for open {? 
``` js
for ( var i = 0; i < 10; i++ ) {
  // code
}
```
or
``` js
for ( var i = 0; i < 10; i++ )
  {
    // code
  }
```

**Comment by cldougl** [comment]
Hi there,
We do not have a strict formatting guide at this time as both formats are acceptable.
