### ISSUE TITLE
specify auto_open = True

### ISSUE THREAD

**Issue by cldougl** [plotly/documentation#915]
**python**: typically our python docs use `py.iplot( )` to plot in a jupyter notebook, but we can add `auto_open=True` to our getting started page `py.plot()` calls emphasize that as an option.
https://plot.ly/python/getting-started/#start-plotting-online

**r**:  to not auto open:
```
> o <- options(browser = 'false')
> api_create(mtcars)
> options(o)
```
The way the docs are currently written don't include this option. We should at least include it on the getting started page: https://plot.ly/r/getting-started/#initialization-for-online-plotting. *This is important as this option is currently undocumented. 
We can discuss if this is needed on all pages- I'm leaning towards no as the current syntax suggests users set api_create as a variable which prevents the chart from being opened in the browser until that variable is explicitly called:

```
library(plotly)
p <- plot_ly(data = iris, x = ~Sepal.Length, y = ~Petal.Length)
# Create a shareable link to your chart
# Set up API credentials: https://plot.ly/r/getting-started
chart_link = api_create(p, filename="scatter-basic")
chart_link
```

**Comment by bcdunbar** [comment]
I've updated both the docs.

> I'm leaning towards no as the current syntax suggests users set api_create as a variable

Agreed. I think that current examples i.e. `chart_link = api_create(p, filename="scatter-basic")` works and providing the option in the getting started page will suffice.

**Comment by bcdunbar** [comment]
closing for now. 

@cldougl Unless you think that more needs done here?

**Comment by cldougl** [comment]
all set - thanks @bcdunbar !
