### ISSUE TITLE
Use `import plotly.graph_objs as go` everywhere

### ISSUE THREAD

**Issue by chriddyp** [plotly/documentation#917]
In https://plot.ly/python/scatterplot-matrix/ we have
```
from plotly.graph_objs import graph_objs
```
let's be consistent and use
```
import plotly.graph_objs as go
```
everywhere. 

This came up in this discussion here: https://github.com/plotly/plotly.py/pull/975#discussion_r178916894

**Comment by bcdunbar** [comment]
a quick grep search turned up these. If anyone comes across any others, feel free to add to the list.

- [ ] 3d-bubble.ipynb
- [ ] les-mis.ipynb
- [ ] 3d-surface.ipynb
- [ ] iso-surface.ipynb
- [ ] proj-on-to-a-plane.ipynb
- [ ] trisurf.ipynb
- [ ] triangulation.ipynb 
- [ ] basic/dot.ipynb
- [ ] basic/line-plots/lines.ipynb
- [ ] basic/pie-charts.ipynb
- [ ] databases/apachespark.ipynb
- [ ] databases/mysql.ipynb
- [ ] databases/redshift.ipynb
- [ ] databases/salesforce.ipynb
- [ ] databases/sqlite.ipynb
- [ ] fundamentals/config_opts.ipynb
- [ ] fundamentals/grid-api.ipynb
- [ ] fundamentals/fileopts-checkpoint.ipynb
- [ ] fundamentals/fileopts.ipynb
- [ ] fundamentals/jupyter-tutorial.ipynb
- [ ] fundamentals/privacy.ipynb
- [ ] fundamentals/getting-started.ipynb
- [ ] ipypython-widgets/dropdown.ipynb
- [ ] ipypython-widgets/filter_example.ipynb
- [ ] ipypython-widgets/mouse_events.ipynb
- [ ] ipypython-widgets/plotly-widgets.ipynb
- [ ] legacy/violin.ipynb
- [ ] mapbox.ipynb
- [ ] offline/plotly-offline.ipynb
- [ ] gmail.ipynb
- [ ] html-repots.ipynb
- [ ] scientific/plotly-mesh-3d.ipynb
- [ ] scientific/chord.ipynb
- [ ] scientific/contour.ipynb
- [ ] scientific/dendograms.ipynb
- [ ] scientific/filled-chord.ipynb
- [ ] scientific/networkx.ipynb
- [ ] statistical/cont-error-bars.ipynb
- [ ] statistical/scatterplot-matrix.ipynb
- [ ] style/colorscales.ipynb
- [ ] style/images.ipynb
- [ ] style/matplotlib-colorscales.ipynb
- [ ] subplots/mixed-subplots.ipynb
- [ ] user_guide/getting-started.ipynb

**Comment by bcdunbar** [comment]
Looks like I have them covered. Thus, I'm closing the issue for now. Although, there may be some that I have missed, so feel free to reopen the issue if you come across any.
