### ISSUE TITLE
dateTime format %c is wrong

### ISSUE THREAD

**Issue by alexcjohnson** [plotly/documentation#919]
https://help.plot.ly/date-format-and-time-series/ - not sure where this image came from:
![table 1](https://user-images.githubusercontent.com/2678795/38828728-f144fe0c-4184-11e8-9698-4488fd2206ff.png)
but %c is incorrect there - it shows "07/22/2012 11:24:45", but it actually gives "Sun Jul 22 11:24:45 2012" in [our default locale](https://github.com/plotly/plotly.js/blob/master/src/locale-en.js) (which matches d3's default locale).

In the attribute reference we just point to https://github.com/d3/d3-time-format/blob/master/README.md#locale_format - which is also confusing, as it doesn't actually tell you what these formats mean in the default locale but gives an example of what it *could* be, if you provided a locale that's different from the default.

**Comment by cldougl** [comment]
closing in favor of https://github.com/plotly/plotly.github.io/issues/355
