### ISSUE TITLE
clicking searched items within the plotly.js docs does not jump to the item 

### ISSUE THREAD

**Issue by SKalt** [plotly/documentation#925]
Steps to reproduce this issue:
1. go to //plot.ly/javascript/reference/
2. type 'button' into the search bar
3. click any of the search items

At this point if you clicked the first item, the URL is https://plot.ly/javascript/reference/#layout-xaxis-rangeselector-buttons-items.  `document.getElementById('layout-xaxis-rangeselector-buttons-items')` returns an empty NodeList. Manually navigating to layout > xaxis > rangeselector > buttons shows no subitems labeled "items". Instead, there are other subelements corresponding to each of the properties of  a layout >... > buttons > item.

It looks like this issue is the search going out-of-sync with what's actually on the page.

**Comment by michaelbabyn** [comment]
closed by #1069
