### ISSUE TITLE
Add info about new legend events 

### ISSUE THREAD

**Issue by etpinard** [plotly/documentation#937]
from https://github.com/plotly/plotly.js/pull/2581#issuecomment-393603619

**Comment by jacobq** [comment]
In particular, I'd like to see examples / recommendations regarding how to prevent firing the click handlers in the case of doubleclick events. (IIRC, this problem also occurs when dealing directly with the DOM, e.g. https://output.jsbin.com/nikimir/3)

**Comment by michaelbabyn** [comment]
closed by [#1002](https://github.com/plotly/documentation/pull/1002)
