### ISSUE TITLE
Full reference documentation missing

### ISSUE THREAD

**Issue by mounica-naidu** [plotly/documentation#939]
Documentation is missing at the link https://plot.ly/javascript/reference/. Maybe the URLs are missing?
![missing_docs](https://user-images.githubusercontent.com/37471532/40914045-4945db3e-6814-11e8-97e3-252989196145.PNG)

**Comment by nicolaskruchten** [comment]
Yikes, there does seem to be a problem there!

**Comment by cldougl** [comment]
@mounica-naidu feel free to let us know if you see any other problems
