### ISSUE TITLE
offline charts not appearing on config doc

### ISSUE THREAD

**Issue by cldougl** [plotly/documentation#941]
https://plot.ly/python/configuration-options/#offline-configuration-options
- [x] offline charts not appearing
- [x] Add `modeBarButtonsToRemove` example

**Comment by cldougl** [comment]
Add `modeBarButtonsToRemove` example

**Comment by bcdunbar** [comment]
done https://github.com/plotly/documentation/commit/5c9223e8928a1917e654ab1a4f514bd5c31d4517
