### ISSUE TITLE
Update r/LaTeX examples

### ISSUE THREAD

**Issue by cpsievert** [plotly/documentation#943]
LaTeX rendering is now supported in R, time to update https://plot.ly/r/LaTeX/! 🎉  

https://github.com/ropensci/plotly/commit/bf5a1e9daeda7fda1e71a6d121018b96835519ee

For some basic examples, see ?TeX. For use with **rmarkdown**, see:

https://github.com/ropensci/plotly/blob/master/inst/examples/rmd/MathJax/index.Rmd

I'll also be doing a blog post about setting up MathJax locally...stay tuned

**Comment by bcdunbar** [comment]
updated in https://github.com/plotly/documentation/commit/b2f3e74855fca263bf8516c4ef159e4c0a84274f
