### ISSUE TITLE
Static export in R via orca

### ISSUE THREAD

**Issue by cpsievert** [plotly/documentation#950]
I'm gonna start suggesting folks use `orca()` over `export()`, so we should update the "Export locally" section of this page:

https://plot.ly/r/static-image-export/

https://github.com/ropensci/plotly/blob/master/R/orca.R

**Comment by bhavenm** [comment]
I am using orca. For some reason, it does not seems to be working. plotly command generates an image and I see it in my browser, however, when I try to generate a png file using orca() command, it generates an empty png file with the name suggested in the orca function but it does not have any data in it. Please let me know if I am missing something here.
