### ISSUE TITLE
igraph docs are not working

### ISSUE THREAD

**Issue by Kully** [plotly/documentation#953]
Here is a healthy list of examples that are failing that depend on `igraph`

Examples:

- [x] https://plot.ly/python/igraph-networkx-comparison/

 BROKEN: broken in general: igraph/jgraph issue

- [x] https://plot.ly/python/network-graphs/

 BROKEN: broken in general: igraph/jgraph issue

- [x] https://plot.ly/python/chord-diagram/

 BROKEN: igraph not working. See similar issues above

- [x] https://plot.ly/python/3d-network-graph/

 BROKEN: igraph/jgraph problem - similar to issues above

**Comment by cldougl** [comment]
Additional information provided by @jsigee87

The example written for using Networkx in Plotly uses an outdated version of Networkx (1.x). There were substantial changes between versions and the example [here](https://plot.ly/python/network-graphs/) no longer works.

## Error 1 
#### Scatter coordinates need to be cast as tuples
In particular, at least these two sections need to be modified- the lists need to be cast as tuples.

```
for edge in G.edges():
    x0, y0 = G.node[edge[0]]['pos']
    x1, y1 = G.node[edge[1]]['pos']
    edge_trace['x'] += tuple([x0, x1, None])
    edge_trace['y'] += tuple([y0, y1, None])
```

and

```
for node in G.nodes():
    x, y = G.node[node]['pos']
    node_trace['x'] += tuple([x])
    node_trace['y'] += tuple([y])
```

## Error 2 
#### Deprecated method

There is also an error in this section as there is no `adjacency_list()` method.

```
for node, adjacencies in enumerate(G.adjacency_list()):
    node_trace['marker']['color'].append(len(adjacencies))
    node_info = '# of connections: '+str(len(adjacencies))
    node_trace['text'].append(node_info)
```

It can be amended in several different ways, for example in my case I wanted to color nodes either magenta or cyan depending on what I set their _color_ attribute to be. Alternatively if you want to color based on `len(adjacencies)` you could instead call the method to calculate the degree of a node.

```
nodes = self.graph.nodes()
node_color_dict = nx.get_node_attributes(self.graph, 'color')
color_map = []
for node in nodes:
    if node_color_dict[node] is 'magenta':
        color_map.append('rgba(128, 0, 128, 0.7)')
    if node_color_dict[node] is 'cyan':
        color_map.append('rgba(0, 255, 255, 0.7)')
    else:
        #error handling
node_trace['marker']['color'] = tuple(color_map)
```
