### ISSUE TITLE
Layout.Scene not Working

### ISSUE THREAD

**Issue by Kully** [plotly/documentation#958]
The example below places a scene into the layout.
- no error is thrown for an incorrect param `cameraposition`
- scene is not getting updated but exists in layout.scene
- does not display scene in the dict representation when `layout` is run in code cell

```
import plotly.plotly as py
import plotly.graph_objs as go

import numpy as np

x, y, z = np.random.multivariate_normal(np.array([0,0,0]), np.eye(3), 200).transpose()
trace1 = go.Scatter3d(
    x=x,
    y=y,
    z=z,
    mode='markers',
    marker=dict(
        size=12,
        line=dict(
            color='rgba(217, 217, 217, 0.14)',
            width=0.5
        ),
        opacity=0.8
    )
)

x2, y2, z2 = np.random.multivariate_normal(np.array([0,0,0]), np.eye(3), 200).transpose()
trace2 = go.Scatter3d(
    x=x2,
    y=y2,
    z=z2,
    mode='markers',
    marker=dict(
        color='rgb(127, 127, 127)',
        size=12,
        symbol='circle',
        line=dict(
            color='rgb(204, 204, 204)',
            width=1
        ),
        opacity=0.9
    )
)
data = [trace1, trace2]

scene = dict(
    xaxis=dict(
        gridcolor='rgb(255, 255, 255)',
        zerolinecolor='rgb(255, 255, 255)',
        showbackground=True,
        backgroundcolor='rgb(230, 230,230)'
    ),
    yaxis=dict(
        gridcolor='rgb(255, 255, 255)',
        zerolinecolor='rgb(255, 255, 255)',
        showbackground=True,
        backgroundcolor='rgb(230, 230,230)'
    ),
    zaxis=dict(
        gridcolor='rgb(255, 255, 255)',
        zerolinecolor='rgb(255, 255, 255)',
        showbackground=True,
        backgroundcolor='rgb(230, 230,230)'
    ),
    cameraposition=[[0.2, 0.5, 0.5, 0.2], [0, 0, 0], 4.8]
)

layout = go.Layout(
    margin=dict(
        l=0,
        r=0,
        b=0,
        t=0
    ),
    scene=scene
)
fig = go.Figure(data=data, layout=layout)
py.iplot(fig)
```

**Comment by jmmease** [comment]
Thanks @Kully , I'll take a look but it probably won't be until tomorrow evening.

**Comment by jmmease** [comment]
@Kully I just tried this out with 3.0.0rc9 on Python 3.6 and I'm not getting the same behavior.  When I run the code above I get a validation error that `cameraposition` is an invalid property.  When I comment out that property I see the figure displayed as I would expect.

Could you double check with rc9 and Python 3.6?

**Comment by Kully** [comment]
> Could you double check with rc9 and Python 3.6?

I am also getting the expected figure when I comment out the `camerapostion`, _and_ the same invalid property error when I don't comment out.

I was using Python 2 before, so my guess is that it's version dependant.

**Comment by jmmease** [comment]
@Kully Could you clarify whether you think there's still a problem here?

**Comment by Kully** [comment]
It doesn't look like an issue anymore.
