### ISSUE TITLE
Python: Add breadcrumb grouping

### ISSUE THREAD

**Issue by jonmmease** [plotly/documentation#989]
A small suggestion that I think would help better orient people to where they are in the docs.

On the main Python documentation page there are top level groupings that show up under "Examples" on the left hand navigation bar.

![screen shot 2018-07-31 at 5 44 11 am](https://user-images.githubusercontent.com/15064365/43452180-d02ef53a-9484-11e8-8a3c-c4b9fdf589ef.png)

Consider the "Basic Charts" grouping. The body of the page has a previews of a collection of basic charts, along with a "More Basic Charts" button.

![screen shot 2018-07-31 at 5 45 10 am](https://user-images.githubusercontent.com/15064365/43452235-f410ec42-9484-11e8-9606-1603805cbd57.png)

If a user clicks on "More Basic Charts" they are taken to the page at https://plot.ly/python/basic-charts/.  At this point, the breadcrumb bar at the top of the page has "Help | API Libraries | Python". I propose appending "Basic Charts" to this breadcrumb path.

Next if a user clicks on, for example, "Sankey Diagram" they are taken to the Sankey Diagram example notebook page.  This page has a breadcrumb path of "Help | API Libraries | Python | Sankey Diagram".  The problem is, from this breadcrumb trail the user has no idea of how to get to the Sankey Diagram page from the main Python documentation page (They don't know that its considered a "Basic Chart"). This is especially a problem when people arrive at a trace page from Google. 

I propose that the breadcrumb trail in this case should be "Help | API Libraries | Python | Basic Charts
 | Sankey Diagram".  Clicking on "Basic Charts" would navigate to https://plot.ly/python/basic-charts/

Similarly, I propose that there be a breadcrumb grouping for all of the categories under "Examples" on the main page. For example, the "3D Axes in Python" page (https://plot.ly/python/3d-axes/) would have the breadcrumb path ""Help | API Libraries | Python | Layout Options | 3D Axes"

Thoughts?

**Comment by cldougl** [comment]
duplicate of: https://github.com/plotly/documentation/issues/855

**Comment by jonmmease** [comment]
Thanks!
