### ISSUE TITLE
Python: Version the docs with plotly.py

### ISSUE THREAD

**Issue by jonmmease** [plotly/documentation#990]
I would like to propose that we work towards hosting a build of the Python documentation for each released version of plotly.py, and add the version number to the URL.

This is the approach of the documentation for many other Python projects. See the pandas documentation for example: The documentation for a prior version of pandas can be accessed at https://pandas.pydata.org/pandas-docs/version/VERSION (e.g. https://pandas.pydata.org/pandas-docs/version/0.21.1/)

My thoughts is that we would continue to update the current URLs with the latest stable version.

Here are some motivations for the change:

 1. I would like to be able to update the legacy docs to use version 3 conventions (e.g. `go.layout.XAxis`), while still having a way for people to access the version 2.7 docs.

 2. I would like to work towards adding docstring hyperlinks to plotly.py that reference documentation pages, and with versioned docs these hyperlinks would always point to the page for the version of plotly.py that the person is actually using.

 3. I would like to get rid of the "Version Check" section at the top of all of the notebooks. It adds clutter and it wouldn't be needed if the docs were built for each version of plotly.py

How hard would this be from a documentation hosting point of view?

**Comment by cldougl** [comment]
@jonmmease I think this would be pretty easy from a hosting point of view (definitely for major releases). We can start this as we rewrite the new documentation.

**Comment by cldougl** [comment]
- copy content folders of `_posts/python/`
- add version2 to url: https://plot.ly/python/version2/pie-charts/
- in the version check link to the version 2 changelog: https://github.com/plotly/plotly.py/blob/master/CHANGELOG.md#270---2018-05-23

example:
### Version Check 
This is documentation for version 2 of plotly.py. See the [changelog](https://github.com/plotly/plotly.py/blob/master/CHANGELOG.md#270---2018-05-23) for differences between package versions. 
(suggestions on an improved message welcome :) )

**Comment by nicolaskruchten** [comment]
We basically did this :)
