### ISSUE TITLE
Python: Update all widget / JavaScript control docs with FigureWidget

### ISSUE THREAD

**Issue by jonmmease** [plotly/documentation#991]
We need to add documentation for the new version 3 `FigureWidget` class, and we need to remove all traces of the old `GraphWidget` class.

I would also suggest removing the discussion of the postMessage API from the Python docs (only talk about it in the JavaScript docs).

To start with, I think we could rename the "Add Custom Controls with JavaScript" to something like "Add Custom Interactivity with Jupyter Widgets". Then we convert all of the examples in this group to use FigureWidget.

In this section we should also add examples of:
 * Data selection callbacks.
 * "Create new view for output" in JupyterLab
 * Add examples from 
https://github.com/jonmmease/plotly_ipywidget_notebooks

We should also have a main `FigureWidget` overview page that explains the relationship between `FigureWidget` and `Figure`+`iplot`. And explains how to convert any of the other example into widget examples (e.g. `Figure` -> `FigureWidget` and remove `iplot`).

**Comment by michaelbabyn** [comment]
closed by #1043
